Utilities
ChrisTitusTech/linutil pull request #163
Opened 2024-08-15 06:57 UTC by jeevithakannan2

# Pull Request

## Title
Add utility functions to check missing packages and display server

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
- Refactor bash to sh -e
- Implement checks for packages xrandr, bluetoothctl, and nmcli
- Add installation of missing packages
- Include display server check (X11 vs Wayland)
- Warn users if running on Wayland
- Improve error handling and user feedback

## Testing
Tested on arch linux and ubuntu 24.04 . Ubuntu 22 and debian 12 systems has bugs. It also had bugs with the https://github.com/ChrisTitusTech/linutil/pull/131

## Impact
Resolves errors that occur when packages are not found. Warns the user if they are in wayland when using monitor utility.

## Additional Information
- Old shell version have errors when running all the utility scripts
- Only systemd implementation 

## Checklist
- [ ] My code adheres to the coding and style guidelines of the project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no errors/warnings/merge conflicts.

2024-08-16 05:07 UTC, ChrisTitusTech requested changes
You can't source files in sh
that is a bash only function

2024-08-16 07:00 UTC, jeevithakannan2 commented
@ChrisTitusTech changed source function to .

2024-08-16 07:01 UTC, jeevithakannan2 commented on src/commands/utils/monitor-control/change_orientation.sh
> -    IFS=$'\n' read -r -d '' -a monitor_array <<<"$monitor_list"
Fixes https://github.com/ChrisTitusTech/linutil/issues/164

2024-08-16 17:56 UTC, afonsofrancof approved these changes

2024-09-03 07:45 UTC, nnyyxxxx approved these changes

2024-09-04 21:49 UTC, ChrisTitusTech approved these changes

2024-09-04 21:49 UTC, merged