Update docs
ChrisTitusTech/linutil pull request #213
Opened 2024-08-30 01:08 UTC by nnyyxxxx

## Type of Change
- [x] New feature
- [x] Documentation Update
- [x] Refactoring

## Checklist
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-08-30 08:09 UTC, Real-MullaC requested changes

2024-08-30 08:09 UTC, Real-MullaC commented on docs/index.md
> -
This should be kept so people can see how to run the script.

2024-08-30 08:16 UTC, nnyyxxxx commented on docs/index.md
> -
in the description section of this PR I gave a reason on why I removed it

2024-08-30 08:23 UTC, Real-MullaC commented on docs/index.md
> -
We have it like this how it is in this docs on WinUtil.

2024-08-30 08:48 UTC, nnyyxxxx commented on docs/index.md
> -
I'll have a look, and do some changes then.

2024-09-10 21:19 UTC, ChrisTitusTech approved these changes

2024-09-10 21:19 UTC, merged