Adding lact for archlinux
ChrisTitusTech/linutil pull request #215
Opened 2024-09-01 15:15 UTC by Nightmare1984

# Pull Request

## Title
Adding Lact For ArchLinux And Adding Aur Helper Checker 

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
This PR Add's Amd Gpu Overclocking app And Aur Checker To Help Install Aur Package's In Linutil 

## Testing
Just Press Lact Setup For ArchLinux

## Impact
Overclocking And A Aur Checker For App's

## Additional Information
Adding Aur Checker To Make Lact Install Work

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-01 23:34 UTC, ChrisTitusTech requested changes
This is an agnostic common script run by debian and rhel systems. your checkenv changes would break them.

2024-09-02 16:16 UTC, nnyyxxxx commented
@Nightmare1984 remove lines 20-14 as its not need with the merge of #217

2024-09-02 16:32 UTC, nnyyxxxx requested changes
@Nightmare1984  remove lines 20-14 as its not needed with the merge of #217

2024-09-03 07:33 UTC, nnyyxxxx commented on src/commands/applications-setup/lact-setup.sh
> +    fi
No need for this if statement here, delete line 13, 15, and leave line 14 untouched.

2024-09-03 07:35 UTC, nnyyxxxx commented on src/commands/applications-setup/lact-setup.sh
> +    fi
@Nightmare1984 Please add support for more distros, take advice from the other scripts.

2024-09-06 00:03 UTC, nnyyxxxx commented on src/commands/applications-setup/lact-setup.sh
> +    checkAURHelper
"checkAURHelper" needs to be moved under "checkEnv"

2024-09-06 08:01 UTC, nnyyxxxx commented on src/commands/applications-setup/lact-setup.sh
> +        echo "Lact already Installed"
```suggestion
        echo "Lact already Installed"
        exit 1
```

2024-09-06 08:03 UTC, nnyyxxxx approved these changes
Looks good, just make sure you have tested this.

2024-09-06 09:36 UTC, Nightmare1984 commented
Lact rpm fedora file is broken from maker's GitHub release i Will Try to see if i can make it compile from source For Fedora user's To Fix The Issue.

2024-09-06 10:43 UTC, Nightmare1984 commented
i still got some work to do for other distro's github api not fetching the file right in the code

2024-09-06 11:55 UTC, nnyyxxxx commented
@Nightmare1984 Mark this PR as a draft until you figure it out.

2024-09-12 18:44 UTC, ChrisTitusTech commented
Sorry for the inconvenience. We had a massive restructure of the codebase to improve future development. Because of this can you update your PR to the new structure. Thank you for your assistance and contribution.

2024-09-14 20:11 UTC, closed without merging