Close linutil on Control-C, clear terminal on exit
ChrisTitusTech/linutil pull request #241
Opened 2024-09-05 14:54 UTC by cartercanedy

# Pull Request

## Title
Added the ability to exit the application with Control-C to match the expected behavior of some users
Added a screen blank on exit to prevent text present on screen from persisting from before starting the application.

## Type of Change
- [x] New feature
- [x] Bug fix
- [ ] Documentation Update
- [x] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
Control-C is the universal "I want to get out of here" chord. Having the binding only exist on the 'q' key makes it unintuitive to exit the app while running. It was only a few lines that needed to be added to accomplish this.

Also, I noticed that stale text would persist from my screen after a cargo run, so I added a final `terminal.clear()` at exit to prevent any old text from persisting

## Testing
I verified that both 'q' and Control-c behave as expected, and I ran a test neovim install to verify that package management functionality wasn't broken.

## Impact
I believe that this makes the application behave as a naive user would expect.

## Issue related to PR
- Resolves #236 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-05 14:59 UTC, cartercanedy commented
it looks like #239 also adds a tips box, if this gets merged, we might want to add a note for "Control-C" as well
@prschorn

2024-09-05 15:57 UTC, prschorn commented
@cartercanedy should we add the control-c note already on #239, or wait for this to merge and then create a second PR adding that?

2024-09-05 16:40 UTC, JustLinuxUser commented
This should not be merged, it brakes pressing CTRL-c when a command is running to stop it. Instead the whole app will just die. The approach to cleaning the screen is also wrong. There is no need to clear the screen, just no  need to restore the position either.

2024-09-05 16:58 UTC, cartercanedy commented
I'll rework the logic to scope the control-c to cancel installations if it's focused.

2024-09-05 17:07 UTC, cartercanedy commented
@JustLinuxUser Just fixed the edge case that you brought up, should be ready to review again

2024-09-05 17:31 UTC, Kingproone commented
Could esc be added as well? Even if not in this pr?

2024-09-05 17:38 UTC, JustLinuxUser requested changes
In general this is a pretty good PR, but you should try to minimize the diff file (if you are not doing a refactor pr, which this is not), and use proper methods when avilable, and don't brake the `cargo fmt`. You can just check if your code passes `cargo fmt` with `cargo fmt --check`

2024-09-05 17:38 UTC, JustLinuxUser commented on src/main.rs
> +
Don't put whitespace for no reason, keep the diff as small as possible

2024-09-05 17:38 UTC, JustLinuxUser commented on src/state.rs
> +                return false;
`key.modifiers` has a `.contains` method, use that

2024-09-05 17:38 UTC, JustLinuxUser commented on src/state.rs
> -                {
we use `cargo fmt` to format the code, don't brake the formatting for no reason

2024-09-05 17:40 UTC, JustLinuxUser commented
Hey, I know github supports shared pull requests, what to share the PR with me? I can add your CTRL-c handling logic to my PR, and we can both have credit, plus you get a GH achievement if you don't have it already

2024-09-05 17:45 UTC, cartercanedy commented on src/state.rs
> +                return false;
I feel like that's a pretty hard nit

2024-09-05 17:56 UTC, cartercanedy commented
> Hey, I know github supports shared (co-authored) pull requests, what to share the PR with me? I can add your CTRL-c handling logic to my PR, and we can both have credit, plus you get a GH achievement if you don't have it already @cartercanedy. And there is no chance of having a PR conflicting because Titus chose to apply 1 before / after the other, so everybody wins

it's pretty simple to just rebase on top of main if this gets merged

2024-09-05 18:10 UTC, JustLinuxUser commented
> > Hey, I know github supports shared (co-authored) pull requests, what to share the PR with me? I can add your CTRL-c handling logic to my PR, and we can both have credit, plus you get a GH achievement if you don't have it already @cartercanedy. And there is no chance of having a PR conflicting because Titus chose to apply 1 before / after the other, so everybody wins
> 
> it's pretty simple to just rebase on top of main if this gets merged

Yes, but rn the PRs will conflict with each other, if we make it 1 pr, it won't conflict with each other. But If I just delete the portion where I removed the restore position thingie from my PR the conflict gets resolved, so I will do that

2024-09-05 18:11 UTC, JustLinuxUser commented
1 last thing, mb don't add `esc` as another way to exit, `esc` is already used to exit from a terminated command / preview, and pressing it 1 more time is just too easy

2024-09-05 18:16 UTC, cartercanedy commented
> 1 last thing, mb don't add `esc` as another way to exit, `esc` is already used to exit from a terminated command / preview, and pressing it 1 more time is just too easy

I could go both ways. Esc would be the third way to exit, so kinda redundant. On the other hand, we use 'q' to exit previews, so the same argument you made could be applied there as well

2024-09-05 18:19 UTC, JustLinuxUser commented
> > 1 last thing, mb don't add `esc` as another way to exit, `esc` is already used to exit from a terminated command / preview, and pressing it 1 more time is just too easy
> 
> I could go both ways. Esc would be the third way to exit, so kinda redundant. On the other hand, we use 'q' to exit previews, so the same argument you made could be applied there as well

I didn't know that, I think ading `q` to exit previews is a bad idea too, you already had `Enter` and `esq`

2024-09-05 18:33 UTC, cartercanedy commented
> > > 1 last thing, mb don't add `esc` as another way to exit, `esc` is already used to exit from a terminated command / preview, and pressing it 1 more time is just too easy
> > 
> > 
> > I could go both ways. Esc would be the third way to exit, so kinda redundant. On the other hand, we use 'q' to exit previews, so the same argument you made could be applied there as well
> 
> I didn't know that, I think ading `q` to exit previews is a bad idea too, you already had `Enter` and `esq`

removed

2024-09-06 11:43 UTC, nnyyxxxx commented
Conflicts with #239

2024-09-06 16:34 UTC, cartercanedy commented
#239 should be deferred for a while, so it'll need to be rebased anyway. I think this is good to merge, just need approval

2024-09-10 23:50 UTC, cartercanedy commented
@ChrisTitusTech this should be good to go

2024-09-11 04:49 UTC, ChrisTitusTech approved these changes

2024-09-11 16:06 UTC, cartercanedy commented
sorry for all of the force-pushes, I was battling the buildbot in my own fork without realizing it

2024-09-12 18:44 UTC, ChrisTitusTech commented
Sorry for the inconvenience. We had a massive restructure of the codebase to improve future development. Because of this can you update your PR to the new structure. Thank you for your assistance and contribution.

2024-09-13 19:29 UTC, cartercanedy commented
@ChrisTitusTech rebase went smooth, ready to get merged

2024-09-15 23:12 UTC, ChrisTitusTech approved these changes

2024-09-16 20:41 UTC, merged