Updated README.md
ChrisTitusTech/linutil pull request #3
Opened 2024-06-09 02:22 UTC by rudra-code-creator

Updated readme

2024-06-17 22:11 UTC, 4yman-el requested changes

2024-06-17 22:11 UTC, 4yman-el commented on README.md
> +as fetured on CTT livestream: https://www.youtube.com/watch?v=X1vQ6va5xOc&t=2578s
```suggestion
as featured on CTT livestream: https://www.youtube.com/watch?v=X1vQ6va5xOc&t=2578s
```

2024-06-18 05:59 UTC, rudra-code-creator commented on README.md
> +as fetured on CTT livestream: https://www.youtube.com/watch?v=X1vQ6va5xOc&t=2578s
Nice catch!

2024-06-28 23:40 UTC, ChrisTitusTech approved these changes

2024-06-28 23:40 UTC, merged