feat(fedora): add nvidia proprietary driver setup script
ChrisTitusTech/linutil pull request #319
Opened 2024-09-09 13:42 UTC by harshv5094

This script allows us to install/remove nvidia driver in fedora system safely.

# Pull Request

## Title

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
This script allows fedora user to install and remove proprietary NVIDIA drivers properly, without locking their system to infinity state on startup.

## Testing
- Tested this script on my personal laptop with Fedora 40 Running on it.
- I've run this script multiple times to check if the driver is working properly.

## Additional Information
- After installing the NVIDIA driver, before rebooting, the user need to keep their system on for up to 5 min. then you need to run this command to check if your driver is installed properly or not. 
```sh
modinfo -F version nvidia
```
- So I've already implemented a solution for this in my script. I added a sleep timer for up to 4 minutes, so that the drivers can build in that time.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-09 18:51 UTC, jeevithakannan2 requested changes
We've refactored the scripts to remove most of the Bash-specific notations and ensure they are POSIX-compliant (sh). Please review the changes." You can also checkout my https://github.com/jeevithakannan2/linutil/tree/fedora-nvidia for your reference for this PR

2024-09-09 18:51 UTC, jeevithakannan2 commented on src/commands/system-setup/fedora/nvidia-proprietary-driver-setup.sh
> +#!/usr/bin/env bash
Use `#!/bin/sh -e` instead of `#!/usr/bin/env bash`

2024-09-09 18:51 UTC, jeevithakannan2 commented on src/commands/system-setup/fedora/nvidia-proprietary-driver-setup.sh
> +. "$(dirname "$0")/../../common-script.sh"
Remove "$(dirname "$0") 

It should be `. ../../common-script.sh`

2024-09-09 18:51 UTC, jeevithakannan2 commented on src/commands/system-setup/fedora/nvidia-proprietary-driver-setup.sh
> +function menu() {
Rename function to `installDriver`

2024-09-09 18:51 UTC, jeevithakannan2 commented on src/commands/system-setup/fedora/nvidia-proprietary-driver-setup.sh
> +      sudo dnf install akmod-nvidia xorg-x11-drv-nvidia-cuda -y
Check if driver is already installed before the installing the driver

Also use `$ESCALATION_TOOL` by calling checkEscalationTool function from common script instead of `sudo` in all places

2024-09-09 18:51 UTC, jeevithakannan2 commented on src/commands/system-setup/fedora/nvidia-proprietary-driver-setup.sh
> +    "Install Nvidia Drivers")
Check if the nvidia non-free repository is enabled or not if not enabled enable it

You can use the following code to do so

```sh
checkRepo() {
    REPO_ID="rpmfusion-nonfree-nvidia-driver"

    if [ $(dnf repolist enabled 2>/dev/null | grep "$REPO_ID" | wc -l) -gt 0 ]; then
        printf "%b\n" "${GREEN}Nvidia non-free repository is already enabled.${RC}"
    else	
        printf "%b\n" "${YELLOW}Nvidia non-free repository is not enabled. Enabling now...${RC}"
    
    	# Enable the repository
    	$ESCALATION_TOOL dnf config-manager --set-enabled "$REPO_ID"

    	# Verify if the repository is enabled
    	if [ $(dnf repolist enabled 2>/dev/null | grep "$REPO_ID" | wc -l) -gt 0 ]; then
        	printf "%b\n" "${GREEN}Nvidia non-free repository is now enabled...${RC}"
    	else
		printf "%b\n" "${RED}Failed to enable nvidia non-free repository...${RC}"
		exit 1
    	fi
    fi
}
```

2024-09-09 18:51 UTC, jeevithakannan2 commented on src/commands/system-setup/fedora/nvidia-proprietary-driver-setup.sh
> +      echo -e "${YELLOW} Stopping script for 4min, for building the drivers. Please don't kill the script!\n If the driver number is showing then your driver is installed properly.\n Else run the scr
use `printf "%b\n"` instead of `echo -e` in all places

2024-09-09 18:51 UTC, jeevithakannan2 commented on src/commands/system-setup/fedora/nvidia-proprietary-driver-setup.sh
> +
Check if driver is already installed before trying to uninstall driver

2024-09-09 18:51 UTC, jeevithakannan2 commented on src/commands/system-setup/fedora/nvidia-proprietary-driver-setup.sh
> +      sleep 4m
Instead of giving a direct 4m sleep you can use the a more robust approach
This will wait for 5min if the driver is built before 5 min it moves on if not it will wait for 5min.
If the driver is not built within 5 min the script should exit

```sh
for i in {1..5}; do
                if modinfo -F version nvidia > /dev/null 2>&1; then
                    printf "%b\n" "${GREEN}Driver installed successfully.${RC}"
                    printf "%b\n" "${GREEN}Installed driver version $(modinfo -F version nvidia)${RC}"
                    break
                fi
                printf "%b\n" "${YELLOW}Waiting for driver to be built...${RC}"
                sleep 1m
            done
```

2024-09-09 18:51 UTC, jeevithakannan2 commented on src/commands/system-setup/fedora/nvidia-proprietary-driver-setup.sh
> +echo -e "${YELLOW} Warning! This script only install drivers for GPU found in 2014 or later and this works on fedora 40 and above system ${RC}"
The warning should also include about the non-free repository

Warning! This script will enable Nvidia non-free repository and only install drivers for GPUs from 2014 or later. It works on fedora 40 and above.

2024-09-09 18:51 UTC, jeevithakannan2 commented on src/commands/system-setup/fedora/nvidia-proprietary-driver-setup.sh
> +      break
After the successful driver uninstall give out a driver uninstall successful message

2024-09-09 18:51 UTC, jeevithakannan2 commented on src/commands/system-setup/fedora/nvidia-proprietary-driver-setup.sh
> +      break
After the successful driver installation give out a driver installation successful message

2024-09-10 06:04 UTC, harshv5094 commented
@jeevithakannan2 I made changes according to your suggestion, and also I've used your script as reference to modify my own script

2024-09-10 08:49 UTC, nnyyxxxx commented on src/commands/system-setup/fedora/nvidia-proprietary-driver-setup.sh
> +userConfirmation
``checkEnv`` and ``checkEscalationTool`` need to called here

2024-09-10 08:50 UTC, nnyyxxxx commented on src/commands/system-setup/fedora/nvidia-proprietary-driver-setup.sh
> +    driverSetupMenu
```bash
    checkEnv
    checkEscalationTool
    checkRepo
    driverSetupMenu
```
These need to be at the bottom of the script.

2024-09-10 08:52 UTC, nnyyxxxx commented on src/commands/system-setup/fedora/nvidia-proprietary-driver-setup.sh
> +. ./../../common-script.sh
```suggestion
. ../../common-script.sh
```

2024-09-10 09:07 UTC, harshv5094 commented on src/commands/system-setup/fedora/nvidia-proprietary-driver-setup.sh
> +    driverSetupMenu
@nnyyxxxx I think `checkRepo` and `driverSetupMenu` should be in the `userConfirmation` 
function. Since, I want to enable `rpmfusion-nonfree-nvidia-driver` repo after user press yes. So I can do it like this.
```sh
...
userConfirmation() {
  read -p "Do you want to continue? (Y/N): " choice
  case "$choice" in
  y | Y)
    checkRepo
    driverSetupMenu
    return
    ;;
  n | N)
    printf "%b\n" "${RED} Exiting the Script ${RC}"
    return
    ;;
  *)
    printf "%b\n" "${RED} Invalid Option! ${RC}"
    userConfirmation
    ;;
  esac
}

printf "%b\n" "${YELLOW}Warning! This script will enable Nvidia non-free repository and only install drivers for GPUs from 2014 or later. It works on fedora 34 and above.${RC}"

checkEnv
checkEscalationTool
userConfirmation
```

2024-09-10 09:09 UTC, harshv5094 commented on src/commands/system-setup/fedora/nvidia-proprietary-driver-setup.sh
> +. ./../../common-script.sh
Okay, I'll fix it

2024-09-10 09:19 UTC, harshv5094 commented on src/commands/system-setup/fedora/nvidia-proprietary-driver-setup.sh
> +    driverSetupMenu
The reason I'm asking for user confirmation, is for them to check if their device gpu is made before 2014 or not. So they don't accidentally download the drivers which will break their distro.

2024-09-10 12:10 UTC, harshv5094 reviewed
All changes are executed

2024-09-11 03:16 UTC, jeevithakannan2 approved these changes

2024-09-12 07:26 UTC, harshv5094 commented
Should I Add VAAPI drivers for video acceleration?

2024-09-12 07:30 UTC, jeevithakannan2 commented
Yeah you could do that, also check whether the user's graphics card is compatible before proceeding with vaapi drivers installation

2024-09-12 08:02 UTC, jeevithakannan2 commented
It would be something like this
```sh
if command_exists nvidia-smi; then
  gpu_info=$(nvidia-smi --query-gpu=name --format=csv,noheader)
  printf "%b\n" "${GREEN}NVIDIA GPU detected: $gpu_info${RC}"
else
  printf "%b\n" "${RED}nvidia-smi not found or drivers not installed.{RC}"
  exit 1
fi

if echo "$gpu_info" | grep -Eq "GeForce (8|9|[1-9][0-9])|GTX|RTX"; then
  printf "%b\n" "${GREEN}Your GPU ($gpu_model) is GeForce 8 series or above.${RC}"
else
  printf "%b\n" "${RED}Your GPU ($gpu_model) is below GeForce 8 series.${RC}"
fi
```

Add few more informational message for users and it is a sample script develop your own script based on that

2024-09-12 15:41 UTC, harshv5094 commented
Yeah! This'll help a lot thanks @jeevithakannan2

2024-09-12 18:41 UTC, ChrisTitusTech commented
Sorry for the inconvenience. We had a massive restructure of the codebase to improve future development. Because of this can you update your PR to the new structure. Thank you for your assistance and contribution.

2024-09-13 15:43 UTC, harshv5094 commented
Okay @ChrisTitusTech, I'll do it now, and also thanks for checking in.

2024-09-13 15:48 UTC, harshv5094 commented
![image](https://github.com/user-attachments/assets/57d7c148-861a-412a-be29-d8f294a70632)
I'm having this problem

2024-09-13 16:22 UTC, nnyyxxxx commented
> ![image](https://private-user-images.githubusercontent.com/51878195/367361534-57d7c148-861a-412a-be29-d8f294a70632.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNDQ4MTUsIm5iZiI6MTcyNjI0NDUxNSwicGF0aCI6Ii81MTg3ODE5NS8zNjczNjE1MzQtNTdkN2MxNDgtODYxYS00MTJhLWJlMjktZDhmMjk0YTcwNjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDE2MjE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyODRiMDU1ZDc5ZjY3OWMzYjRkYjI0ZTFkYjViNWY0OTY2YTM1Y2IyZGVlOWI0NzdjN2EwZmQwMGQ2MzMyZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RGOsEQ2qgZfOzO0GSlFSXX-69YZmYTTUOSYnbPrUEyc) I'm having this problem now. I'm unable to sync the repo

The file structure has changed, you'll have to rebase.

2024-09-13 17:15 UTC, nnyyxxxx commented on src/commands/system-setup/fedora/nvidia-proprietary-driver-setup.sh
> +  echo "2. Remove Nvidia Drivers"
No need for the uninstalling feature, see #362 for more information.

2024-09-13 17:23 UTC, harshv5094 commented on src/commands/system-setup/fedora/nvidia-proprietary-driver-setup.sh
> +  echo "2. Remove Nvidia Drivers"
Should I delete this pull request and create a fresh one?

2024-09-13 17:29 UTC, harshv5094 commented
So, I don't know how I can fix this issue so I'm going to create a new pull request, with proper precaution.

2024-09-13 17:29 UTC, closed without merging