Add a script to set up shell aliases for linutil
ChrisTitusTech/linutil pull request #354
Opened 2024-09-12 18:37 UTC by adamperkowski

# Add a script to set up shell aliases for linutil

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
ref #349, https://github.com/ChrisTitusTech/linutil/issues/349#issuecomment-2346816737

## Impact
Created a new manu entry and sh script.

## Issue related to PR
- Resolves #349

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-12 18:41 UTC, ChrisTitusTech commented
Sorry for the inconvenience. We had a massive restructure of the codebase to improve future development. Because of this can you update your PR to the new structure. Thank you for your assistance and contribution.

2024-09-12 18:51 UTC, adamperkowski commented
@ChrisTitusTech Updated. Everything works.

2024-09-12 22:56 UTC, lj3954 requested changes

2024-09-12 22:56 UTC, lj3954 commented on tabs/applications-setup/shell-aliases.sh
> +fi
```suggestion
```
We can move this to a precondition, in order for the script to not be displayed whatsoever in the case that the command already exists.

2024-09-12 22:56 UTC, lj3954 commented on tabs/applications-setup/tab_data.toml
> +script = "shell-aliases.sh"
```suggestion
script = "shell-aliases.sh"

[[data.preconditions]]
matches = false
data = "command_exists"
values = [ "linutil" ]
```

2024-09-12 23:41 UTC, adamperkowski commented on tabs/applications-setup/tab_data.toml
> +script = "shell-aliases.sh"
> We can move this to a precondition, in order for the script to not be displayed whatsoever in the case that the command already exists.

That's a good idea. Done.

2024-09-13 02:41 UTC, nnyyxxxx commented on tabs/applications-setup/shell-aliases.sh
> +for ((i=0; i<${#shells[@]}; i++)); do
This is not posix-compliant.

2024-09-13 02:41 UTC, nnyyxxxx commented on tabs/applications-setup/shell-aliases.sh
> +    if command_exists ${shells[$i]}; then
This is not posix-compliant.

2024-09-13 02:42 UTC, nnyyxxxx commented on tabs/applications-setup/shell-aliases.sh
> +        echo "Found ${shells[$i]}. Adding the alias..."
This is not posix compliant.

2024-09-13 02:42 UTC, nnyyxxxx commented on tabs/applications-setup/shell-aliases.sh
> +        config_file="$HOME/${configs[$i]}"
This is not posix compliant.

2024-09-13 02:42 UTC, nnyyxxxx commented on tabs/applications-setup/shell-aliases.sh
> +            if [ "${shells[$i]}" == "fish" ] || [ "${shells[$i]}" == "nu" ]; then     # Change config dirs for specific shells
This is not posix compliant.

2024-09-13 02:42 UTC, nnyyxxxx commented on tabs/applications-setup/shell-aliases.sh
> +                config_dir="$XDG_CONFIG_HOME/${shells[$i]}"
This is not posix compliant.

2024-09-13 02:42 UTC, nnyyxxxx commented on tabs/applications-setup/shell-aliases.sh
> +                config_file="$config_dir/${configs[$i]}"
This is not posix compliant.

2024-09-13 02:43 UTC, nnyyxxxx commented on tabs/applications-setup/shell-aliases.sh
> +            elif [ "${shells[$i]}" == "bash" ] && [ -f "/etc/skel/.bashrc" ]; then    # Default distro-specific config for bash
This is not posix compliant.

2024-09-13 02:43 UTC, nnyyxxxx commented on tabs/applications-setup/shell-aliases.sh
> +        if ! grep -Fxq "${aliases[$i]}" "$config_file"; then                          # Check if alias already exists
This is not posix compliant.

2024-09-13 02:44 UTC, nnyyxxxx commented on tabs/applications-setup/shell-aliases.sh
> +            echo "${aliases[$i]}" >> "$config_file"
This is not posix compliant.

2024-09-13 02:45 UTC, nnyyxxxx commented
@adamperkowski Too many bashisms in this PR; this will have to get refactored.

2024-09-13 03:25 UTC, nnyyxxxx commented on tabs/applications-setup/shell-aliases.sh
> +#!/bin/sh
```suggestion
#!/bin/sh -e
```

2024-09-13 12:55 UTC, adamperkowski commented
@nnyyxxxx Done.

2024-09-13 13:08 UTC, adamperkowski commented on tabs/applications-setup/shell-aliases.sh
> +#!/bin/sh
![image](https://github.com/user-attachments/assets/80c09c82-cfd8-45d8-b4f9-f824a57cbbb6)

2024-09-13 13:54 UTC, nnyyxxxx approved these changes
Looks great.

2024-09-13 14:25 UTC, lj3954 approved these changes

2024-09-18 19:00 UTC, closed without merging