SDDM theme with Autologin
ChrisTitusTech/linutil pull request #381
Opened 2024-09-14 16:00 UTC by mashrukk

# Pull Request

## SDDM Astronaut theme with Autologin
This script installs sddm-astronaut-theme from last stream and provides an option to enable autologin with sddm. Users can choose which desktop session they want to autologin on startup. After selecting desktop session, it will do a sddm restart and autologin to that desktop.

## Testing
If you want to test it first, do the following.
```
git clone --branch sddm https://github.com/mashrukk/linutil
cd linutil && cargo run
```

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-14 16:16 UTC, adamperkowski requested changes

2024-09-14 16:16 UTC, adamperkowski commented on tabs/applications-setup/sddm-theme.sh
> +if ! command -v sddm &> /dev/null; then
```suggestion
if ! command -v sddm > /dev/null 2>&1; then
```

not posix-compliant

2024-09-14 16:16 UTC, adamperkowski commented on tabs/applications-setup/sddm-theme.sh
> +read -p "Do you want to enable autologin? (y/n): " enable_autologin
```suggestion
read -r -p "Do you want to enable autologin? (y/n): " enable_autologin
```

not posix-compliant

2024-09-14 16:16 UTC, adamperkowski commented on tabs/applications-setup/sddm-theme.sh
> +if [[ $enable_autologin =~ ^[Yy]$ ]]; then
```suggestion
if [ "$enable_autologin" = "y" ] || [ "$enable_autologin" = "Y" ]; then
```

not posix-compliant

2024-09-14 16:28 UTC, adamperkowski requested changes

2024-09-14 16:28 UTC, adamperkowski commented on tabs/applications-setup/sddm-theme.sh
> +            $ESCALATION_TOOL pacman -S --needed --noconfirm sddm qt6-svg
use $PACKAGER instead of calling `apt-get` for example. 
and you can change `apt-get)` to `apt-get|nala)`

2024-09-14 16:28 UTC, adamperkowski commented on tabs/applications-setup/sddm-theme.sh
> +            printf "${RED}Unsupported package manager. Please install SDDM manually.${RC}\n"
add `"%b\n"`

2024-09-14 16:28 UTC, adamperkowski commented on tabs/applications-setup/sddm-theme.sh
> +    printf "${YELLOW}Installing SDDM login manager...${RC}\n"
add `"%b\n"`

2024-09-14 16:28 UTC, adamperkowski commented on tabs/applications-setup/sddm-theme.sh
> +            $ESCALATION_TOOL pacman -S --needed --noconfirm sddm qt6-svg
also, make a `DEPENDENCIES` var with `sddm qt6-svg` and install `$DEPENDENCIES`

2024-09-14 16:31 UTC, adamperkowski commented on tabs/applications-setup/sddm-theme.sh
> +USERNAME=$(whoami)
also u can use `$USER` env var

2024-09-14 16:33 UTC, adamperkowski commented on tabs/applications-setup/sddm-theme.sh
> +$ESCALATION_TOOL systemctl restart sddm
https://github.com/ChrisTitusTech/linutil/pull/375#discussion_r1759724142

2024-09-14 16:34 UTC, adamperkowski commented
And please don't open any more PRs for the same thing

2024-09-14 16:34 UTC, mashrukk commented on tabs/applications-setup/sddm-theme.sh
> +    printf "${YELLOW}Installing SDDM login manager...${RC}\n"
printf  "%b\n" "${YELLOW} ?

2024-09-14 16:36 UTC, adamperkowski commented on tabs/applications-setup/sddm-theme.sh
> +    printf "${YELLOW}Installing SDDM login manager...${RC}\n"
```suggestion
    printf "%b\n" "${YELLOW}Installing SDDM login manager...${RC}\n"
```

2024-09-14 16:44 UTC, adamperkowski commented on tabs/applications-setup/sddm-theme.sh
> -            printf "${RED}Unsupported package manager. Please install SDDM manually.${RC}\n"
without `\n` at the end

2024-09-14 17:05 UTC, mashrukk commented
@nnyyxxxx @adamperkowski Check for issues

2024-09-14 17:11 UTC, adamperkowski requested changes

2024-09-14 17:11 UTC, adamperkowski commented on tabs/applications-setup/sddm-theme.sh
> +                $ESCALATION_TOOL ${PACKAGER} install -y sddm qt6-svg
what about dnf and `qt6-qtsvg`?
zypper with `--non-interactive` (or `-n`)?

2024-09-14 17:11 UTC, adamperkowski commented on tabs/applications-setup/sddm-theme.sh
> +USERNAME=$(whoami)
no need for this with `$USER`

2024-09-14 17:11 UTC, adamperkowski commented on tabs/applications-setup/sddm-theme.sh
> +    $ESCALATION_TOOL sed -i '1i[Autologin]\nUser = '"$USERNAME"'\nSession = '"$actual_session"'\n' /etc/sddm.conf
```suggestion
    $ESCALATION_TOOL sed -i '1i[Autologin]\nUser = '"$USER"'\nSession = '"$actual_session"'\n' /etc/sddm.conf
```

2024-09-14 17:20 UTC, nnyyxxxx commented on tabs/applications-setup/sddm-theme.sh
> +    printf "${YELLOW}Installing SDDM...${RC}\n"
```suggestion
    printf "${YELLOW}Installing SDDM...${RC}"
```

2024-09-14 17:21 UTC, nnyyxxxx commented on tabs/applications-setup/sddm-theme.sh
> +            $ESCALATION_TOOL dnf update
Remove every update, no need for them.

2024-09-14 17:25 UTC, nnyyxxxx commented on tabs/applications-setup/sddm-theme.sh
> +            printf "${RED}Unsupported package manager. Please install SDDM manually.${RC}"
Every printf with a color code must be:

``printf "%b\n"``

2024-09-14 17:26 UTC, mashrukk commented
@nnyyxxxx @adamperkowski Check for issues

2024-09-14 17:26 UTC, nnyyxxxx commented on tabs/applications-setup/sddm-theme.sh
> +            printf "${RED}Unsupported package manager. Please install SDDM manually.${RC}"
> Every printf with a color code must be:
> 
> `printf "%b\n"`

@mashrukk

2024-09-14 17:29 UTC, mashrukk commented on tabs/applications-setup/sddm-theme.sh
> +            printf "${RED}Unsupported package manager. Please install SDDM manually.${RC}"
like this?  printf "%b\n" "${RED}Unsupported package manager. Please install SDDM manually.${RC}"

2024-09-14 17:30 UTC, adamperkowski requested changes

2024-09-14 17:30 UTC, adamperkowski commented on tabs/applications-setup/sddm-theme.sh
> +            $ESCALATION_TOOL pacman -S --needed --noconfirm sddm qt6-svg
Change these back to `$PACKAGER`

2024-09-14 17:30 UTC, adamperkowski commented on tabs/applications-setup/sddm-theme.sh
> +    printf "${YELLOW}Installing SDDM...${RC}"
```suggestion
    printf "%b\n" "${YELLOW}Installing SDDM...${RC}"
```

2024-09-14 17:30 UTC, adamperkowski commented on tabs/applications-setup/sddm-theme.sh
> +            printf "${RED}Unsupported package manager. Please install SDDM manually.${RC}"
```suggestion
            printf "%b\n" "${RED}Unsupported package manager. Please install SDDM manually.${RC}"
```

2024-09-14 17:31 UTC, nnyyxxxx commented on tabs/applications-setup/sddm-theme.sh
> +            printf "${RED}Unsupported package manager. Please install SDDM manually.${RC}"
> @nnyyxxxx like this? printf "%b\n" "${RED}Unsupported package manager. Please install SDDM manually.${RC}"

Every single printf with a color code must be printf "%b\n" instead of just printf

2024-09-14 17:34 UTC, adamperkowski requested changes

2024-09-14 17:34 UTC, adamperkowski commented on tabs/applications-setup/sddm-theme.sh
> +        apt-get)
```suggestion
        apt-get|nala)
```

2024-09-14 17:34 UTC, adamperkowski commented on tabs/applications-setup/sddm-theme.sh
> +            $ESCALATION_TOOL pacman -S --needed --noconfirm sddm qt6-svg
```suggestion
            $ESCALATION_TOOL "$PACKAGER" install -y sddm qt6-svg
            ;;
        zypper)
            $ESCALATION_TOOL "$PACKAGER" --non-interactive install sddm qt6-qtsvg
            ;;
        dnf)
            $ESCALATION_TOOL "$PACKAGER" install -y sddm qt6-qtsvg
            ;;
        pacman)
            $ESCALATION_TOOL "$PACKAGER" -S --needed --noconfirm sddm qt6-svg
```

2024-09-14 17:39 UTC, nnyyxxxx commented
@mashrukk Don't make any more changes to this. It's perfect how it is now.

2024-09-14 17:39 UTC, nnyyxxxx approved these changes
Looks good at the time of reviewing; might be different if anything changes.

2024-09-14 17:40 UTC, mashrukk commented
> @mashrukk Don't make any more changes to this. It's perfect how it is now.

@nnyyxxxx @adamperkowski  I won't. Thanks for steering me in the right direction

2024-09-14 17:42 UTC, nnyyxxxx commented on tabs/applications-setup/tab_data.toml
> +script = "sddm-theme.sh"
```suggestion
script = "sddm-setup.sh"
```

2024-09-14 17:42 UTC, nnyyxxxx commented on tabs/applications-setup/sddm-theme.sh
> +#!/bin/sh -e
Change this file name to sddm-setup.sh

2024-09-14 17:42 UTC, adamperkowski commented on tabs/applications-setup/tab_data.toml
> +script = "sddm-theme.sh"
```suggestion
name = "SDDM"
```

2024-09-14 17:42 UTC, nnyyxxxx commented
@mashrukk These are the last 2 changes we request of you, thank you for your contribution otherwise.

2024-09-14 17:42 UTC, adamperkowski commented on tabs/applications-setup/tab_data.toml
> +script = "sddm-theme.sh"
and `name` from "SDDM Theme" to just "SDDM"

2024-09-14 17:43 UTC, adamperkowski commented
@mashrukk If you'd give me write permissions on your branch, I could squash those commits into one

2024-09-14 17:53 UTC, adamperkowski requested changes

2024-09-14 17:53 UTC, adamperkowski commented on tabs/applications-setup/tab_data.toml
> +name = "SDDM Theme"
```suggestion
name = "SDDM"
```

One last change. That would be more accurate.
If you know how to, please squash those commits. I can do that if you want https://github.com/ChrisTitusTech/linutil/pull/381#issuecomment-2351081242

2024-09-14 17:55 UTC, nnyyxxxx commented on tabs/applications-setup/tab_data.toml
> +name = "SDDM Theme"
I agree with @adamperkowski

2024-09-14 17:57 UTC, mashrukk commented on tabs/applications-setup/tab_data.toml
> +name = "SDDM Theme"
SDDM theme is fine. People can just install sddm without using linutil.

2024-09-14 17:58 UTC, adamperkowski commented on tabs/applications-setup/tab_data.toml
> +name = "SDDM Theme"
Your script doesn't only install the theme. `SDDM Theme` is misleading.

2024-09-14 17:58 UTC, nnyyxxxx commented on tabs/applications-setup/tab_data.toml
> +name = "SDDM Theme"
> SDDM theme is fine.

I disagree.

2024-09-14 18:00 UTC, adamperkowski commented on tabs/applications-setup/tab_data.toml
> +name = "SDDM Theme"
> The synergy should be kept within the toml file.

And the TUI / UX

2024-09-14 18:03 UTC, nnyyxxxx commented on tabs/applications-setup/tab_data.toml
> +name = "SDDM Theme"
> > The synergy should be kept within the toml file.
> 
> And the TUI / UX

@mashrukk

2024-09-14 18:03 UTC, mashrukk commented on tabs/applications-setup/tab_data.toml
> +name = "SDDM Theme"
Okay.

2024-09-14 18:11 UTC, adamperkowski reviewed
As @nnyyxxxx said: this needs testing, the commits need squashing. (not quoting)

Code looks good for now, although this might change after the tests. I could test this out later when I'm able to, then I'll approve the changes.

2024-09-14 18:52 UTC, mashrukk commented
@adamperkowski check invite

2024-09-14 19:19 UTC, adamperkowski commented
@mashrukk got it

2024-09-14 21:26 UTC, adamperkowski approved these changes
After c5c06fdbaa161f7a382c2b4cbceb796ffd9fab99 & 581c243160a45d22867585dc784f97fc4af75d84 everything works as expected.

Tested on: Debian 12.6, Ubuntu 24.04 LTS & Arch 2024.09.01

2024-09-15 06:08 UTC, mashrukk commented
Perfect

2024-09-15 06:14 UTC, mashrukk commented
@adamperkowski To check dependencies required check [sddm-astronaut-theme](https://github.com/Keyitdev/sddm-astronaut-theme)

2024-09-15 07:01 UTC, guruswarupa commented
Duplicate of #228

2024-09-15 07:35 UTC, mashrukk commented
> Duplicate of #228 partially

I appreciate your work. But Instead of making a separate script. It's better to include SDDM with auto login functionality.

2024-09-15 07:39 UTC, mashrukk commented
> Duplicate of #228 partially

@guruswarupa I appreciate your work. But Instead of making a separate autologin script. It's better to have SDDM with auto login functionality.

2024-09-15 07:47 UTC, guruswarupa commented
> > Duplicate of #228 partially
> 
> @guruswarupa I appreciate your work. But Instead of making a separate autologin script. It's better to have SDDM with auto login functionality.

my script auto-login for multiple display managers. this pr should just work on setting up the theme and not adding features  such as autologin which is part of util features. where user can choose to keep autologin on or not. what if he doesn't need autologin but wants to have the theme setup? hope you get my point.

2024-09-15 07:49 UTC, guruswarupa commented
> > > Duplicate of #228 partially
> > 
> > 
> > @guruswarupa I appreciate your work. But Instead of making a separate autologin script. It's better to have SDDM with auto login functionality.
> 
> my script auto-login is for multiple display managers. this pr should just work on setting up the theme and not adding features such as autologin which is part of util features, wherein user can choose to keep autologin on or not. what if he doesn't need autologin but wants to have the theme setup? hope you get my point.

whats your take on it? @adamperkowski @nnyyxxxx

2024-09-15 07:52 UTC, mashrukk commented
> > > Duplicate of #228 partially
> > 
> > @guruswarupa I appreciate your work. But Instead of making a separate autologin script. It's better to have SDDM with auto login functionality.
> 
> my script auto-login is for multiple display managers. this pr should just work on setting up the theme and not adding features  such as autologin which is part of util features, wherein user can choose to keep autologin on or not. what if he doesn't need autologin but wants to have the theme setup? hope you get my point.

@guruswarupa  Check the script. Auto login is optional

2024-09-15 08:03 UTC, guruswarupa commented
@mashrukk yes, just working on installing sddm and then the theme is better option. and also restarting without asking user is unexpected behavior for script to do.

2024-09-15 08:06 UTC, guruswarupa commented
> @mashrukk yes, just working on installing sddm and then the theme is better option. and also restarting sddm without asking user is unexpected behavior for script to do.

2024-09-15 08:16 UTC, mashrukk commented
@guruswarupa That's a good point. But, If it's executed from TTY, if we don't restart. The user will have type enable --now. Right? In that case we can just enable it. I need your inputs @adamperkowski @nnyyxxxx

2024-09-15 08:21 UTC, guruswarupa commented
> @guruswarupa That's a good point. But, If it's executed from TTY and we don't restart. The user will have to type the command enable --now Right? In that case we can just enable it. I need your inputs @adamperkowski @nnyyxxxx

if its added to the sddm.conf, automatically when user restarts the theme should be loaded. in the sddm install add sudo systemctl enable sddm.service

2024-09-15 08:36 UTC, mashrukk commented
@guruswarupa Done

2024-09-16 14:39 UTC, closed without merging