System Cleanup
ChrisTitusTech/linutil pull request #396
Opened 2024-09-15 15:25 UTC by mashrukk

## System Cleanup Script

This is a comprehensive system cleanup script that performs various cleanup tasks.

### Key Features:
- Removes unused packages
- Common cleanup tasks (journalctl, temporary files, log truncation)
- Optional user cache and trash cleanup

This script provides a unified approach to system cleanup across different Linux distributions, improving system performance and freeing up disk space.

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-15 15:50 UTC, jeevithakannan2 commented on tabs/system-setup/system-cleanup.sh
> +            if command -v paru >/dev/null 2>&1; then
Use command_exists instead of command -v

It is a function in common script

2024-09-15 15:53 UTC, mashrukk commented on tabs/system-setup/system-cleanup.sh
> +            if command -v paru >/dev/null 2>&1; then
Ok

2024-09-15 15:53 UTC, adamperkowski requested changes

2024-09-15 15:53 UTC, adamperkowski commented on tabs/system-setup/system-cleanup.sh
> +            $ESCALATION_TOOL du -h /var/cache/apt
Why escalate here?

2024-09-15 15:53 UTC, adamperkowski commented on tabs/system-setup/system-cleanup.sh
> +            fi
add `checkAURHelper` from common-script if you want to, if not use

```suggestion
            if command_exists paru >/dev/null 2>&1; then
                paru -c
            elif command_exists yay >/dev/null 2>&1; then
                yay -c
            fi
```

2024-09-15 15:53 UTC, adamperkowski commented on tabs/system-setup/system-cleanup.sh
> +    printf "%b\n" "${YELLOW}Performing comprehensive system cleanup...${RC}"
```suggestion
    printf "%b\n" "${YELLOW}Performing system cleanup...${RC}"
```

2024-09-15 15:53 UTC, adamperkowski commented on tabs/system-setup/system-cleanup.sh
> +            printf "%b\n" "${RED}Unsupported package manager. Unable to perform system cleanup.${RC}"
```suggestion
            printf "%b\n" "${RED}Unsupported package manager.${RC}"
```

2024-09-15 15:53 UTC, adamperkowski commented on tabs/system-setup/system-cleanup.sh
> +    printf "%b\n" "${GREEN}Comprehensive system cleanup completed.${RC}"
```suggestion
    printf "%b\n" "${GREEN}System cleanup completed.${RC}"
```

2024-09-15 15:53 UTC, adamperkowski commented on tabs/system-setup/system-cleanup.sh
> +    printf "%b\n" "${YELLOW}Do you want to clean up old cache files and empty the trash? (y/n)${RC}"
```suggestion
    printf "%b\n" "${YELLOW}Clean up old cache files and empty the trash? (y/N)${RC}"
```

2024-09-15 15:53 UTC, jeevithakannan2 commented on tabs/system-setup/system-cleanup.sh
> +            find ~/.cache/ -type f -atime +5 -delete
I dont think it's a good idea to clean the .cache folder as it holds thumbnails, etc. This would make loading of those files slower. I would not recommend deleting .cache

2024-09-15 16:00 UTC, adamperkowski commented on tabs/system-setup/system-cleanup.sh
> +    printf "%b\n" "${YELLOW}Clean up old cache files and empty the trash? (y/N)${RC}"
```suggestion
    printf "%b" "${YELLOW}Clean up old cache files and empty the trash? (y/N) ${RC}"
```

2024-09-15 16:00 UTC, mashrukk commented on tabs/system-setup/system-cleanup.sh
> +            find ~/.cache/ -type f -atime +5 -delete
@jeevithakannan2 Using tools like BleachBit clears the cache and reloads thumbnails, which is why I made it optional for users.

2024-09-15 16:01 UTC, jeevithakannan2 commented on tabs/system-setup/system-cleanup.sh
> +            $ESCALATION_TOOL du -h /var/cache/apt
If you want to use du in /var it requires escalation in some distros

2024-09-15 16:42 UTC, adamperkowski approved these changes
Looks good

2024-09-16 05:19 UTC, jeevithakannan2 commented on tabs/system-setup/system-cleanup.sh
> +            find ~/.cache/ -type f -atime +5 -delete
Ok thanks for the information

2024-09-17 22:05 UTC, closed without merging