feat: Implement minimum TUI size
ChrisTitusTech/linutil pull request #425
Opened 2024-09-16 17:50 UTC by jeevithakannan2

# Pull Request

## Title
Implement minimum TUI size

## Type of Change
- [x] New feature
- [x] UI/UX improvement

## Description
- Add a warning message stating that current terminal size is too small
- Prevents entries from not appearing on screen. Refer issue https://github.com/ChrisTitusTech/linutil/issues/242
- The method to resolve the issue is to render the TUI only when the size of TUI is above a certain threshold

![warning](https://github.com/user-attachments/assets/e2416b28-6ff4-4e38-930f-69d8b33e6483)

## Impact
- Disables users from accessing the UI when the terminal size is small 

## Issue related to PR
- Resolves https://github.com/ChrisTitusTech/linutil/issues/242

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-16 19:14 UTC, adamperkowski approved these changes

2024-09-16 21:37 UTC, adamperkowski requested changes

2024-09-16 21:37 UTC, adamperkowski commented on tui/src/state.rs
> +            if key.code == KeyCode::Char('q') {
```suggestion
            if key.code == KeyCode::Char('q')
                || key.code == KeyCode::Char('c') && key.modifiers.contains(KeyModifiers::CONTROL)
            {
```

2024-09-16 23:28 UTC, adamperkowski approved these changes

2024-09-17 00:40 UTC, nnyyxxxx approved these changes

2024-09-17 01:05 UTC, nnyyxxxx commented
Nice! bashtop also has a feature like this.
![image](https://github.com/user-attachments/assets/6a8cdeba-cb89-4fee-bbdb-c4a7c8bb67bb)

2024-09-17 01:18 UTC, jeevithakannan2 commented
I see, I think i should change Terminal size too small to current size. What do you think ?

2024-09-17 01:21 UTC, nnyyxxxx commented
> I see, I think i should change Terminal size too small to current size. What do you think ?

No the current version is fine how it is.

2024-09-18 18:49 UTC, ChrisTitusTech approved these changes

2024-09-18 18:49 UTC, merged