System Cleanup
ChrisTitusTech/linutil pull request #478
Opened 2024-09-18 20:23 UTC by mashrukk

## System Cleanup Script
This is a comprehensive system cleanup script that performs various cleanup tasks.
#### Key Features:
- Removes unused packages
- Common cleanup tasks (journalctl, temporary files, log truncation)
- Optional user cache and trash cleanup
This script provides a unified approach to system cleanup across different Linux distributions, improving system performance and freeing up disk space.
## Type of Change
- [x] New feature
## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-18 20:49 UTC, adamperkowski requested changes

2024-09-18 20:49 UTC, adamperkowski commented on tabs/system-setup/system-cleanup.sh
> +            $ESCALATION_TOOL "$PACKAGER" -Rns "$(pacman -Qtdq)" --noconfirm
```suggestion
            "$ESCALATION_TOOL" "$PACKAGER" clean
            "$ESCALATION_TOOL" "$PACKAGER" autoremove -y
            "$ESCALATION_TOOL" "$PACKAGER" autoclean
            "$ESCALATION_TOOL" du -h /var/cache/apt
            "$ESCALATION_TOOL" "$PACKAGER" clean
            ;;
        zypper)
            "$ESCALATION_TOOL" "$PACKAGER" clean -a
            "$ESCALATION_TOOL" "$PACKAGER" tidy
            "$ESCALATION_TOOL" "$PACKAGER" cc -a
            ;;
        dnf)
            "$ESCALATION_TOOL" "$PACKAGER" clean all
            "$ESCALATION_TOOL" "$PACKAGER" autoremove -y
            ;;
        pacman)
            "$ESCALATION_TOOL" "$PACKAGER" -Sc --noconfirm
            "$ESCALATION_TOOL" "$PACKAGER" -Rns "$(pacman -Qtdq)" --noconfirm
```

2024-09-18 20:49 UTC, adamperkowski commented on tabs/system-setup/system-cleanup.sh
> +    printf "%b\n" "${GREEN}System cleanup completed.${RC}"
Remove this line or change it to
```suggestion
    printf "%b\n" "${GREEN}Package manager cleanup completed.${RC}"
```

2024-09-18 20:49 UTC, adamperkowski commented on tabs/system-setup/system-cleanup.sh
> +    $ESCALATION_TOOL journalctl --vacuum-time=3d
```suggestion
    "$ESCALATION_TOOL" find /var/tmp -type f -atime +5 -delete
    "$ESCALATION_TOOL" find /tmp -type f -atime +5 -delete
    "$ESCALATION_TOOL" find /var/log -type f -name "*.log" -exec truncate -s 0 {} \;
    "$ESCALATION_TOOL" journalctl --vacuum-time=3d
```

2024-09-18 20:49 UTC, adamperkowski commented on tabs/system-setup/system-cleanup.sh
> +        [Yy]*)
```suggestion
        y|Y)
```

To match other scripts.

2024-09-18 21:06 UTC, mashrukk commented on tabs/system-setup/system-cleanup.sh
> +            $ESCALATION_TOOL "$PACKAGER" -Rns "$(pacman -Qtdq)" --noconfirm
Should it be within qoutes? I removed them cause i thought $ESCALATION_TOOL is correct

2024-09-18 21:09 UTC, adamperkowski commented on tabs/system-setup/system-cleanup.sh
> +            $ESCALATION_TOOL "$PACKAGER" -Rns "$(pacman -Qtdq)" --noconfirm
Should be. #454 would get merged today, but Chris messed it up when trying to resolve conflicts.

2024-09-18 21:12 UTC, nnyyxxxx commented
@mashrukk Can you stop spamming PRs? I saw your history and you just keep closing and then re-opening the PR for some reason? I assume a bump to the top, please don't do that. It's getting pretty redundant...
![image](https://github.com/user-attachments/assets/84d674ec-12b8-4f81-8df7-744387637f57)

2024-09-18 21:18 UTC, mashrukk commented
@nnyyxxxx My bad. ok I'll try

2024-09-19 00:30 UTC, ChrisTitusTech approved these changes

2024-09-19 00:31 UTC, merged