enhancement: Update bashisms.yml
ChrisTitusTech/linutil pull request #480
Opened 2024-09-18 20:27 UTC by jeevithakannan2

## Type of Change
- [x] Hotfix

## Description
- Changed from apt to apt-get
- Added `apt-get update` with prior to the documentation https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/customizing-github-hosted-runners
- Use xargs to run the checks a little faster by parallel processing

## Testing
Tested on my repo works fine

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-18 20:32 UTC, adamperkowski requested changes

2024-09-18 20:32 UTC, adamperkowski commented on .github/workflows/bashisms.yml
> +        run: sudo apt-get update && sudo apt-get install devscripts
No need to update here. Containers provided by GitHub are already pre-updated.
```suggestion
        run: sudo apt install devscripts
```

2024-09-18 20:33 UTC, adamperkowski commented on .github/workflows/bashisms.yml
> +        run: find . -name '*.sh' | xargs -P 4 -n 1 checkbashisms
This is a good change actually. I wanted "fix" this in my PR when I first implemented this CI, but I forgot and it got merged.

2024-09-18 20:34 UTC, jeevithakannan2 commented on .github/workflows/bashisms.yml
> +        run: sudo apt-get update && sudo apt-get install devscripts
Please check with https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/customizing-github-hosted-runners

2024-09-18 20:35 UTC, adamperkowski approved these changes

2024-09-18 20:36 UTC, jeevithakannan2 commented on .github/workflows/bashisms.yml
> +        run: sudo apt-get update && sudo apt-get install devscripts
No problem thank you for taking a look

2024-09-19 00:17 UTC, ChrisTitusTech approved these changes

2024-09-19 00:18 UTC, merged