added browser setup script
ChrisTitusTech/linutil pull request #498
Opened 2024-09-19 08:23 UTC by guruswarupa

# Pull Request

## added browser setup script

- a script to install popular browsers(brave , chrome, chromium,firefox, vivaldi) for arch, debian, opensuse and fedora based distros

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-19 13:53 UTC, nnyyxxxx requested changes

2024-09-19 13:53 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +            $ESCALATION_TOOL ${PACKAGER} addrepo http://dl.google.com/linux/chrome/rpm/stable/x86_64 Google-Chrome
```suggestion
            "$ESCALATION_TOOL" "$PACKAGER" addrepo http://dl.google.com/linux/chrome/rpm/stable/x86_64 Google-Chrome
```

Do this for every one.

2024-09-19 13:53 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +            printf "%b\n" "The script does not support your Distro. Install manually.."
```suggestion
            printf "%b\n" "${RED}The script does not support your Distro. Install manually..${RC}"
```

2024-09-19 13:53 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +    printf "%b\n" "Installing Google Chrome..."
```suggestion
    printf "%b\n" "${YELLOW}Installing Google Chrome..${RC}."
```

2024-09-19 13:53 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +        apt-get)
```suggestion
        apt-get|nala)
```

2024-09-19 13:53 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +            cd google-chrome
```suggestion
            cd "$HOME/google-chrome"
```
Stop using hardcoded paths.

2024-09-19 13:53 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +    printf "%b\n" "Installing Mozilla Firefox..."
```suggestion
    printf "%b\n" "${YELLOW}Installing Mozilla Firefox...${RC}"
```

2024-09-19 13:53 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +            printf "%b\n" "The script does not support your Distro. Install manually.."
```suggestion
            printf "%b\n" "${RED}The script does not support your Distro. Install manually..${RC}"
```

2024-09-19 13:53 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +        apt-get)
```suggestion
        apt-get|nala)
```

2024-09-19 13:53 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +    case $PACKAGER in
```suggestion
    case "$PACKAGER" in
```

2024-09-19 13:53 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +    case $PACKAGER in
```suggestion
    case "$PACKAGER" in
```

2024-09-19 13:53 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +    case $PACKAGER in
```suggestion
    case "$PACKAGER" in
```

2024-09-19 13:53 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +    printf "%b\n" "Installing Brave..."
```suggestion
    printf "%b\n" "${YELLOW}Installing Brave...${RC}"
```

2024-09-19 13:53 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +            cd google-chrome
```suggestion
            cd "$HOME/google-chrome"
```
Stop using hardcoded paths.

2024-09-19 13:53 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +    printf "%b\n" "Installing Vivaldi..."
```suggestion
    printf "%b\n" "${YELLOW}Installing Vivaldi...${RC}"
```

2024-09-19 13:53 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +            printf "%b\n" "The script does not support your Distro. Install manually.."
```suggestion
            printf "%b\n" "${RED}The script does not support your Distro. Install manually..${RC}"
```

2024-09-19 13:53 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +     printf "%b\n" "Installing Brave..."
```suggestion
```

2024-09-19 13:53 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +    printf "%b\n" "Installing Chromium..."
```suggestion
    printf "%b\n" "${YELLOW}Installing Chromium...${RC}"
```

2024-09-19 13:53 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +    case $PACKAGER in
```suggestion
    case "$PACKAGER" in
```

2024-09-19 13:53 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +        apt-get)
```suggestion
        apt-get|nala)
```

2024-09-19 14:09 UTC, nnyyxxxx requested changes

2024-09-19 14:09 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +            "$ESCALATION_TOOL" "$PACKAGER" -S --noconfirm firefox
```BASH
        pacman)
            git clone https://aur.archlinux.org/google-chrome.git
            cd "$HOME/google-chrome"
            makepkg -s
            "$ESCALATION_TOOL" "$PACKAGER" -S --noconfirm firefox
```
Not sure whats going on here, why is it installing fire fox and chrome instead of brave?

2024-09-19 14:15 UTC, nnyyxxxx requested changes

2024-09-19 14:15 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +browser_setup
```suggestion
checkAURHelper
browser_setup
```

2024-09-19 14:15 UTC, nnyyxxxx commented on tabs/applications-setup/browser-setup.sh
> +            "$ESCALATION_TOOL" "$PACKAGER" -S --noconfirm firefox
Replace this
```bash
            git clone https://aur.archlinux.org/google-chrome.git
            cd "$HOME/google-chrome"
            makepkg -s
            "$ESCALATION_TOOL" "$PACKAGER" -S --noconfirm firefox
```
With this
```bash
            $AUR_HELPER -S brave-bin
```

2024-09-19 14:22 UTC, nnyyxxxx requested changes

2024-09-19 14:25 UTC, adamperkowski requested changes

2024-09-19 14:25 UTC, adamperkowski commented on tabs/applications-setup/browser-setup.sh
> +            "$ESCALATION_TOOL" "$PACKAGER" -U --noconfirm google-chrome-*-x86_64.pkg.tar.zst
```suggestion
            cd "$HOME/google-chrome" && makepkg --noconfirm -si
```

2024-09-19 14:25 UTC, adamperkowski commented on tabs/applications-setup/browser-setup.sh
> +            ;;
```suggestion
        pacman)
            "$ESCALATION_TOOL" "$PACKAGER" -S --noconfirm firefox
            ;;
```

2024-09-19 14:25 UTC, adamperkowski commented on tabs/applications-setup/browser-setup.sh
> +            $AUR_HELPER -S brave-bin
If you're using `AUR_HELPE`R here, why not on chrome?

2024-09-19 14:27 UTC, adamperkowski requested changes

2024-09-19 14:27 UTC, adamperkowski commented on tabs/applications-setup/browser-setup.sh
> +            ;;
Or even better,

```suggestion
        pacman)
            $AUR_HELPER -S google-chrome
            ;;
```

2024-09-19 14:27 UTC, adamperkowski commented on tabs/applications-setup/browser-setup.sh
> +            "$ESCALATION_TOOL" "$PACKAGER" -U --noconfirm google-chrome-*-x86_64.pkg.tar.zst
https://github.com/ChrisTitusTech/linutil/pull/498#discussion_r1766942591

2024-09-19 14:27 UTC, adamperkowski commented on tabs/applications-setup/browser-setup.sh
> +            makepkg -s
https://github.com/ChrisTitusTech/linutil/pull/498#discussion_r1766942591

2024-09-19 14:34 UTC, adamperkowski requested changes

2024-09-19 14:34 UTC, adamperkowski commented on tabs/applications-setup/browser-setup.sh
> +            "$ESCALATION_TOOL" "$PACKAGER" install google-chrome-stable
```suggestion
            "$ESCALATION_TOOL" "$PACKAGER" --non-interactive install google-chrome-stable
```

2024-09-19 14:34 UTC, adamperkowski commented on tabs/applications-setup/browser-setup.sh
> +            "$ESCALATION_TOOL" "$PACKAGER" in MozillaFirefox
`install` just to match other instances.

```suggestion
            "$ESCALATION_TOOL" "$PACKAGER" --non-interactive install MozillaFirefox
```

2024-09-19 14:34 UTC, adamperkowski commented on tabs/applications-setup/browser-setup.sh
> +            "$ESCALATION_TOOL" "$PACKAGER" install brave-browser
```suggestion
            "$ESCALATION_TOOL" "$PACKAGER" --non-interactive install brave-browser
```

2024-09-19 14:34 UTC, adamperkowski commented on tabs/applications-setup/browser-setup.sh
> +            "$ESCALATION_TOOL" "$PACKAGER" install chromium
```suggestion
            "$ESCALATION_TOOL" "$PACKAGER" --non-interactive install chromium
```

2024-09-19 16:49 UTC, adamperkowski requested changes
u forgot about `--noconfirm` :))

2024-09-19 16:49 UTC, adamperkowski commented on tabs/applications-setup/browser-setup.sh
> +            "$AUR_HELPER" -S brave-bin
```suggestion
            "$AUR_HELPER" -S --noconfirm brave-bin
```

2024-09-19 16:53 UTC, mashrukk commented
Now after seeing my PR you're making changes?

2024-09-19 16:56 UTC, ChrisTitusTech approved these changes

2024-09-19 16:56 UTC, merged

2024-09-19 16:59 UTC, guruswarupa commented
> Now after seeing my PR you're making changes? Funny

maintainers know who made the actual script. just work on yours. adam asked me to add lynx and i did and then squashed.

2024-09-19 17:01 UTC, mashrukk commented
It's all good. Now that my I PR got closed I'll add those additions to your script

2024-09-19 17:10 UTC, Angxddeep commented
![image](https://github.com/user-attachments/assets/ef1fc84b-a69b-42b4-bfa5-839eb229d9b0)
Well didn't work on fedora

2024-09-20 01:33 UTC, guruswarupa commented
> It's all good. Now that my PR got closed I'll add those additions to the script 

Yes that's what I wanted you to do thanks.