Add support for Portage, XBPS and Nix to setupbash.sh
ChrisTitusTech/linutil pull request #5
Opened 2024-06-10 17:24 UTC by AlbydST

Added support for Gentoo's Portage, Void's XBPS and Nix to setupbash.sh

2024-06-17 22:19 UTC, 4yman-el requested changes

2024-06-17 22:19 UTC, 4yman-el commented on src/commands/setupbash.sh
> +            ${PACKAGER} --noconfirm -S base-devel
```suggestion
            sudo ${PACKAGER} --noconfirm -S base-devel
```

We still need to use sudo

2024-06-17 22:19 UTC, 4yman-el commented on src/commands/setupbash.sh
> +        ${PACKAGER} install -yq ${DEPENDENCIES}
```suggestion
        sudo ${PACKAGER} install -yq ${DEPENDENCIES}
```

2024-06-18 17:47 UTC, AlbydST commented
I've made it so it supports both doas and sudo, and if neither is present it just runs the command with su -c

2024-06-28 23:54 UTC, ChrisTitusTech commented
Love the PR @AlbydST but I had to move this to the mybash project and change the code a bit. I put it in this commit e9382f6b861824ec0ed1d233113ebdd90ea17b9e

2024-06-28 23:54 UTC, closed without merging