feat: implement syntax highlighting for preview text
ChrisTitusTech/linutil pull request #568
Opened 2024-09-20 17:54 UTC by cartercanedy

![image](https://github.com/user-attachments/assets/81e359f8-3786-4c79-9864-2af94ae16beb)

Tree-sitter is a permissively licensed, open-source parser framework, well known for its integration with many popular editors. Luckily, they provide Rust bindings that are reasonably straightforward to use. This PR implements syntax highlighting for the source preview, making it much easier to read for people wanting to understand the code behind commands that they are running.

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Documentation update
- [x] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [x] UI/UX improvement

## Description
- Implement tree-sitter-based syntax highlighting

## Testing
Manual testing by perusing the previews of various commands

## Impact
This should make it much easier to understand the source while being presented in the preview

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-20 17:59 UTC, adamperkowski requested changes
Awesome.
Just remember to run `cargo fmt --all`.

2024-09-20 17:59 UTC, adamperkowski commented on tui/src/floating_text.rs
> +const SYNTAX_HIGHLIGHT_STYLES: [(&'static str, anstyle::Style); 8] = [
```suggestion
const SYNTAX_HIGHLIGHT_STYLES: [(&str, anstyle::Style); 8] = [
```

2024-09-20 17:59 UTC, adamperkowski commented on tui/src/floating_text.rs
> +fn get_highlighted_string<'a>(s: &'a str) -> Option<String> {
```suggestion
fn get_highlighted_string(s: &str) -> Option<String> {
```

2024-09-20 18:06 UTC, cartercanedy commented
> Just remember to run `cargo fmt --all`.

:))

2024-09-20 18:07 UTC, adamperkowski approved these changes

2024-09-20 18:09 UTC, adamperkowski commented
> and remove Cargo.lock

Don't remove it if you're adding deps.
If it doesn't conflict, then it's fine.

2024-09-20 18:10 UTC, cartercanedy commented
> > and remove Cargo.lock
> 
> Don't remove it if you're adding deps.
> If it doesn't conflict, then it's fine.

Did the Cargo.lock ci check get removed?

2024-09-20 18:13 UTC, adamperkowski commented
> Did the Cargo.lock ci check get removed?

It did because `Cargo.lock` exists for some reason.
Just don't push a deleated and re-cleanbuilded `Cargo.lock` if not neccessary.

2024-09-20 18:19 UTC, cartercanedy commented
>Just don't push a deleated and re-cleanbuilded `Cargo.lock` if not neccessary

makes sense

2024-09-20 21:40 UTC, Real-MullaC commented
Please take a look at the check.

2024-09-20 21:42 UTC, cartercanedy commented
> Please take a look at the check.

already on it

2024-09-20 22:59 UTC, lj3954 commented
This causes a reversion by removing functionality added in #202.

2024-09-20 23:12 UTC, cartercanedy commented
Yeah, that'll have to get sorted out. I'll have to take a deeper look into breaking up the lines on overflow, since it gets a little complicated with the unrendered ansi sequences in the raw strings

2024-09-20 23:24 UTC, cartercanedy commented
Just perusing the docs a bit, this shouldn't be too hard. I'd probably still use a flat map, just over the constructed lines rather than the raw text to preserve the styling and accurately determine the width of the actually rendered text

2024-09-20 23:25 UTC, cartercanedy commented
@lj3954 why are we looking at wrapping rather than side scrolling?

2024-09-21 14:18 UTC, ChrisTitusTech commented
> @lj3954 why are we looking at wrapping rather than side scrolling?

Oh I like side scrolling a lot better.

2024-09-21 17:41 UTC, cartercanedy commented
> Oh I like side scrolling a lot better. 

Me 2, but there's also the issue of altered semantics of a mid line break without also inserting a talking backslash, and even then I'm not sure that backslashes are a perfect solution

2024-09-21 21:35 UTC, cartercanedy commented
@ChrisTitusTech @lj3954 just implemented side scrolling to fix regression

2024-09-21 21:37 UTC, adamperkowski approved these changes
`v_scroll` and `h_scroll` could be renamed to `scroll_v` and `scroll_h` but it's not that big.

2024-09-21 22:14 UTC, lj3954 commented
get_lines should not take in an owned String, the split method is implemented for str instead. The lines() method also is more idiomatic than split("\n").

2024-09-21 22:45 UTC, cartercanedy commented
> get_lines should not take in an owned String, the split method is implemented for str instead. The lines() method also is more idiomatic than split("\n").

good catch, that was pretty sloppy

2024-09-22 15:52 UTC, ChrisTitusTech approved these changes

2024-09-22 15:56 UTC, merged