Add waydroid
ChrisTitusTech/linutil pull request #585
Opened 2024-09-21 13:36 UTC by nnyyxxxx

## Type of Change
- [x] New feature

## Description
adds waydroid, uses instructions from https://docs.waydro.id/usage/install-on-desktops for installation

## Testing
tested

## Impact

## Issues / other PRs related

- Resolves #580 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-21 14:00 UTC, adamperkowski approved these changes

2024-09-21 14:00 UTC, adamperkowski commented on core/tabs/applications-setup/waydroid-setup.sh
> +    else
```suggestion
        esac
    printf "%b\n" "${GREEN}Waydroid installation complete.${RC}"
    else
```

2024-09-21 14:01 UTC, nnyyxxxx commented on core/tabs/applications-setup/waydroid-setup.sh
> +    else
that would break the consistency with the other application scripts

2024-09-21 14:05 UTC, adamperkowski commented
We should consider this if system is using dkms
https://www.reddit.com/r/linux4noobs/comments/rdpsz4/driver_problem_while_attempting_to_install/

2024-09-21 14:09 UTC, jeevithakannan2 requested changes

2024-09-21 14:09 UTC, jeevithakannan2 commented on core/tabs/applications-setup/waydroid-setup.sh
> +                "$AUR_HELPER" -S --needed --noconfirm waydroid # dont run any aur helper as root
```suggestion
                "$AUR_HELPER" -S --needed --noconfirm waydroid
```

2024-09-21 14:09 UTC, jeevithakannan2 commented on core/tabs/applications-setup/waydroid-setup.sh
> +                "$AUR_HELPER" -S --needed --noconfirm waydroid # dont run any aur helper as root
I don't this that comment is necessary there

2024-09-21 14:10 UTC, nnyyxxxx commented on core/tabs/applications-setup/waydroid-setup.sh
> +                "$AUR_HELPER" -S --needed --noconfirm waydroid # dont run any aur helper as root
i usually include context for the maintainer, but i see your point

2024-09-21 14:12 UTC, jeevithakannan2 commented
Waydroid only works on wayland so add pre-condition in toml

2024-09-21 14:13 UTC, jeevithakannan2 commented
Also it won't work with nvidia GPU it would be better if we notified the user about that and make a work around to use software rendering if nvidia GPU is used

2024-09-21 14:16 UTC, nnyyxxxx commented
> Waydroid only works on wayland so add pre-condition in toml

sure:)

2024-09-21 14:17 UTC, nnyyxxxx commented
needs 2 issues to be worked out before merge

2024-09-21 14:31 UTC, adamperkowski requested changes
@nnyyxxxx Something like this. Feel free to restructure my changes.

2024-09-21 14:31 UTC, adamperkowski commented on core/tabs/applications-setup/waydroid-setup.sh
> +                ;;
```suggestion
            pacman)
                "$AUR_HELPER" -S --needed --noconfirm waydroid
                if command_exists dkms; then
                    "$AUR_HELPER" -S --needed --noconfirm binder_linux-dkms
                    "$ESCALATION_TOOL" modprobe binder-linux device=binder,hwbinder,vndbinder
                fi
                ;;
            apt-get|nala)
                curl https://repo.waydro.id | "$ESCALATION_TOOL" sh
                "$ESCALATION_TOOL" "$PACKAGER" install -y waydroid
                if command_exists dkms; then
                    "$ESCALATION_TOOL" "$PACKAGER" install -y git
                    git clone https://github.com/choff/anbox-modules.git && cd anbox-modules
                    "$ESCALATION_TOOL" cp anbox.conf /etc/modules-load.d/
                    "$ESCALATION_TOOL" cp 99-anbox.rules /lib/udev/rules.d/
                    "$ESCALATION_TOOL" cp -rT ashmem /usr/src/anbox-ashmem-1
                    "$ESCALATION_TOOL" cp -rT binder /usr/src/anbox-binder-1
                    "$ESCALATION_TOOL" dkms install anbox-ashmem/1
                    "$ESCALATION_TOOL" dkms install anbox-binder/1
                fi
                ;;
            dnf)
                "$ESCALATION_TOOL" "$PACKAGER" install -y waydroid
                if command_exists dkms; then
                    "$ESCALATION_TOOL" "$PACKAGER" install -y git
                    git clone https://github.com/choff/anbox-modules.git && cd anbox-modules
                    "$ESCALATION_TOOL" cp anbox.conf /etc/modules-load.d/
                    "$ESCALATION_TOOL" cp 99-anbox.rules /lib/udev/rules.d/
                    "$ESCALATION_TOOL" cp -rT ashmem /usr/src/anbox-ashmem-1
                    "$ESCALATION_TOOL" cp -rT binder /usr/src/anbox-binder-1
                    "$ESCALATION_TOOL" dkms install anbox-ashmem/1
                    "$ESCALATION_TOOL" dkms install anbox-binder/1
                fi
                ;;
```

2024-09-21 14:32 UTC, adamperkowski commented on core/tabs/applications-setup/tab_data.toml
> +values = [ "wayland-info", "weston" ]
Do something like this but with `WAYLAND_DISPLAY` instead:
https://github.com/ChrisTitusTech/linutil/blob/995a51a66548b1f913bafddbe5241d2ebdf778ca/core/tabs/utils/tab_data.toml#L7-L10

2024-09-21 14:34 UTC, nnyyxxxx commented on core/tabs/applications-setup/tab_data.toml
> +values = [ "wayland-info", "weston" ]
tahnks

2024-09-21 14:42 UTC, adamperkowski approved these changes

2024-09-21 14:53 UTC, nnyyxxxx commented
ready to be merged

2024-09-21 14:54 UTC, nnyyxxxx commented on core/tabs/applications-setup/waydroid-setup.sh
> +                if command_exists dkms; then
these if statements are a bit messy, can be cleaned up in the future.

2024-09-21 15:01 UTC, adamperkowski approved these changes

2024-09-21 15:20 UTC, jeevithakannan2 commented
@nnyyxxxx waydroid won't work with nvidia GPU it would be better if we notified the user about that and make a work around to use software rendering if nvidia GPU is used

2024-09-21 15:21 UTC, nnyyxxxx commented
> @nnyyxxxx waydroid won't work with nvidia GPU it would be better if we notified the user about that and make a work around to use software rendering if nvidia GPU is used

ill look into it

2024-09-21 15:22 UTC, idea90 commented
adds for arch linux

2024-09-22 16:03 UTC, ChrisTitusTech approved these changes

2024-09-22 16:03 UTC, merged