Add colors to d2r-loot-filters & use command_exists instead of command -v
ChrisTitusTech/linutil pull request #591
Opened 2024-09-21 18:04 UTC by nnyyxxxx

## Type of Change
- [x] Refactoring

## Description
quotes vars to prevent globbing, adds colors, uses command_exists function defined in common-script

## Testing
needs testing, though it should work fine. can't test because i don't own the game, but the first 18 lines work:

![image](https://github.com/user-attachments/assets/9a8cea63-2139-451d-be51-16d92dff7e87)

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-21 20:34 UTC, lj3954 requested changes

2024-09-21 20:34 UTC, lj3954 commented on core/tabs/gaming/diablo-ii/d2r-loot-filters.sh
> +    if ! command_exists "$cmd" >/dev/null 2>&1; then
```suggestion
    if ! command_exists "$cmd"; then
```

The command_exists function pipes output to /dev/null, this is redundant.

2024-09-21 20:53 UTC, lj3954 approved these changes

2024-09-22 01:09 UTC, adamperkowski approved these changes

2024-09-22 16:08 UTC, merged