added adb setup + uad setup
ChrisTitusTech/linutil pull request #592
Opened 2024-09-21 18:30 UTC by guruswarupa

## Type of Change
- [x] New feature

## Description
Installs Android tools (adb) and installs Universal Android debloater Next Gen.
- run uad command to execute  Universal Android debloater
## Checklist
- [ ] My code adheres to the coding and style guidelines of the project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no errors/warnings/merge conflicts.

2024-09-21 18:57 UTC, adamperkowski requested changes

2024-09-21 18:57 UTC, adamperkowski commented on core/tabs/applications-setup/android-debloat.sh
> +        printf "%b\n" "${YELLOW}Installing ADB..${RC}."
```suggestion
        printf "%b\n" "${YELLOW}Installing ADB...${RC}."
```

2024-09-21 18:57 UTC, adamperkowski commented on core/tabs/applications-setup/android-debloat.sh
> +                "$ESCALATION_TOOL" "$PACKAGER" install android-tools
```suggestion
                "$ESCALATION_TOOL" "$PACKAGER" install -y android-sdk-platform-tools
                ;;
            zypper)
                "$ESCALATION_TOOL" "$PACKAGER" --non-interactive install android-tools
                ;;
            pacman)
                "$ESCALATION_TOOL" "$PACKAGER" -S --noconfirm android-tools
                ;;
            yum)
                "$ESCALATION_TOOL" "$PACKAGER" install -y android-tools
```

2024-09-21 18:57 UTC, adamperkowski commented on core/tabs/applications-setup/android-debloat.sh
> +                printf "%b\n" "${RED}The script does not support your Distro. Install manually..${RC}"
```suggestion
                printf "%b\n" "${RED}Unsupported package manager: "$PACKAGER"${RC}"
```

2024-09-21 18:57 UTC, adamperkowski commented on core/tabs/applications-setup/android-debloat.sh
> +        printf "%b\n" "${YELLOW}Installing Universal Android Debloater..${RC}."
```suggestion
        printf "%b\n" "${YELLOW}Installing Universal Android Debloater...${RC}."
```

2024-09-21 18:57 UTC, adamperkowski commented on core/tabs/applications-setup/android-debloat.sh
> +        printf "%b\n" "${GREEN}Universal Android Debloater is already installed. Run 'uad' command to execute...${RC}"
```suggestion
        printf "%b\n" "${GREEN}Universal Android Debloater is already installed. Run 'uad' command to execute.${RC}"
```

2024-09-21 20:05 UTC, nnyyxxxx commented on core/tabs/applications-setup/android-debloat.sh
> +                printf "%b\n" "${RED}The script does not support your Distro. Install manually..${RC}"
```suggestion
                printf "%b\n" "${RED}Unsupported package manager: "$PACKAGER"${RC}"
                exit 1
```

2024-09-21 21:02 UTC, adamperkowski commented on core/tabs/applications-setup/android-debloat.sh
> +                printf "%b\n" "${RED}The script does not support your Distro. Install manually..${RC}"
https://github.com/ChrisTitusTech/linutil/pull/592#discussion_r1769638445

2024-09-21 21:03 UTC, nnyyxxxx commented on core/tabs/applications-setup/android-debloat.sh
> +                printf "%b\n" "${RED}The script does not support your Distro. Install manually..${RC}"
u forgot exit 1 nub

2024-09-21 21:24 UTC, adamperkowski commented on core/tabs/applications-setup/android-debloat.sh
> +                printf "%b\n" "${RED}The script does not support your Distro. Install manually..${RC}"
Oh yes. Sorry

2024-09-22 12:43 UTC, adamperkowski approved these changes

2024-09-22 12:46 UTC, nnyyxxxx commented on core/tabs/applications-setup/android-debloat.sh
> +                ;;
remove yum

2024-09-22 12:48 UTC, adamperkowski commented on core/tabs/applications-setup/android-debloat.sh
> +                ;;
replace with dnf

2024-09-22 13:22 UTC, guruswarupa commented on core/tabs/applications-setup/android-debloat.sh
> +                ;;
In the docs it's given to use yum.

2024-09-22 13:22 UTC, guruswarupa commented on core/tabs/applications-setup/android-debloat.sh
> +                ;;
> replace with dnf

You sure dnf has that package?

2024-09-22 13:30 UTC, adamperkowski commented on core/tabs/applications-setup/android-debloat.sh
> +                ;;
> You sure dnf has that package?

https://packages.fedoraproject.org/pkgs/android-tools/android-tools/index.html
From the wiki, dnf uses packages.fedoraproject.org as a resource.

2024-09-22 13:36 UTC, adamperkowski approved these changes

2024-09-22 16:09 UTC, ChrisTitusTech approved these changes

2024-09-22 16:09 UTC, merged