increase synergy between scripts
ChrisTitusTech/linutil pull request #596
Opened 2024-09-21 20:03 UTC by nnyyxxxx

## Type of Change
- [x] Refactoring

## Description
increases synergy between scripts

## Testing
tested

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-21 21:22 UTC, adamperkowski requested changes

2024-09-21 21:22 UTC, adamperkowski commented on core/tabs/applications-setup/Developer-tools/sublime-setup.sh
> +        esac
```suggestion
            esac
```

2024-09-21 21:22 UTC, adamperkowski commented on core/tabs/applications-setup/browser-setup.sh
> +    printf "%b"  "Enter your choices (e.g., 1 3 5): "
```suggestion
    printf "%b"  "Enter your choices (e.g. 1 3 5): "
```

2024-09-21 21:22 UTC, adamperkowski commented on core/tabs/utils/auto-login.sh
> +    printf "%b" "Enter your choice [1-10]: "
```suggestion
    printf "%b" "Enter your choice (1-10): "
```

2024-09-21 21:22 UTC, adamperkowski commented on core/tabs/utils/auto-login.sh
> +    printf "%b" "Enter your choice [1-2]: "
```suggestion
    printf "%b" "Enter your choice (1-2): "
```

2024-09-21 21:22 UTC, adamperkowski commented on core/tabs/utils/auto-login.sh
> +        printf "%b" "Enter your choice [1-4]: "
```suggestion
        printf "%b" "Enter your choice (1-4): "
```

2024-09-21 21:22 UTC, adamperkowski commented on core/tabs/utils/auto-login.sh
> +        printf "%b" "Enter your choice [1-4]: "
```suggestion
        printf "%b" "Enter your choice (1-4): "
```

2024-09-21 21:22 UTC, adamperkowski commented on core/tabs/utils/create-bootable-usb.sh
> +    printf "%b" "Enter the USB device (e.g., /dev/sdX): "
```suggestion
    printf "%b" "Enter the USB device (e.g. /dev/sdX): "
```

2024-09-21 21:22 UTC, adamperkowski commented on core/tabs/utils/encrypt_decrypt_tool.sh
> +            printf "%b\n" "${RED}Unsupported package manager: "$PACKAGER"${RC}"
```suggestion
            printf "%b\n" "${RED}Unsupported package manager: ""$PACKAGER""${RC}"
```

2024-09-21 21:22 UTC, adamperkowski commented on core/tabs/utils/numlock.sh
>      "$ESCALATION_TOOL" systemctl enable numlock.service --quiet
y is not the default here. Shouldn't be `Y`.

```suggestion
  printf "%b\n" "Do you want to enable Numlock on boot? (y/N): "
  read -r confirm
  if [ "$confirm" = "y" ] || [ "$confirm" = "Y" ]; then
    "$ESCALATION_TOOL" systemctl enable numlock.service --quiet
```

2024-09-21 21:22 UTC, adamperkowski commented on core/tabs/utils/ollama.sh
> +    printf "%b" "Please select a model to run: "
```suggestion
    printf "%b" "Select a model to run: "
```

2024-09-21 21:22 UTC, adamperkowski commented on core/tabs/utils/service-control.sh
>      if [ "$START_ENABLE" = "y" ]; then
Same here.

```suggestion
    printf "%b" "Do you want to start and enable the service now? (y/N): "
    read -r START_ENABLE

    if [ "$START_ENABLE" = "y" ] || [ "$START_ENABLE" = "Y" ]; then
```

2024-09-21 21:22 UTC, adamperkowski commented on core/tabs/utils/timeshift.sh
>      if [ "$SKIP_GRUB" = "yes" ]; then
```suggestion
    printf "%b" "${CYAN}Do you want to skip GRUB reinstall? (y/N): ${RC}"
    read -r SKIP_GRUB

    if [ "$SKIP_GRUB" = "y" ] || [ "$SKIP_GRUB" = "Y" ]; then
```

2024-09-21 21:22 UTC, adamperkowski commented on core/tabs/utils/timeshift.sh
>      if [ "$CONFIRMATION" = "yes" ]; then
```suggestion
    printf "%b" "${CYAN}Are you sure? (y/N): ${RC}"
    read -r CONFIRMATION

    if [ "$CONFIRMATION" = "y" ] || [ "$CONFIRMATION" = "Y" ]; then
```

2024-09-21 21:24 UTC, adamperkowski commented
Looked through every single changed line. Apart from what I've requested, great work. Thanks.

2024-09-21 21:26 UTC, nnyyxxxx commented on core/tabs/utils/numlock.sh
>      "$ESCALATION_TOOL" systemctl enable numlock.service --quiet
remove the \n aswell

2024-09-21 21:28 UTC, adamperkowski commented on core/tabs/utils/numlock.sh
>      "$ESCALATION_TOOL" systemctl enable numlock.service --quiet
Done

2024-09-21 21:35 UTC, nnyyxxxx commented
ready for merge

2024-09-21 21:37 UTC, adamperkowski approved these changes

2024-09-21 21:37 UTC, adamperkowski commented
Every single line approved.

2024-09-21 23:07 UTC, ChrisTitusTech commented on core/tabs/system-setup/global-theme.sh
> +            printf "%b\n" "${RED}Unsupported package manager: "$PACKAGER"${RC}"
Missing Double quote for PACKAGER

2024-09-21 23:14 UTC, nnyyxxxx commented on core/tabs/system-setup/global-theme.sh
> +            printf "%b\n" "${RED}Unsupported package manager: "$PACKAGER"${RC}"
thanks for spotting that

2024-09-21 23:15 UTC, nnyyxxxx commented on core/tabs/system-setup/global-theme.sh
> +            printf "%b\n" "${RED}Unsupported package manager: "$PACKAGER"${RC}"
fixed

2024-09-22 16:01 UTC, ChrisTitusTech approved these changes

2024-09-22 16:01 UTC, merged