Add package installation instructions to the docs
ChrisTitusTech/linutil pull request #605
Opened 2024-09-21 23:32 UTC by adamperkowski

## Type of Change
- [x] Documentation update

## Markdown preview
![image](https://github.com/user-attachments/assets/678d0cc9-6419-4720-a04a-a19f01b66536)
---
![image](https://github.com/user-attachments/assets/4647d14d-c359-4eda-9625-9e7e1a5a41d9)

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-21 23:34 UTC, nnyyxxxx requested changes

2024-09-21 23:34 UTC, nnyyxxxx commented on docs/index.md
> +If you use [yay](https://github.com/Jguer/yay), [paru](https://github.com/Morganamilo/paru) or any other [AUR Helper](https://wiki.archlinux.org/title/AUR_helpers), it's even simplier:
```suggestion
If you use [yay](https://github.com/Jguer/yay), [paru](https://github.com/Morganamilo/paru) or any other [AUR Helper](https://wiki.archlinux.org/title/AUR_helpers), it's even simpler:
```

2024-09-21 23:34 UTC, nnyyxxxx commented on docs/index.md
> +paru -S linutil
```suggestion
paru -S linutil
yay -s linutil
```

2024-09-21 23:34 UTC, nnyyxxxx commented on docs/index.md
> +Replace `paru` with your preferred helper and `linutil` with your preferred package.
```suggestion
```

2024-09-21 23:37 UTC, nnyyxxxx requested changes

2024-09-21 23:37 UTC, nnyyxxxx commented on README.md
> +LinUtil is also available as a package in various repositories:
```suggestion
Linutil is also available as a package in various repositories:
```

2024-09-21 23:37 UTC, nnyyxxxx commented on README.md
> +paru -S linutil
```suggestion
paru -S linutil
yay -S linutil
```

2024-09-21 23:37 UTC, nnyyxxxx commented on README.md
> +Replace `paru` with your preferred helper and `linutil` with your preferred package.
```suggestion
```

2024-09-21 23:49 UTC, nnyyxxxx approved these changes
If we're going to put html in the readme, might as well open a separate PR to add more of it for the header at the top.

2024-09-22 16:38 UTC, ChrisTitusTech approved these changes

2024-09-22 16:38 UTC, merged