Fix: Selected-cmd bug
ChrisTitusTech/linutil pull request #638
Opened 2024-09-23 10:36 UTC by jeevithakannan2

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
- Fixed a bug where floating window appears even though no command is selected.

![command](https://github.com/user-attachments/assets/adee98be-25b2-40cc-bb5d-86217707122b)

## Testing
- Working as expected.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-23 12:12 UTC, adamperkowski approved these changes

2024-09-23 14:30 UTC, lj3954 requested changes

2024-09-23 14:30 UTC, lj3954 commented on tui/src/state.rs
> +        }
```suggestion
            self.selection.selected().is_some() && !(self.selected_item_is_up_dir() || self.selected_item_is_dir())
```

2024-09-23 14:59 UTC, lj3954 requested changes

2024-09-23 14:59 UTC, lj3954 commented on tui/src/state.rs
> +            self.selection.selected().is_some() && !(self.selected_item_is_up_dir() || self.selected_item_is_dir())
```suggestion
        self.selection.selected().is_some() && !(self.selected_item_is_up_dir() || self.selected_item_is_dir())
```

2024-09-23 15:05 UTC, lj3954 requested changes

2024-09-23 15:05 UTC, lj3954 commented on tui/src/state.rs
> +        self.selection.selected().is_some() && !(self.selected_item_is_up_dir() || self.selected_item_is_dir())
```suggestion
        self.selection.selected().is_some()
            && !(self.selected_item_is_up_dir() || self.selected_item_is_dir())
```

2024-09-23 15:05 UTC, lj3954 commented on tui/src/state.rs
> +        self.selection.selected().is_some() && !(self.selected_item_is_up_dir() || self.selected_item_is_dir())
That'll resolve rustfmt issues.

2024-09-30 20:21 UTC, ChrisTitusTech approved these changes

2024-09-30 20:23 UTC, merged