refactor meld
ChrisTitusTech/linutil pull request #644
Opened 2024-09-23 13:18 UTC by nnyyxxxx

## Type of Change
- [x] Refactoring

## Description
refactors meld

## Testing
tested

2024-09-29 23:58 UTC, adamperkowski requested changes

2024-09-29 23:58 UTC, adamperkowski commented on core/tabs/applications-setup/Developer-tools/meld-setup.sh
> +        esac
As far as I know, `meld` is available in some repos (`apt` for example) and we don't really want to rely on flatpak that much.
Also, `FI` (for flatpak installation) should be added to `tab_data.toml`.

2024-09-30 12:52 UTC, adamperkowski approved these changes

2024-09-30 12:52 UTC, adamperkowski commented on core/tabs/applications-setup/tab_data.toml
> +task_list = "FI"
```suggestion
task_list = "I FI"
```

2024-09-30 20:47 UTC, ChrisTitusTech approved these changes

2024-09-30 20:47 UTC, merged