Emit all shellcheck errors using github action workflow toolkit annotations and check for tab indentation
ChrisTitusTech/linutil pull request #658
Opened 2024-09-23 18:04 UTC by cartercanedy

Tabs are problematic when rendering previews of shell scripts, as it results in a disparity between the position of expected rendered characters and where they may actually be rendered on the screen, and having mixed space/tab indentation in the same file is generally problematic as well.

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [x] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
- Emit all errors found within the changed files using gh actions toolkit annotations, before, the workflow would fail on the first shellcheck invocation that had an error emission
- Add a tab indentation check to enforce consistency in code style
- removed all current tab indentations that I've found in shell scripts

## Testing
Verified using workflow runs within my own repository

## Impact
Helps provide complete error information from both shellcheck and tab indentation detection

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-23 18:23 UTC, nnyyxxxx requested changes

2024-09-23 18:23 UTC, nnyyxxxx commented on core/tabs/applications-setup/browser-setup.sh
> +            exit 1
these formatting changes are going to conflict with #648

2024-09-23 18:23 UTC, nnyyxxxx commented on core/tabs/applications-setup/Developer-tools/sublime-setup.sh
> +    if ! command_exists sublime; then
these formatting changes are going to conflict with #648

2024-09-23 18:24 UTC, nnyyxxxx commented
also the browser-setup and sublime-setup formatting changes are already implemented in #648 @cartercanedy

2024-09-23 18:28 UTC, cartercanedy commented on core/tabs/applications-setup/Developer-tools/sublime-setup.sh
> +    if ! command_exists sublime; then
this should be easy to resolve with a simple rebase, not worried about it

2024-09-23 18:29 UTC, cartercanedy commented
> also the browser-setup formatting changes are already implemented in #648 @cartercanedy

I need those implemented here to pass the new shellcheck ci workflow. You should be able to rebase your changes on top of mine

2024-09-28 19:12 UTC, cartercanedy commented
@ChrisTitusTech I'd recommend committing this before pulling in any shell scripts to get better shellcheck errors and catch formatting issues

2024-10-04 09:25 UTC, nnyyxxxx approved these changes

2024-10-08 20:34 UTC, ChrisTitusTech approved these changes

2024-10-08 20:34 UTC, merged