Fix AutoLogin printf & > issues
ChrisTitusTech/linutil pull request #662
Opened 2024-09-23 22:25 UTC by adamperkowski

## Type of Change
- [x] Bug fix
- [x] Refactoring
- [x] Hotfix

## Description
A LOT of bugs here. Someone didn't test this.

## Issues / other PRs related

- Resolves #654

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-23 22:33 UTC, nnyyxxxx requested changes

2024-09-23 22:33 UTC, nnyyxxxx commented on core/tabs/utils/auto-login.sh
> +    printf "%b\n" 'autologin-user-timeout=0' | "$ESCALATION_TOOL" tee -a /etc/lightdm/lightdm.conf.d/50-autologin.conf
50-autologin.conf is wrong

2024-09-23 22:33 UTC, nnyyxxxx commented on core/tabs/utils/auto-login.sh
> +    printf "%b\n" 'AutomaticLoginEnable = true' | "$ESCALATION_TOOL" tee -a /etc/gdm/custom.conf
custom.conf is also wrong

2024-09-23 22:33 UTC, nnyyxxxx commented
@adamperkowski you'll have to go through and find the correct paths for each one, some of these are wrong

2024-09-23 22:34 UTC, nnyyxxxx commented on core/tabs/utils/auto-login.sh
> +    printf "%b\n" 'autologin-user-timeout=0' | "$ESCALATION_TOOL" tee -a /etc/lightdm/lightdm.conf.d/50-autologin.conf
lightdm.conf.d is not even a subdir

2024-09-23 22:37 UTC, adamperkowski commented
@nnyyxxxx Who did this, I'd like to have a friendly talk with them...

2024-09-23 22:37 UTC, nnyyxxxx commented
> @nnyyxxxx Who did this? I'd like to have a friendly talk with them...

guru

2024-09-23 22:38 UTC, adamperkowski commented
@guruswarupa ...

2024-09-23 22:50 UTC, adamperkowski commented on core/tabs/utils/auto-login.sh
> +    printf "%b\n" 'AutomaticLoginEnable = true' | "$ESCALATION_TOOL" tee -a /etc/gdm/custom.conf
This actually is right according to the [Archwiki](https://wiki.archlinux.org/title/GDM#Automatic_login).

2024-09-23 22:55 UTC, adamperkowski commented
https://wiki.archlinux.org/title/LightDM#Enabling_autologin

2024-09-23 22:59 UTC, nnyyxxxx approved these changes

2024-09-23 23:31 UTC, cartercanedy requested changes

2024-09-23 23:31 UTC, cartercanedy commented on core/tabs/utils/auto-login.sh
> +    "$ESCALATION_TOOL" sed -i '/^autologin-/d' /etc/lightdm/lightdm.conf
Change to `"$ESCALATION_TOOL" sed -i''...` for compat with bsd sed

2024-09-23 23:41 UTC, cartercanedy commented
I'm pretty sure that the empty `-i` arg to I needs to be joined like `sed -i'' ...`, just based off of my own usage and the man pages

2024-09-23 23:48 UTC, nnyyxxxx commented
> I was wrong
> 
> The bsd man pages are so much better than the ones for gnutils

wrong

2024-09-23 23:48 UTC, nnyyxxxx commented
thats only for bsd

2024-09-23 23:53 UTC, cartercanedy commented
> thats only for bsd

? 

Which form are you talking about

2024-09-23 23:57 UTC, nnyyxxxx commented
> > thats only for bsd
> 
> ?
> 
> Which form are you talking about

the empty arg u mentioned in your edited message, only works for linux, bsd on the otherhand it would not work on

2024-09-23 23:59 UTC, cartercanedy commented
> > > thats only for bsd
> > 
> > ?
> > 
> > Which form are you talking about
> 
> the empty arg u mentioned in your edited message, only works for linux, bsd on the otherhand it would not work on

`sed -i'.old' 's/foo/bar/' test.txt` produces a file named foo.txt.old

2024-09-24 00:00 UTC, nnyyxxxx commented
> sed -i'.old' 's/foo/bar/' test.txt

that **will** work on bsd, but if u take the argument away it **wont**

2024-09-24 00:01 UTC, nnyyxxxx commented
if there is no argument on linux it will work though, so you were only half right.

2024-09-24 00:01 UTC, cartercanedy commented
> > sed -i'.old' 's/foo/bar/' test.txt
> 
> that **will** work on bsd, but if u take the argument away it **wont**

Correct, that's why I suggested the change

2024-09-24 00:08 UTC, cartercanedy commented
I want saying that I was wrong to suggest the change, just that the empty arg needed to be concatenated to the flag @nnyyxxxx

2024-09-24 00:10 UTC, nnyyxxxx commented
> I wasn't saying that I was wrong to suggest the change, just that the empty arg needed to be concatenated to the flag @nnyyxxxx

i understand i was only saying that you were partially wrong

2024-09-24 00:12 UTC, cartercanedy commented
Ok, glad we agree...
Right?

2024-09-24 00:20 UTC, cartercanedy approved these changes
:)

2024-09-24 00:31 UTC, adamperkowski commented
Co-authors for you :)

2024-09-24 12:27 UTC, guruswarupa commented
> @guruswarupa ...

It seemed to work when those lines which you changed were echo. Later while changing it to printf, it broke. I did test on my system before adding it.

2024-09-24 16:26 UTC, cartercanedy commented
> It seemed to work when those lines which you changed were echo. Later while changing it to printf, it broke. I did test on my system before adding it.

On its face that's incorrect. The single string argument being passed to sudo *will* fail because it will assume that it's looking for an executable named `echo '...' > ...`, which fails regardless of whether you substitute echo for printf. You'd either have to run `sudo bash -c "..."` or do what @adamperkowski did and utilize `sudo tee` to get the permissions right

2024-09-24 22:23 UTC, nnyyxxxx commented
> > It seemed to work when those lines which you changed were echo. Later while changing it to printf, it broke. I did test on my system before adding it.
> 
> On its face that's incorrect. The single string argument being passed to sudo _will_ fail because it will assume that it's looking for an executable named `"echo '...' > ..."`, which fails regardless of whether you substitute echo for printf. You'd either have to run `sudo bash -c "..."` or do what @adamperkowski did and utilize `sudo tee` to get the permissions right

i'd recommend against using sub shells

2024-09-28 18:55 UTC, ChrisTitusTech approved these changes

2024-09-28 18:56 UTC, merged