updating Gaming For Fedora 41
ChrisTitusTech/linutil pull request #681
Opened 2024-09-27 07:09 UTC by Nightmare1984

## Type of Change
- [ ] New feature
- [x ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [x ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
Red Hat Already Has OpenH264 Installed When You Update To Fedora 41

## Testing
Since I Do Not Use Fedora I Tested it In Box buddy Virtual Fedora Terminal

## Impact

## Issues / other PRs related
https://github.com/ChrisTitusTech/linutil/issues/679
- Resolves #
Fedora 41 Update

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-27 13:28 UTC, adamperkowski commented
Resolves #679

2024-09-27 13:32 UTC, adamperkowski requested changes
These scripts are not explicitly made for Fedora **41**. What about older versions or other distros?

2024-09-27 14:48 UTC, adamperkowski commented on core/tabs/system-setup/gaming-setup.sh
> +                echo "Skipping Fedora 41 Setup To Older setup"
```suggestion
                printf "%b\n" "${CYAN}Fedora < 41 detected. Installing rpmfusion repos."
```

2024-09-27 14:48 UTC, adamperkowski approved these changes

2024-09-27 19:22 UTC, nnyyxxxx commented on core/tabs/system-setup/gaming-setup.sh
> +                "$ESCALATION_TOOL" "$PACKAGER" install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfu
```suggestion
                "$ESCALATION_TOOL" "$PACKAGER" install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-"$(rpm -E %fedora)".noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-"$(rpm -E %fedora)".noarch.rpm -y
```

2024-09-27 19:37 UTC, nnyyxxxx commented
put

- resolves #679

in the description

2024-09-28 08:02 UTC, nnyyxxxx approved these changes

2024-09-28 18:59 UTC, ChrisTitusTech approved these changes

2024-09-28 18:59 UTC, merged