feat: Linux Neptune (Valve's kernel for SteamDeck) installation
ChrisTitusTech/linutil pull request #683
Opened 2024-09-27 14:45 UTC by adamperkowski

## Type of Change
- [x] New feature
- [x] Bug fix

## Description
Added a script that installs Linux Neptune on Vanilla Arch.

## Testing
Could not test on the deck so I am unable to confirm if Wi-Fi works properly, but the script itself works.

## Issues / other PRs related
- Resolves #269

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-27 17:14 UTC, cartercanedy commented
I think we should implement a confirmation prompt to prevent people from fat fingering on these kinds of significant changes

2024-09-27 17:15 UTC, cartercanedy commented
I've done it before, and I've seen Chris wipe out his nvim cfg on stream, that would be big

2024-09-27 17:18 UTC, adamperkowski commented
@cartercanedy On one hand, I agree, on the other one, Chris says he wants MINIMAL (none) user interaction in shell scripts. 
And we have **Important Actions** with **kernel modifications** + the script preview so I don't know about this to be honest.

2024-09-27 17:19 UTC, cartercanedy commented
> Chris says he wants MINIMAL (none) user interaction in shell scripts

I was thinking about implementing this via a tui integration

2024-09-27 17:22 UTC, adamperkowski commented
> I was thinking about implementing this via a tui integration

That might actually be a good idea for tui to automatically detect important actions (we could move these from strings to custom values in toml) and display a popup with confirmation. 
Open an issue, please.

2024-09-27 19:30 UTC, nnyyxxxx requested changes

2024-09-27 19:30 UTC, nnyyxxxx commented on core/tabs/system-setup/arch/linux-neptune.sh
> +	    echo 'UPDATEDEFAULT=yes' | sudo tee -a /etc/default/grub
```suggestion
	    echo 'UPDATEDEFAULT=yes' | "$ESCALATION_TOOL" tee -a /etc/default/grub
```

2024-09-27 19:30 UTC, nnyyxxxx commented on core/tabs/system-setup/arch/linux-neptune.sh
> +   	    sudo sed -i 's/^UPDATEDEFAULT=.*/UPDATEDEFAULT=yes/' /etc/default/grub
```suggestion
   	    "$ESCALATION_TOOL" sed -i 's/^UPDATEDEFAULT=.*/UPDATEDEFAULT=yes/' /etc/default/grub
```

2024-09-27 19:30 UTC, nnyyxxxx commented on core/tabs/system-setup/arch/linux-neptune.sh
> +#! /bin/sh -e
```suggestion
#!/bin/sh -e
```
keep the consistency with other scripts

2024-09-27 19:31 UTC, nnyyxxxx commented on core/tabs/system-setup/arch/linux-neptune.sh
> +copyFirmwareFiles
some of the indentation throughout the script looks f'ed up locally, might want to reformat all of this

2024-09-27 19:45 UTC, nnyyxxxx approved these changes

2024-09-27 19:47 UTC, nnyyxxxx commented on core/tabs/system-setup/arch/linux-neptune.sh
> +        else
fix indentation on this ``else``

2024-09-27 19:52 UTC, adamperkowski commented
I gotta fix my neovim with those whitespaces. Don't know what happened.

2024-09-30 21:24 UTC, adamperkowski commented
@ChrisTitusTech read this: #269

2024-09-30 21:29 UTC, ChrisTitusTech requested changes
Add precondition that isolates this to only show on steamdeck

2024-09-30 22:27 UTC, lj3954 requested changes

2024-09-30 22:27 UTC, lj3954 commented on core/tabs/system-setup/tab_data.toml
> +
```suggestion

[[data.preconditions]]
matches = false
data = { file = "/sys/devices/virtual/dmi/id/board_vendor" }
values = ["Valve", "Jupiter"]

```
source: https://www.reddit.com/r/SteamDeck/comments/telfda/how_to_detect_if_software_is_running_on_steamdeck/

2024-09-30 22:37 UTC, adamperkowski commented on core/tabs/system-setup/tab_data.toml
> +
Okayy. Thank you. Will check with the issue's author to see if this works.

2024-10-03 12:54 UTC, adamperkowski commented
Drafting this because there's a bug in `tab_data`

2024-11-06 22:20 UTC, merged