Draft: Feat: confirmation prompts
ChrisTitusTech/linutil pull request #687
Opened 2024-09-27 21:19 UTC by cartercanedy

# Add confirmation prompt to prevent accidental command execution

## note: this PR anticipates #668 will get merged, I will have to rebase this once it gets merged to remove the extra commits

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [x] UI/UX improvement

## Description
Having an accidental keypress result in a significant environment change sucks. Adding a prompt to confirm the execution of a command makes it less likely that a user will have a destructive command accidentally execute and have to decipher the command source to revert the changes (if they even are revertible).

## Testing
locally, tested aborting and confirming command selections

## Impact
should prevent accidental neovim config deletions, at least :)

## Issues / other PRs related
- Resolves #686 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-28 17:32 UTC, lj3954 commented
Confirmation prompt doesn't need its own variant, we can use the generic float variant with slight refactoring. https://github.com/lj3954/linutil/commit/0a17f4272397964719f73d1cba2a06eac00c63e0

2024-09-28 18:20 UTC, cartercanedy commented
I think the focus specialization is fine there, it prevents us from needing to polute the `FloatContent` interface for other implementors

2024-09-28 19:42 UTC, lj3954 commented
> I think the focus specialization is fine there, it prevents us from needing to polute the `FloatContent` interface for other implementors

I don't think it's "polluting" the trait. All that needs to be changed is to return an enum rather than a boolean. It's probably more clear that way, since the variants can explicitly state what action is occuring ('None', 'Close', etc) rather than having to look at comments in the trait to explain what each boolean value corresponds to.

2024-09-28 19:46 UTC, adamperkowski approved these changes
Works as expected, no issues.

NIT:
We could add some colors or other "aesthetic" things (like the one i mentioned below for example) to the popup though.

When selecting more than 9 entries, the list looks something like this:
```
1. Alacritty         
2. Android Debloater 
3. Bash Prompt       
4. Bottles           
5. DWM-Titus         
6. Docker            
7. Fastfetch         
8. Grub Theme        
9. Kitty             
10. Linutil Installer
11. Office Suite     
12. ZSH Prompt
```
We could make it check for the number of selected entries and add an extra space after the number for every 9/10 so it'd look like this:
```
9.  Kitty             
10. Linutil Installer
```

2024-09-28 19:51 UTC, cartercanedy commented
@lj3954 sorry for jumping to conclusions, I do like what you did with `FloatEvent` and making the `handle_key_event` api more fluent, but I do think that the confirmation float and potentially other potential features could benefit from specialization of `Float` for concrete types instead of being limited by `FloatContent` trait objects

2024-09-28 20:05 UTC, cartercanedy commented
how about
```
 1. ...
 ...
10. ...
```

2024-09-28 20:08 UTC, adamperkowski commented
> how about
> 
> ```
>  1. ...
>  ...
> 10. ...
> ```

Looks alright.

2024-09-28 20:09 UTC, adamperkowski commented on tui/src/confirmation.rs
> +                    .collect::<String>();
Clippy is mad again.

```suggestion
                let space_str = (0..(max_count_str.len() - count_str.len()))
                    .map(|_| ' ')
                    .collect::<String>();
```

2024-09-28 20:10 UTC, cartercanedy commented on tui/src/confirmation.rs
> +                    .collect::<String>();
yeah, I should just add `cargo clippy` to a precommit hook at this point

2024-09-28 20:13 UTC, adamperkowski commented on tui/src/confirmation.rs
> +                    .collect::<String>();
Add `cargo clippy -- -Dwarnings` so it'll return `0` on warnings.

2024-09-30 21:32 UTC, nnyyxxxx requested changes
love it

2024-09-30 21:48 UTC, merged