Removing autoclean from system-cleanup.sh (for nala)
ChrisTitusTech/linutil pull request #697
Opened 2024-09-29 11:50 UTC by AngelosGian

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [x] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description

Remove autoclean from system-cleanup.sh . Nala doesn't have autoclean command.
Please read additional information

## Testing

edited the script under core/tabs/system-setup/system-cleanup.sh
saved the changes
cargo run >  System-setup > Full System Cleanup
Everything works without the error

## Impact

## Issues / other PRs related

- Resolves #

## Additional Information

Autoclean is a command of apt-get that works. Unfortunately, nala doesn't have that command.
I tried an if statement to resolve this issue but it throws an syntax error that I couldn't resolve.
I though to make another case for nala but I leave it for discussion.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-29 14:19 UTC, jeevithakannan2 approved these changes

2024-09-29 22:06 UTC, nnyyxxxx approved these changes

2024-09-30 00:11 UTC, lj3954 commented
Why don't we just disregard the packager variable there and use `apt-get autoclean`? Nala depends on apt, correct?

2024-09-30 01:15 UTC, nnyyxxxx commented
> Why don't we just disregard the packager variable there and use `apt-get autoclean`? Nala depends on apt, correct?

why do that?

2024-09-30 01:16 UTC, nnyyxxxx commented
the user will always have apt / apt-get on their sys anyways. its best just to keep the packager var

> Why don't we just disregard the packager variable there and use `apt-get autoclean`? Nala depends on apt, correct?

2024-09-30 02:56 UTC, lj3954 commented
> the user will always have apt / apt-get on their deb derivative anyways. its best just to keep the packager var

Yes. My suggestion is to change that one specific line from `"$ESCALATION_TOOL" "$PACKAGER" autoclean` to `"$ESCALATION_TOOL" apt-get autoclean`, since nala is missing this functionality and apt-get will be present on debian systems, as you mentioned.

2024-09-30 03:12 UTC, nnyyxxxx commented
> > the user will always have apt / apt-get on their deb derivative anyways. its best just to keep the packager var
> 
> Yes. My suggestion is to change that one specific line from `"$ESCALATION_TOOL" "$PACKAGER" autoclean` to `"$ESCALATION_TOOL" apt-get autoclean`, since nala is missing this functionality and apt-get will be present on debian systems, as you mentioned.

no need 
![image](https://github.com/user-attachments/assets/7ff29323-8d7b-45bf-9753-77302e8b1d2d)

2024-09-30 03:13 UTC, nnyyxxxx commented
nala is being removed so it will default to apt via the packager above

2024-09-30 03:15 UTC, nnyyxxxx commented on core/tabs/system-setup/system-cleanup.sh
> -            "$ESCALATION_TOOL" "$PACKAGER" autoclean
instead of removing, change the packager variable to apt-get

2024-09-30 06:15 UTC, AngelosGian commented on core/tabs/system-setup/system-cleanup.sh
> -            "$ESCALATION_TOOL" "$PACKAGER" autoclean
Thank you very much. I haven't thought of that. I test it and it works. Again thank you very much.

2024-09-30 06:34 UTC, jeevithakannan2 commented
Removing autoclean is the better option here

`man apt-get`

```
clean
   clean clears out the local repository of retrieved package files. It
   removes everything but the lock file from /var/cache/apt/archives/ and
   /var/cache/apt/archives/partial/.

autoclean (and the auto-clean alias since 1.1)
   Like clean, autoclean clears out the local repository of retrieved
   package files. The difference is that it only removes package files
   that can no longer be downloaded, and are largely useless. This allows
   a cache to be maintained over a long period without it growing out of
   control. The configuration option APT::Clean-Installed will prevent
   installed packages from being erased if it is set to off.
```

Doing a `apt-get clean` will remove everything in `/var/cache/apt/archives/` so `apt-get autoclean` is useless here

2024-09-30 07:11 UTC, AngelosGian commented
Well, I will leave it as is (deleted). Chris will decide if he will accept it or not. So, no big deal. Again thank you for the feedback.

2024-09-30 07:12 UTC, nnyyxxxx commented
> Removing `autoclean` is the better option here
> 
> `man apt-get`
> 
> ```
> clean
>    clean clears out the local repository of retrieved package files. It
>    removes everything but the lock file from /var/cache/apt/archives/ and
>    /var/cache/apt/archives/partial/.
> 
> autoclean (and the auto-clean alias since 1.1)
>    Like clean, autoclean clears out the local repository of retrieved
>    package files. The difference is that it only removes package files
>    that can no longer be downloaded, and are largely useless. This allows
>    a cache to be maintained over a long period without it growing out of
>    control. The configuration option APT::Clean-Installed will prevent
>    installed packages from being erased if it is set to off.
> ```
> 
> Doing a `apt-get clean` will remove everything in `/var/cache/apt/archives/` so `apt-get autoclean` is useless here.
> 
> `apt clean` or `nala clean` also does the same by removing everything in `/var/cache/apt/archives/`

well it was lj's suggestion to add it back after all :joy:

2024-09-30 07:29 UTC, jeevithakannan2 requested changes

2024-09-30 07:29 UTC, jeevithakannan2 commented on core/tabs/system-setup/system-cleanup.sh
> +            "$ESCALATION_TOOL" "apt-get" autoclean
```suggestion
```

Removing `autoclean` is the better option here

`man apt-get`

```
clean
   clean clears out the local repository of retrieved package files. It
   removes everything but the lock file from /var/cache/apt/archives/ and
   /var/cache/apt/archives/partial/.

autoclean (and the auto-clean alias since 1.1)
   Like clean, autoclean clears out the local repository of retrieved
   package files. The difference is that it only removes package files
   that can no longer be downloaded, and are largely useless. This allows
   a cache to be maintained over a long period without it growing out of
   control. The configuration option APT::Clean-Installed will prevent
   installed packages from being erased if it is set to off.
```

Doing a `apt-get clean` will remove everything in `/var/cache/apt/archives/` so `apt-get autoclean` is useless here.

`nala clean` also does the same by removing everything in `/var/cache/apt/archives/`

Adding `apt-get autoclean` will not do anything here it is basically useless if `apt-get clean` or `nala clean` is used

2024-09-30 07:29 UTC, jeevithakannan2 commented on core/tabs/system-setup/system-cleanup.sh
>              "$ESCALATION_TOOL" "$PACKAGER" clean
Also remove this duplicate clean


```suggestion
```

2024-09-30 07:50 UTC, AngelosGian commented on core/tabs/system-setup/system-cleanup.sh
>              "$ESCALATION_TOOL" "$PACKAGER" clean
Right I forgot that.

2024-09-30 08:07 UTC, jeevithakannan2 approved these changes

2024-09-30 08:36 UTC, nnyyxxxx approved these changes

2024-09-30 22:18 UTC, lj3954 approved these changes

2024-10-24 21:52 UTC, adamperkowski approved these changes
Good to merge

2024-10-31 19:02 UTC, merged