New Feature : Setting Default TTY Fonts to Terminus Fonts
ChrisTitusTech/linutil pull request #698
Opened 2024-09-29 14:51 UTC by blusewill

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
This will set the Default Font from whatever is it to the Terminus Fonts Size 32 Bold

## Testing
![2024-09-29_22-45](https://github.com/user-attachments/assets/7c1c4ba2-65f4-4dff-a0b8-7484cbb97c2c)

## Impact
Installs Terminus Fonts as Dependency.

## Additional Information
The Current setfont is currently default to /dev/tty1.
Due to the script is executing in a sub process

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-29 18:52 UTC, adamperkowski requested changes
Add this to `docs/userguide.md`

2024-09-29 18:52 UTC, adamperkowski commented on core/tabs/system-setup/tab_data.toml
> +name = "Set TTY Fonts"
```suggestion
name = "TTY Fonts"
```

2024-09-29 18:52 UTC, adamperkowski commented on core/tabs/system-setup/tab_data.toml
> +description = "This Script will set the default font for tty to Terminus Fonts size 32 Bold And Set tty1 to the Terminus Font"
```suggestion
description = "This Script will set the default TYY font to Terminus size 32 Bold"
```

2024-09-29 23:50 UTC, adamperkowski requested changes

2024-09-29 23:50 UTC, adamperkowski commented on core/tabs/system-setup/tab_data.toml
> +task_list = "RP"
```suggestion
task_list = "I PFM"
```

I for installation
PFM for privileged file modification
This script doesn't remove any packages.

2024-09-29 23:50 UTC, adamperkowski commented on core/tabs/system-setup/terminus-tty.sh
> +       [ ! -f "/usr/lib/kbd/consolefonts/ter-p32n.psf.gz" ]; then
These statements could be merged into one.

2024-09-29 23:50 UTC, adamperkowski commented on core/tabs/system-setup/terminus-tty.sh
> +    # Checking the Font is installed or not. By Checking the Font Files
No need for this comment. Code is pretty self explanatory.

2024-09-29 23:50 UTC, adamperkowski commented on core/tabs/system-setup/terminus-tty.sh
> +                # Setting Default TTY Fonts
Same here.

2024-09-29 23:50 UTC, adamperkowski commented on core/tabs/system-setup/terminus-tty.sh
> +                fi
1. The comment could be removed
2. This is not checking if running Xorg OR Wayland, it's checking Xorg AND wayland.

2024-09-29 23:50 UTC, adamperkowski commented on core/tabs/system-setup/terminus-tty.sh
> +                # Setting Default TTY Fonts
Same here.

2024-09-29 23:50 UTC, adamperkowski commented on core/tabs/system-setup/terminus-tty.sh
> +                # After Edited the console-setup requires initramfs to be updated
```suggestion
                # Editing console-setup requires initramfs to be regenerated
```

2024-09-29 23:50 UTC, adamperkowski commented on core/tabs/system-setup/terminus-tty.sh
> +                fi
Same here. The if statement is wrong.

2024-09-29 23:50 UTC, adamperkowski commented on core/tabs/system-setup/terminus-tty.sh
> +                fi
Same here. The if statement is wrong.
This should probably be moved to a function or check only once and save the output since it's used a couple of times.

2024-09-30 16:06 UTC, adamperkowski approved these changes
Thanks

2024-09-30 22:21 UTC, ChrisTitusTech approved these changes

2024-09-30 22:21 UTC, merged

2024-09-30 22:21 UTC, adamperkowski commented on core/tabs/system-setup/terminus-tty.sh
> +        esac
there should be an exception for `*` here. it should return 1