Adding Fedora ISO download.
ChrisTitusTech/linutil pull request #699
Opened 2024-09-29 16:30 UTC by lennartpj

## Type of Change
- [x] New feature

## Description
This pull request adds functionality to download the latest Fedora Workstation ISO in the "create-bootable-usb.sh". This allows users to conveniently access Fedora alongside the present distributions.

## Testing
I have tested the changes by executing cargo run and confirming that the latest Fedora ISO URL is fetched correctly without any errors. The output is displayed as expected, and the script functions as intended.

## Impact
The change introduces a new option for users to select Fedora as an ISO source, enhancing the usability of the script. No new dependencies have been introduced, and the performance remains unaffected.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-29 21:15 UTC, adamperkowski requested changes

2024-09-29 21:15 UTC, adamperkowski commented on core/tabs/utils/create-bootable-usb.sh
> +# Function to fetch the latest Fedora Workstation ISO
Remove these comments.
And take look at [the guidelines](https://github.com/ChrisTitusTech/linutil/blob/main/.github/CONTRIBUTING.md#8-understand-and-test-the-code-you-write).

2024-09-29 21:15 UTC, adamperkowski commented on core/tabs/utils/create-bootable-usb.sh
> +    # Convert the input to lowercase and compare
Remove these comments.
And take look at [the guidelines](https://github.com/ChrisTitusTech/linutil/blob/main/.github/CONTRIBUTING.md#8-understand-and-test-the-code-you-write).

2024-09-29 21:17 UTC, adamperkowski commented
> The confirmation prompt accepts 'y', 'yes', and case-insensitive variants. The output is displayed as expected, and the script functions as intended.

Please rewrite the code and this PRs description without using AI/LLMs.

2024-09-29 21:31 UTC, adamperkowski commented
Add this to `docs/userguide.md`

2024-09-30 00:06 UTC, lj3954 commented
Hardcoding releases induces a major maintenance burden. Please use APIs available to you: https://www.fedoraproject.org/releases.json

2024-09-30 12:41 UTC, lennartpj commented on core/tabs/utils/create-bootable-usb.sh
> +# Function to fetch the latest Fedora Workstation ISO
I have removed the Comments!

2024-09-30 12:41 UTC, lennartpj commented on core/tabs/utils/create-bootable-usb.sh
> +    # Convert the input to lowercase and compare
I have removed the Comments!

2024-09-30 12:44 UTC, lennartpj commented
> Hardcoding releases induces a major maintenance burden. Please use APIs available to you: https://www.fedoraproject.org/releases.json

Thank you for the advice! I have changed my part accordingly

2024-09-30 13:06 UTC, adamperkowski requested changes

2024-09-30 13:06 UTC, adamperkowski commented on core/tabs/utils/create-bootable-usb.sh
> +    FEDORA_URL=$(curl -s 'https://www.fedoraproject.org/releases.json' | jq -r '.[] | select(.version == "40" and .arch == "x86_64" and .variant == "Workstation") | select(.link | match(".*Live-x86_6
Tested your code, works as expected **but** jquery is not POSIX-compliant and not all distros ship it by default. This script could install it before running by a think this is a better idea:

```suggestion
    FEDORA_URL=$(curl -s 'https://www.fedoraproject.org/releases.json' |
    grep -o '"link": "[^"]*' |
    sed -e 's/"link": "//' |
    awk -v version="40" -v arch="x86_64" -v variant="Workstation" ' BEGIN { FS="," }
    {
        if ($0 ~ version && $0 ~ arch && $0 ~ variant && $0 ~ "Live-x86_64") {
            print $0
        }
    }' |
    head -n 1)
```
And please, fix my tabs and spaces here, I'm typing this from my phone.

2024-09-30 14:29 UTC, adamperkowski approved these changes
Thanks

2024-09-30 14:56 UTC, lennartpj commented
@adamperkowski  
Thank you very much! I still have a lot to learn :)

2024-09-30 18:07 UTC, lj3954 commented on core/tabs/utils/create-bootable-usb.sh
> +    FEDORA_URL=$(curl -s 'https://www.fedoraproject.org/releases.json' | jq -r '.[] | select(.version == "40" and .arch == "x86_64" and .variant == "Workstation") | select(.link | match(".*Live-x86_6
jq is a JSON parser, jQuery is a JS library. They are not the same thing. All of these are external tools (even curl, grep, sed, which are practically universal), though it is obviously preferable to use more common programs whenever possible.

2024-10-09 11:45 UTC, adamperkowski requested changes

2024-10-09 11:45 UTC, adamperkowski commented on docs/userguide.md
> +- **Bootable USB Creator**: Makes a USB Stick that can be used to install the selected Linux distribution.
Please move this to the script's description in `tab_data.toml` and run `cargo xtask docgen`. Otherwise, it's gonna conflict.

2024-10-10 14:18 UTC, lennartpj commented on docs/userguide.md
> +- **Bootable USB Creator**: Makes a USB Stick that can be used to install the selected Linux distribution.
Okay, will do as soon as I'm back home next week :)

2024-10-17 17:41 UTC, adamperkowski approved these changes
thanks

2024-10-17 17:41 UTC, adamperkowski commented on core/tabs/utils/create-bootable-usb.sh
> +    printf "%b\n" "${GREEN} Selected Fedora Workstation (latest) ISO URL: ${RC} $FEDORA_URL"
```suggestion
    printf "%b\n" "${GREEN} Selected Fedora Workstation (latest) ISO URL:${RC} $FEDORA_URL"
```

2024-10-17 17:41 UTC, adamperkowski commented on docs/userguide.md
> +- **Bootable USB Creator**: Makes a USB Stick that can be used to install the selected Linux distribution.
no problem

2024-10-30 12:07 UTC, lennartpj commented
@adamperkowski I have change the version from 40 to 41.
I have also tested the change and made a fresh install of fedora 41 using this method.

2024-10-30 14:05 UTC, adamperkowski approved these changes
> @adamperkowski I have change the version from 40 to 41. I have also tested the change and made a fresh install of fedora 41 using this method.

Thanks. Good to merge.

2024-10-31 18:04 UTC, jeevithakannan2 commented
https://github.com/ChrisTitusTech/linutil/pull/828 was merged this can be closed

2024-10-31 18:10 UTC, closed without merging