added waterfox browser
ChrisTitusTech/linutil pull request #700
Opened 2024-09-30 03:22 UTC by hexisXz

## Type of Change
- [1] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description

## Testing

## Issues / other PRs related

- Resolves #

## Additional Information

## Checklist
- [ I am 95% sure it does] My code adheres to the coding and style guidelines of the project.
- [ YES] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ YES] My changes generate no errors/warnings/merge conflicts.

2024-09-30 03:34 UTC, nnyyxxxx commented on core/tabs/applications-setup/browsers/waterfox.sh
> +}
this is no good, it needs to be in 1 function and you cannot use wget and if anything this is the ugliest code i have seen in my life

![image](https://github.com/user-attachments/assets/7e1f95c2-405d-491f-b426-c49bb5578bfe)

merge this into the installwaterfox function and use curl instead of wget, also waterfox is in the aur so use checkAURHelper along with the aur_helper for the pacman packager

and put the waterfox building in *)

2024-09-30 03:36 UTC, nnyyxxxx commented on core/tabs/applications-setup/browsers/waterfox.sh
> +}
make sure to use the waterfox binary

2024-09-30 03:41 UTC, hexisXz commented on core/tabs/applications-setup/browsers/waterfox.sh
> +}
If you mean the stuff that's in the function is ugly then yeah agreed. also why do i have to use curl instead of wget?

2024-09-30 03:43 UTC, nnyyxxxx commented on core/tabs/applications-setup/browsers/waterfox.sh
> +}
> If you mean the stuff that's in the function is ugly then yeah agreed. also why do i have to use curl instead of wget?

curl is more extensible and is preinstalled on most distros while wget is not

2024-09-30 03:44 UTC, nnyyxxxx commented on core/tabs/applications-setup/browsers/waterfox.sh
> +}
its to keep the synergy between the scripts as well, we don't want to be installing any unnecessary packages on the users sys

2024-09-30 03:48 UTC, nnyyxxxx commented on core/tabs/applications-setup/browsers/waterfox.sh
> +	        ;;
```bash
		    "$ESCALATION_TOOL" "$PACKAGER" --non-interactive install wget && buildWaterfox
```
this is also formatted incorrectly

2024-09-30 04:01 UTC, hexisXz commented on core/tabs/applications-setup/browsers/waterfox.sh
> +}
> this is no good, it needs to be in 1 function and you cannot use wget and if anything this is the ugliest code i have seen in my life
> 
> ![image](https://private-user-images.githubusercontent.com/144965845/371935965-7e1f95c2-405d-491f-b426-c49bb5578bfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NjgxNDAsIm5iZiI6MTcyNzY2Nzg0MCwicGF0aCI6Ii8xNDQ5NjU4NDUvMzcxOTM1OTY1LTdlMWY5NWMyLTQwNWQtNDkxZi1iNDI2LWM0OWJiNTU3OGJmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQwMzQ0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmQ0NDVhOTk4NWEwYThhNjRhOTNlYjc3YmM5NjRiMTZiMmFlNjYyZjMwNmFiZmQ4MzNmNTdiMDVmYjAxZjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QdKZWdAMvDNx_SBaPc7wDMevs14fmFv02MZXF0ivsAM)
> 
> merge this into the installwaterfox function and use curl instead of wget, also waterfox is in the aur so use checkAURHelper along with the aur_helper for the pacman packager
> 
> and put the waterfox building / installing in *) for other packagers

okay before i do anything do this look better 

`#!/bin/sh -e

. ../../common-script.sh

installWaterfox() {
    buildWaterfox=$(curl -L -o waterfox.tar.bz2 "https://cdn1.waterfox.net/waterfox/releases/latest/linux" && tar -xvjf waterfox.tar.bz2 -C ./ && rm waterfox.tar.bz2 ; sudo mkdir -p /opt/waterfox && sudo mv waterfox /opt/waterfox && cd /opt/waterfox/waterfox && sudo ln -s /opt/waterfox/waterfox/waterfox /usr/bin/waterfox)

    if ! command_exists firefox; then
        printf "%b\n" "${YELLOW}Installing waterfox...${RC}"
        case "$PACKAGER" in
            apt-get|nala)
		"$ESCALATION_TOOL" "$PACKAGER" install -y curl && printf("$buildWaterfox")
                ;;
            zypper)
                "$ESCALATION_TOOL" "$PACKAGER" --non-interactive install curl && printf("$buildWaterfox")
                ;;
            pacman)
                "$ESCALATION_TOOL" "$PACKAGER" -S --needed --noconfirm curl && printf("$buildWaterfox")
                ;;
            dnf)
                "$ESCALATION_TOOL" "$PACKAGER" install -y curl && printf("$buildWaterfox")
                ;;
            *)
                printf "%b\n" "${RED}Unsupported package manager: ""$PACKAGER""${RC}"
                exit 1
                ;;
        esac
    else
        printf "%b\n" "${GREEN}Waterfox Browser is already installed.${RC}"
    fi
}

checkEnv
checkEscalationTool
installWaterfox`

2024-09-30 04:06 UTC, nnyyxxxx commented on core/tabs/applications-setup/browsers/waterfox.sh
> +}
no it looks terrible

2024-09-30 04:07 UTC, nnyyxxxx commented
@adamperkowski please help this guy lmao, hes making it worse; i dont have the sanity right now to even bother. I gave clear-cut instructions on what to do and hes messing it up even more.

2024-09-30 04:08 UTC, hexisXz commented on core/tabs/applications-setup/browsers/waterfox.sh
> +}
> no it looks terrible

all of it or just buildWaterfox

2024-09-30 04:10 UTC, nnyyxxxx commented on core/tabs/applications-setup/browsers/waterfox.sh
> +}
> > no it looks terrible
> 
> all of it or just buildWaterfox

all of it, please re-read my original message. I gave you clear-cut instructions on what to do.

2024-09-30 04:11 UTC, nnyyxxxx commented on core/tabs/applications-setup/browsers/waterfox.sh
> +}
also no need to install curl

2024-09-30 04:13 UTC, hexisXz commented on core/tabs/applications-setup/browsers/waterfox.sh
> +}
> > > no it looks terrible
> > 
> > 
> > all of it or just buildWaterfox
> 
> all of it, please re-read my original message. I gave you clear-cut instructions on what to do.

well idk how all of it looks bad to you because if thats the case then you need to remove all the browser scripts because all i did was copy and paste the firefox script and added this part `buildWaterfox=$(curl -L -o waterfox.tar.bz2 "https://cdn1.waterfox.net/waterfox/releases/latest/linux" && tar -xvjf waterfox.tar.bz2 -C ./ && rm waterfox.tar.bz2 ; sudo mkdir -p /opt/waterfox && sudo mv waterfox /opt/waterfox && cd /opt/waterfox/waterfox && sudo ln -s /opt/waterfox/waterfox/waterfox /usr/bin/waterfox)` thats the only code that i added. along with the printf after curl gets installed

2024-09-30 04:15 UTC, nnyyxxxx commented on core/tabs/applications-setup/browsers/waterfox.sh
> +                ;;
the formatting for all of this is still off as well

2024-09-30 04:22 UTC, nnyyxxxx commented on core/tabs/applications-setup/browsers/waterfox.sh
> +checkEscalationTool
```suggestion
checkEscalationTool
checkAURHelper
```

2024-09-30 04:22 UTC, nnyyxxxx commented on core/tabs/applications-setup/browsers/waterfox.sh
> +        printf "%b\n" "${GREEN}Waterfox Browser is already installed.${RC}"
```suggestion
        printf "%b\n" "${GREEN}Waterfox is already installed.${RC}"
```

2024-09-30 04:22 UTC, nnyyxxxx commented on core/tabs/applications-setup/browsers/waterfox.sh
> +    buildWaterfox=$(curl -L -o waterfox.tar.bz2 "https://cdn1.waterfox.net/waterfox/releases/latest/linux" && tar -xvjf waterfox.tar.bz2 -C ./ && rm waterfox.tar.bz2 ; sudo mkdir -p /opt/waterfox &&
remove this as well

2024-09-30 04:22 UTC, nnyyxxxx commented on core/tabs/applications-setup/browsers/waterfox.sh
> +}
@hexisXz refer to my latest reviews

2024-09-30 04:34 UTC, nnyyxxxx commented
@hexisXz dude. remove the building, the package is in the aur

2024-09-30 04:34 UTC, nnyyxxxx commented
```bash
            pacman)
                "$AUR_HELPER" -S --needed --noconfirm waterfox-bin
                ;;
            *)
                . ./setup-flatpak.sh
                flatpak install -y flathub net.waterfox.waterfox
                ;;
                ```
its supposed to be like this

2024-09-30 04:35 UTC, nnyyxxxx requested changes

2024-09-30 04:35 UTC, nnyyxxxx commented on core/tabs/applications-setup/browsers/waterfox.sh
> +    buildWaterfox=$(curl -L -o waterfox.tar.bz2 "https://cdn1.waterfox.net/waterfox/releases/latest/linux" && tar -xvjf waterfox.tar.bz2 -C ./ && rm waterfox.tar.bz2 ; sudo mkdir -p /opt/waterfox &&
remove the building, the pkg is in the aur

2024-09-30 04:35 UTC, nnyyxxxx commented on core/tabs/applications-setup/browsers/waterfox.sh
> +                "$ESCALATION_TOOL" "$PACKAGER" -S --needed --noconfirm curl && printf "$buildWaterfox"
```suggestion
                "$AUR_HELPER" -S --needed --noconfirm waterfox-bin
```

2024-09-30 04:36 UTC, nnyyxxxx commented on core/tabs/applications-setup/browsers/waterfox.sh
> +                ;;
```bash
            *)
                . ./setup-flatpak.sh
                flatpak install -y flathub net.waterfox.waterfox
                ;;
```
use this

2024-09-30 04:38 UTC, hexisXz commented on core/tabs/applications-setup/browsers/waterfox.sh
> +}
> @hexisXz refer to my latest reviews

okay i removed every package manager except pacman and added the other changes

2024-09-30 04:38 UTC, hexisXz commented on core/tabs/applications-setup/browsers/waterfox.sh
> +    buildWaterfox=$(curl -L -o waterfox.tar.bz2 "https://cdn1.waterfox.net/waterfox/releases/latest/linux" && tar -xvjf waterfox.tar.bz2 -C ./ && rm waterfox.tar.bz2 ; sudo mkdir -p /opt/waterfox &&
okay hold on

2024-09-30 04:43 UTC, hexisXz commented on core/tabs/applications-setup/browsers/waterfox.sh
> +                ;;
okay is everything good now?

2024-09-30 04:46 UTC, nnyyxxxx approved these changes
looks good atm, if they make any changes my opinion will of course change.

2024-09-30 04:46 UTC, nnyyxxxx commented on core/tabs/applications-setup/browsers/waterfox.sh
> +                ;;
yes @hexisXz resolve all of the reviews

2024-09-30 04:46 UTC, hexisXz commented
> looks good atm, if they make any changes my opinion will of course change.

okay

2024-09-30 04:48 UTC, nnyyxxxx commented on core/tabs/applications-setup/tab_data.toml
> +task_list = "I"
```suggestion
task_list = "FI"
```

2024-09-30 04:49 UTC, nnyyxxxx commented on core/tabs/applications-setup/tab_data.toml
> +task_list = "I"
flatpak installation is fi instead of i

2024-09-30 04:51 UTC, hexisXz commented on core/tabs/applications-setup/tab_data.toml
> +task_list = "I"
> flatpak installation is fi instead of i

fixed

2024-09-30 04:52 UTC, nnyyxxxx commented
@hexisXz resolve all of these reviews please

2024-09-30 04:53 UTC, hexisXz commented
> @hexisXz resolve all of these reviews please

like resole the conversations

2024-09-30 04:54 UTC, hexisXz commented
> @hexisXz resolve all of these reviews please

alr i think i did it

2024-09-30 14:28 UTC, adamperkowski requested changes

2024-09-30 14:28 UTC, adamperkowski commented on core/tabs/applications-setup/browsers/waterfox.sh
> +		. ./setup-flatpak.sh
@nnyyxxxx You're the one not testing now. 

```suggestion
		. ../setup-flatpak.sh
```

2024-09-30 14:45 UTC, hexisXz commented on core/tabs/applications-setup/browsers/waterfox.sh
> +		. ./setup-flatpak.sh
> @nnyyxxxx You're the one not testing now.

fixed

2024-09-30 15:34 UTC, nnyyxxxx commented on core/tabs/applications-setup/browsers/waterfox.sh
> +		. ./setup-flatpak.sh
> @nnyyxxxx You're the one not testing now.

not my job, not my pr, :laughing:

2024-09-30 16:07 UTC, adamperkowski approved these changes
Thanks

2024-10-01 22:53 UTC, nnyyxxxx commented
@hexisXz keep this PR focused on 1 thing, move the lapce ide section to a different PR

2024-10-01 23:00 UTC, hexisXz commented
> @hexisXz keep this PR focused on 1 thing, move the lapce ide section to a different PR

lol you are fast. I tried to delete that before anyone could see it but i think i removed it. this is my first time doing a PR so i actually dont know what i am doing.

2024-10-09 11:46 UTC, adamperkowski commented
@hexisXz Please run `cargo xtask docgen` and push the changes. Thanks.

2024-10-20 12:57 UTC, jeevithakannan2 requested changes

2024-10-20 12:57 UTC, jeevithakannan2 commented on core/tabs/applications-setup/browsers/waterfox.sh
> +    if ! command_exists waterfox; then
```suggestion
    if ! command_exists net.waterfox.waterfox && ! command_exists waterfox; then
```

2024-10-20 12:57 UTC, jeevithakannan2 commented on core/tabs/applications-setup/browsers/waterfox.sh
> +    if ! command_exists waterfox; then
Add `net.waterfox.waterfox` for flatpak binaries

2024-10-31 18:04 UTC, ChrisTitusTech approved these changes

2024-10-31 18:04 UTC, merged