refact fix: Flatpak
ChrisTitusTech/linutil pull request #705
Opened 2024-09-30 13:12 UTC by jeevithakannan2

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [x] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
- Moved flatpak handling to `common-script` due to path conflicts when `setup-flatpak` is called from different tabs.
- The following error was reproduced by removing the `pacman` installation section, forcing the script to use flatpak for installation: 

> [!NOTE]
> This issue was originally identified on another laptop running openSUSE. Since no screenshots were captured in openSUSE, the workaround was applied to reproduce the error.

![flatpak-error](https://github.com/user-attachments/assets/128d2d7e-73f1-49c5-911a-ec74942408da)

## Testing
- Tested on arch and openSUSE, works as expected.

## Additional Description
- Office script is excluded from this PR as it requires a rework. It should be split into separate scripts for better maintainability.
- This implementation is basic and can be improved in future.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-09-30 13:21 UTC, nnyyxxxx commented
@jeevithakannan2 this is going to break a lot of things and this is bloating up common script, you're doing too much here man, literally its a 1 dot fix...

2024-09-30 13:22 UTC, nnyyxxxx commented
setup-flatpak is in the dir before zoom... just add an extra dot, why are you adding all of this bloat into linutil?

2024-09-30 13:24 UTC, nnyyxxxx requested changes
its a simple 1 dot fix, all of this bloat is being added why exactly? please refactor this PR to add an extra dot to the flatpak pathing

2024-09-30 13:39 UTC, nnyyxxxx approved these changes
if any other scripts use flatpak be sure to include these changes

2024-09-30 13:42 UTC, nnyyxxxx commented on core/tabs/applications-setup/bottles-setup.sh
> +        flatpak install -y flathub com.usebottles.bottles
just use command_exists instead of a custom flatpak command_exists it shouldnt matter too much

2024-09-30 13:42 UTC, nnyyxxxx commented on core/tabs/applications-setup/communication-apps/slack-setup.sh
> +}
this is rough remove this and just add the variable below

2024-09-30 13:42 UTC, nnyyxxxx commented on core/tabs/applications-setup/communication-apps/slack-setup.sh
> +    if ! checkSlackInstallation; then
undo these changes

2024-09-30 13:42 UTC, nnyyxxxx commented on core/tabs/applications-setup/communication-apps/zoom-setup.sh
> +}
same with the previous reviews this is rough, read the previous changes

2024-09-30 13:43 UTC, nnyyxxxx commented on core/tabs/applications-setup/communication-apps/zoom-setup.sh
> +    if ! checkZoomInstallation; then
undo this and just source at the bottom of script

2024-09-30 14:02 UTC, jeevithakannan2 commented on core/tabs/applications-setup/bottles-setup.sh
> +        flatpak install -y flathub com.usebottles.bottles
flatpak binaries is not in PATH

2024-09-30 16:31 UTC, jeevithakannan2 commented
> DONT merge this yet, needs more discussing, this implementation is a bit dirty and i feel like we can just combine the flatpak command_exists with the reg one

It's tricky to implement it that way. I tried multiple ways and came up with this just for now. This is a basic implementation and can be changed in future !!

2024-09-30 16:42 UTC, jeevithakannan2 commented
> if any other scripts use flatpak be sure to include these changes

Included all the scripts except office setup. It needs a rework splitting them would be better for maintaining the code

2024-10-09 14:51 UTC, jeevithakannan2 commented
> DONT merge this yet, needs more discussing, this implementation is a bit dirty and i feel like we can just combine the flatpak command_exists with the reg one

Combined both

2024-10-30 23:01 UTC, adamperkowski approved these changes
I'd wait with this until other PRs that may conflict are resolved.

2024-11-01 17:25 UTC, ChrisTitusTech approved these changes

2024-11-01 17:25 UTC, merged