Added Fedora on Docker Setup
ChrisTitusTech/linutil pull request #707
Opened 2024-09-30 17:48 UTC by Angxddeep

## Type of Change
- [x] New feature

## Description
Making Docker setup to work on fedora

## Testing
Working flawlessly

## Impact
Life for Fedora users will be easier while installing docker 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-10-04 09:26 UTC, nnyyxxxx approved these changes

2024-10-20 12:58 UTC, jeevithakannan2 requested changes

2024-10-20 12:58 UTC, jeevithakannan2 commented on core/tabs/applications-setup/docker-setup.sh
> +            "$ESCALATION_TOOL" systemctl start docker
```suggestion
            "$ESCALATION_TOOL" systemctl enable --now docker
```

2024-10-20 15:24 UTC, jeevithakannan2 approved these changes

2024-10-30 23:02 UTC, adamperkowski approved these changes

2024-10-31 19:14 UTC, merged