Fixed Vivaldi Setup
ChrisTitusTech/linutil pull request #718
Opened 2024-10-01 13:09 UTC by leventbesli

## Type of Change
- [ ] New feature
- [x ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description

Vivaldi setup section was containing Lynx install script. I replaced it with Vivaldi.

## Testing

Tested inside Fedora 40 and Debian 12 Distrobox environments. Installed successfully in both of them.

## Additional Information

First PR. Be gentle. 

## Checklist
- [ x] My code adheres to the coding and style guidelines of the project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x ] My changes generate no errors/warnings/merge conflicts.

2024-10-01 13:14 UTC, adamperkowski approved these changes
Hmmm...

2024-10-01 16:34 UTC, jeevithakannan2 requested changes
- Need to pacman and zypper in the installation
- Fix formatting
- Drop the changes to Cargo.lock

2024-10-02 09:27 UTC, adamperkowski approved these changes

2024-10-02 10:11 UTC, jeevithakannan2 requested changes
Just copy paste the the cargo.lock from the repo and push it. The cargo lock is fixed in the main branch.

2024-10-02 11:51 UTC, jeevithakannan2 requested changes

2024-10-02 11:51 UTC, jeevithakannan2 commented on core/tabs/applications-setup/browsers/vivaldi.sh
> +                "$ESCALATION_TOOL" "$PACKAGER" -S --needed --noconfirm xdg-utils vivaldi
Why are we adding xdg-utils ? 🤔

2024-10-02 12:02 UTC, leventbesli commented on core/tabs/applications-setup/browsers/vivaldi.sh
> +                "$ESCALATION_TOOL" "$PACKAGER" -S --needed --noconfirm xdg-utils vivaldi
ahh. It was from the test within headless Distrobox. It's not needed with desktop environments obviously. I will update it now. Thanks for pointing it out.

2024-10-02 12:10 UTC, jeevithakannan2 approved these changes

2024-10-04 09:23 UTC, nnyyxxxx approved these changes

2024-10-04 09:24 UTC, nnyyxxxx requested changes
drop the cargo lock changes or Chris will most likely decline this PR

2024-10-04 10:13 UTC, jeevithakannan2 commented
Don't do git rm cargo.lock

2024-10-04 10:17 UTC, jeevithakannan2 commented
Merge with upstream/main. It will fix the issue

2024-10-04 10:24 UTC, nnyyxxxx requested changes
commit these changes

2024-10-04 10:24 UTC, nnyyxxxx commented on Cargo.lock
> +version = "24.9.28"
```suggestion
version = "24.9.23"
```

2024-10-04 10:24 UTC, nnyyxxxx commented on Cargo.lock
> +version = "24.9.28"
```suggestion
version = "24.9.23"
```

2024-10-04 10:35 UTC, nnyyxxxx approved these changes

2024-10-31 19:16 UTC, ChrisTitusTech approved these changes

2024-10-31 19:19 UTC, merged