return user to their previous position if they enter a subdir
ChrisTitusTech/linutil pull request #725
Opened 2024-10-02 03:24 UTC by nnyyxxxx

## Type of Change
- [x] New feature

## Description
takes the user back to their previous position when they exit 

tested with a subdir inside of a subdir works as expected

tested with a regular subdir works as expected as well

examples: 
![image](https://github.com/user-attachments/assets/b17c6be8-c750-4a18-8a4d-c13228415289)
hitting enter on .. will take you back to
![image](https://github.com/user-attachments/assets/63f32f03-6d44-49f4-9e06-172eaac01ee0)
your previous position
and hitting enter on .. in the subdir inside of in the subdir in the subdir
![image](https://github.com/user-attachments/assets/477e6316-e92a-437f-a4ed-0fa4c886dfbb)
will take you back to
![image](https://github.com/user-attachments/assets/8546409f-2ab5-4ba6-a32b-e83328efd000)
your original position

before, it would just take u back to the first entry in the list

2024-10-02 03:42 UTC, cartercanedy requested changes
Put `visit_stack` and `position_stack` together:
```rust
// ...
    visit_stack: Vec<(Rc<ListNode>, usize)>
// ...
```

### Correction:
```rust
// ...
    visit_stack: Vec<(NodeId, usize)>,
// ...
```

2024-10-02 03:43 UTC, adamperkowski requested changes

2024-10-02 03:43 UTC, adamperkowski commented on tui/src/state.rs
> +        }
```suggestion
        if let Some(previous_position) = self.position_stack.pop() {
            self.visit_stack.pop();
            self.selection.select(Some(previous_position));
            self.update_items();
        }
```

2024-10-02 03:43 UTC, adamperkowski commented on tui/src/state.rs
> +        } else if self.selected_item_is_cmd() {
We could make a selected item type here and then use `match`. Just an idea, that would need a refactor.

2024-10-02 03:48 UTC, nnyyxxxx commented
> Put `visit_stack` and `position_stack` together:
> 
> ```rust
> // ...
>     visit_stack: Vec<(Rc<ListNode>, usize)>
> // ...
> ```

its best we keep them separated

2024-10-02 03:51 UTC, cartercanedy commented
> its best we keep them separated

Besides unnecessarily making a heap allocation, they're both participating in the same functionality; they're best together

2024-10-02 04:01 UTC, adamperkowski approved these changes

2024-10-02 04:04 UTC, nnyyxxxx commented on tui/src/state.rs
> +        } else if self.selected_item_is_cmd() {
solved with [ce5f037](https://github.com/ChrisTitusTech/linutil/pull/725/commits/ce5f0375b0ecec3e5beed2133f8a3713718d7987)

2024-10-02 04:09 UTC, nnyyxxxx commented
> > its best we keep them separated
> 
> Besides unnecessarily making a heap allocation, they're both participating in the same functionality; they're best together

sorry but i see no performance impact with this current implementation, if we want to combine them then we can refactor it in the future. For now this implementation is just a stepping stone.

2024-10-02 19:40 UTC, cartercanedy commented
> sorry but i see no performance impact with this current implementation, if we want to combine them then we can refactor it in the future. For now this implementation is just a stepping stone.

I figure that there's no better time than now
Just opened a PR for your fork, you're free to merge the changes if you want

2024-10-03 02:22 UTC, cartercanedy approved these changes
Awesome, thanks for merging that commit

2024-10-31 18:30 UTC, ChrisTitusTech approved these changes

2024-10-31 18:30 UTC, merged