allow scrolling past last entry / first entry
ChrisTitusTech/linutil pull request #727
Opened 2024-10-02 05:54 UTC by nnyyxxxx

# watch the video

regular scrolling and tab scrolling **NEEDS** to be separated, without separation, we wont be able to properly handle subdir cases

## Type of Change
- [x] New feature

## Description
wraps the user to the top of the list or to the bottom of the list depending on where they are at
example:

https://github.com/user-attachments/assets/567753aa-7725-4cce-b83c-966a868ea207

2024-10-02 06:54 UTC, adamperkowski requested changes
Other functions here like `scroll_up` need to be refactored aswell.

2024-10-02 06:54 UTC, adamperkowski commented on tui/src/state.rs
> +        let next = if current + 1 >= len { 0 } else { current + 1 };
```suggestion
        if self.tabs.len() == 0 {
            return;
        }

        let current = self.current_tab.selected().unwrap_or(0);
        let next = if current + 1 >= self.tabs.len() {
            0
        } else {
            current + 1
        };
 
```

2024-10-02 06:54 UTC, adamperkowski commented on tui/src/state.rs
> +        let next = if current == 0 { len - 1 } else { current - 1 };
```suggestion
        if self.tabs.len() == 0 {
            return;
        }

        let current = self.current_tab.selected().unwrap_or(0);
        let next = if current == 0 {
            self.tabs.len() - 1
        } else {
            current - 1
        };
        
```

2024-10-02 06:58 UTC, lj3954 commented on tui/src/state.rs
> +        let next = if current + 1 >= len { 0 } else { current + 1 };
core panics if tabs are empty, since it's an unreasonable expectation for a UI to handle rendering nothing. Checking if the length is equal to 0 (is_empty() by the way) is unnecessary.

2024-10-02 07:01 UTC, lj3954 requested changes
As mentioned in another comment, linutil core will panic on an empty tab array. Better error handling there may be a good idea, but the output of the function should still absolutely be guaranteed to not be empty; otherwise undefined behaviour could occur during UI rendering.

2024-10-02 07:02 UTC, adamperkowski commented on tui/src/state.rs
> +        let next = if current + 1 >= len { 0 } else { current + 1 };
```suggestion
        let current = self.current_tab.selected().unwrap_or(0);
        let next = if current + 1 >= self.tabs.len() {
            0
        } else {
            current + 1
        };
```

2024-10-02 07:13 UTC, nnyyxxxx commented on tui/src/state.rs
> +        let next = if current + 1 >= len { 0 } else { current + 1 };
I'd rather keep the current implementation.

2024-10-02 07:14 UTC, adamperkowski requested changes

2024-10-02 07:14 UTC, adamperkowski commented on tui/src/state.rs
> +        self.selection.select(Some(next));
```suggestion
        let current = self.selection.selected().unwrap_or(0);
        let max_index = if self.at_root() { self.filter.item_list().len() - 1 } else { self.filter.item_list().len() };
        let next = if current + 1 > max_index {
            0
        } else {
            current + 1
        };
        self.selection.select(Some(next));
```

2024-10-02 07:14 UTC, adamperkowski commented on tui/src/state.rs
> +        self.selection.select(Some(next));
```suggestion
        let current = self.selection.selected().unwrap_or(0);
        let max_index = if self.at_root() { self.filter.item_list().len() - 1 } else { self.filter.item_list().len() };
        let next = if current == 0 { max_index } else { current - 1 };
        self.selection.select(Some(next));
```

2024-10-02 07:15 UTC, adamperkowski commented
You missed 2, @lj3954

2024-10-02 07:16 UTC, adamperkowski requested changes

2024-10-02 07:16 UTC, adamperkowski commented on tui/src/state.rs
> +        }
```suggestion
```

2024-10-02 07:16 UTC, adamperkowski commented on tui/src/state.rs
> +        }
```suggestion
```

2024-10-02 07:18 UTC, adamperkowski requested changes

2024-10-02 07:18 UTC, adamperkowski commented on tui/src/state.rs
> +        self.selection.select(Some(next));
```suggestion
        };

        self.selection.select(Some(next));
```

2024-10-02 07:18 UTC, adamperkowski commented on tui/src/state.rs
> +        self.selection.select(Some(next));
```suggestion
        let next = if current == 0 { max_index } else { current - 1 };

        self.selection.select(Some(next));
```

2024-10-02 07:18 UTC, adamperkowski commented on tui/src/state.rs
> +        self.refresh_tab();
```suggestion
        let next = if current + 1 >= len { 0 } else { current + 1 };

        self.current_tab.select(Some(next));
        self.refresh_tab();
```

2024-10-02 07:18 UTC, adamperkowski commented on tui/src/state.rs
> +        self.refresh_tab();
```suggestion
        let next = if current == 0 { len - 1 } else { current - 1 };

        self.current_tab.select(Some(next));
        self.refresh_tab();
```

2024-10-02 07:21 UTC, adamperkowski approved these changes
Thanks.

2024-10-02 07:35 UTC, lj3954 commented
> You missed 2, @lj3954

No, those are wrong. The item list can be empty if a search term not matching anything is entered. You should get a panic with those changes applied in that case.

2024-10-02 07:38 UTC, adamperkowski commented on tui/src/state.rs
> +        let current = self.selection.selected().unwrap_or(0);
```suggestion
        if len == 0 {
            panic!("item_list cannot be empty");
        }

        let current = self.selection.selected().unwrap_or(0);
```

2024-10-02 07:38 UTC, adamperkowski commented on tui/src/state.rs
> +        let current = self.selection.selected().unwrap_or(0);
```suggestion
        let len = self.filter.item_list().len();
        if len == 0 {
            panic!("item_list cannot be empty");
        }

        let current = self.selection.selected().unwrap_or(0);
        let current = self.selection.selected().unwrap_or(0);
```

2024-10-02 07:40 UTC, lj3954 commented
Absolutely not. The item list can be empty, since a search can come up with no results. Only the tab list should be expected not to be empty.

2024-10-02 07:41 UTC, nnyyxxxx commented
> Absolutely not. The item list can be empty, since a search can come up with no results. Only the tab list should be expected not to be empty.

idk bro just dmed me saying hes high

2024-10-02 07:41 UTC, nnyyxxxx commented
![image](https://github.com/user-attachments/assets/189ac61b-7125-4822-a18c-753ced3c1419)

2024-10-02 07:43 UTC, lj3954 approved these changes

2024-10-31 18:34 UTC, ChrisTitusTech approved these changes

2024-10-31 18:35 UTC, merged

2024-10-31 18:38 UTC, adamperkowski commented
@nnyyxxxx i meant `tall`, not `high`. sorry.