Mybash dependencies
ChrisTitusTech/linutil pull request #751
Opened 2024-10-03 22:14 UTC by cartercanedy

## Type of Change
- [x] Bug fix

## Description
Corrects the dependency executable tests

## Testing
tested on a fresh of openSUSE Leap 15.6 vm

## Impact
Should make mybash run as intended on fresh installs

## Issues / other PRs related
- Resolves #750 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-10-04 06:20 UTC, nnyyxxxx commented
you're doing so much unnecessary things here

2024-10-04 06:22 UTC, nnyyxxxx commented
there is nothing wrong with the script, not sure what you're trying to accomplish here, every pkg listed there is valid and was in the original mybash-setup script.

![image](https://github.com/user-attachments/assets/4bcbb710-029d-4f09-a476-777237952cf7)

2024-10-04 06:24 UTC, nnyyxxxx commented
```bash
        *)
            "$ESCALATION_TOOL" "$PACKAGER" install -y bash bash-completion tar bat tree unzip fontconfig git
            ;;
```
if this is the issue then expand it out to more packagers && put a pkger not supported in the *)

2024-10-04 06:25 UTC, nnyyxxxx commented
though it really shouldnt be as these are highly known packages, so really there is no issue in the first place. If you could provide any screenshots on the error you encountered that would be great

2024-10-04 06:26 UTC, nnyyxxxx requested changes
revert these changes, command_exists only checks if the first package exists as a command. Also there is no issue with how it is, even if the command does not exist it will still run due to the "!", this PR is pretty redundant.

2024-10-04 06:29 UTC, nnyyxxxx commented
![image](https://github.com/user-attachments/assets/c04e682f-c415-47d0-a50f-2afc2eace70b)
also this makes zero sense, because of the ! even if 1 is installed and none of the rest are installed then it will still begin installation this includes if all are installed as well

2024-10-04 06:29 UTC, nnyyxxxx commented
there is zero issue here, just close this nonsense

2024-10-04 06:36 UTC, nnyyxxxx commented
and in your original issue, you're wrong again because multiple pkg names that are included in command_exists will be ignored, only the 1st pkg will be used for checking. Instead refactor this PR to remove all additional pkgs from the command_exists variable

2024-10-04 06:39 UTC, nnyyxxxx commented
![s](https://github.com/user-attachments/assets/92a34b4b-ac5b-4b26-b2e7-8741767d73dd)


all this PR does is bloat up the deps function

2024-10-04 09:11 UTC, nnyyxxxx commented on core/tabs/applications-setup/mybash-setup.sh
> +    done
```suggestion
installDepend() {
    if ! command_exists bash; then
    printf "%b\n" "${YELLOW}Installing Bash...${RC}"
    case "$PACKAGER" in
        pacman)
            "$ESCALATION_TOOL" "$PACKAGER" -S --needed --noconfirm bash bash-completion tar bat tree unzip fontconfig git
            ;;
        *)
            "$ESCALATION_TOOL" "$PACKAGER" install -y bash bash-completion tar bat tree unzip fontconfig git
            ;;
    esac
    fi
```

2024-10-04 09:15 UTC, nnyyxxxx commented on core/tabs/applications-setup/mybash-setup.sh
> +installDeps
```suggestion
installDepend
```

2024-10-04 15:35 UTC, cartercanedy commented
Have you tried running the command on a fresh headless installation? It fails because there are missing dependencies, particularly fc-cache that comes with fontconfig. Please try the current version deployment on a fresh VM and tell me what happens

2024-10-04 15:48 UTC, cartercanedy commented
> Have you tried running the command on a fresh headless installation? It fails because there are missing dependencies, particularly fc-cache that comes with fontconfig. Please try the current deployment on a fresh headless VM and tell me what happens

2024-10-04 19:46 UTC, cartercanedy commented
for context, here's the issue manifested.
the command fails since it's current implementation inadequately verifies that the dependencies are installed
![image](https://github.com/user-attachments/assets/dcbc0ed5-bcfd-44c6-9df5-c7450487bec6)

2024-10-04 23:49 UTC, nnyyxxxx commented
> for context, here's the issue manifested. the command fails since it's current implementation inadequately verifies that the dependencies are installed ![image](https://private-user-images.githubusercontent.com/99052281/373790060-dcbc0ed5-bcfd-44c6-9df5-c7450487bec6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwODU5ODUsIm5iZiI6MTcyODA4NTY4NSwicGF0aCI6Ii85OTA1MjI4MS8zNzM3OTAwNjAtZGNiYzBlZDUtYmNmZC00NGM2LTlkZjUtYzc0NTA0ODdiZWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDIzNDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkODczNmMyYWE0YjhmYTI0MWYyMWYwZmI0MjYyZjZiNGM3YmQ2ZDlkNDY1YjAxODIyMGViYTNlNDNlODk3ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ooa10bIHcXomcl0FjpcCWcaT4QSKiUSlAfhxtInxmtI)

again, re read what i said, the simple solution to this is to use 1 pkg for detection. All you're doing here is bloating up the deps function.

2024-10-05 00:17 UTC, cartercanedy commented
Your suggestion as implemented would not have resolved the issue

2024-10-05 01:06 UTC, nnyyxxxx commented
> Your suggestion as implemented would not have resolved the issue

yes it would resolve the issue, you're removing all other dependencies, how would a simple installation of one dep not work?

2024-10-05 01:07 UTC, nnyyxxxx commented
> Your suggestion as implemented would not have resolved the issue

explain how it wouldnt resolve the issue?

2024-10-05 01:08 UTC, nnyyxxxx commented
there literally is no issue here, just remove every other dep from the command exists line lmao

2024-10-05 01:10 UTC, nnyyxxxx commented on core/tabs/applications-setup/mybash-setup.sh
> +    done
```suggestion
installDeps() {
    if ! command_exists bash; then
    printf "%b\n" "${YELLOW}Installing Bash...${RC}"
    case "$PACKAGER" in
        pacman)
            "$ESCALATION_TOOL" "$PACKAGER" -S --needed --noconfirm bash bash-completion tar bat tree unzip fontconfig git
            ;;
        *)
            "$ESCALATION_TOOL" "$PACKAGER" install -y bash bash-completion tar bat tree unzip fontconfig git
            ;;
    esac
    fi
```

2024-10-05 01:11 UTC, cartercanedy commented
You've refuse to recreate the environment that I've already been very clear about, and are still choosing to insist on your incorrect understanding of the issue. 

It _**is**_ an issue, this fixes it without additional regressions

2024-10-05 01:13 UTC, nnyyxxxx commented
> You've refuse to recreate the environment that I've already been very clear about, and are still choosing to insist on your incorrect understanding of the issue.
> 
> It _**is**_ an issue, this fixes it without additional regressions

again there is no issue here, what you're doing is bloating up the deps function..

2024-10-05 01:14 UTC, nnyyxxxx commented
there is no need to verify if deps are installed if they are literally getting installed beforehand

2024-10-05 01:15 UTC, nnyyxxxx commented
anyways, i cant even reproduce the issue you're having. The script works perfectly fine for me

2024-10-05 01:15 UTC, cartercanedy commented on core/tabs/applications-setup/mybash-setup.sh
> +    done
To fix my specific issue, you would have to test for `fc-cache`, not `bash`. Each deep needs to be checked for independently. This wouldn't fix the issue, it would pretty much guarantee that the dependency specification is never properly verified or satisfied considering how many distros provide bash out of the box

2024-10-05 01:16 UTC, cartercanedy commented
> anyways, i cant even reproduce the issue you're having. The script works perfectly fine for me

You're being ignorant at this point

2024-10-05 01:18 UTC, nnyyxxxx commented on core/tabs/applications-setup/mybash-setup.sh
> +    done
> To fix my specific issue, you would have to test for `fc-cache`, not `bash`. Each deep needs to be checked for independently. This wouldn't fix the issue, it would pretty much guarantee that the dependency specification is never properly verified or satisfied considering how many distros provide bash out of the box

this does fix the issue. and anyways there literally is NO issue here its clear to me that no testing was involve to encounter such issue and all you're doing is trying to bloat up the deps func

2024-10-05 01:19 UTC, nnyyxxxx commented
> > anyways, i cant even reproduce the issue you're having. The script works perfectly fine for me
> 
> You're being ignorant at this point

again there is no issue here, as i said above i cant reproduce. The fontconfig package is literally getting installed, WHY check for these deps after they are installed?? you are just bloated up the func

2024-10-05 01:23 UTC, cartercanedy commented
It's incredible how hostile you're being right now

2024-10-05 01:30 UTC, nnyyxxxx commented
> It's incredible how hostile you're being right now

no hostility is being expressed, i am asking a question as seen here

> The fontconfig package is literally getting installed, WHY check for these deps after they are installed?? you are just bloating up the func

the capped "why" is to show frustration over you not getting the point i'm trying to make

2024-10-05 01:34 UTC, cartercanedy commented
The point of checking for dependencies is to preserve efficiency. An alternative is to just blindly install the dependencies without writing about checking for deps. The script fails as it's currently written; there's multiple solutions, and I can only implement one. You've repeatedly insisted that there is no issue. If that's your point, then you are either mistaken or intentionally being combative.

2024-10-05 01:37 UTC, nnyyxxxx commented
> The point of checking for dependencies is to preserve efficiency. An alternative is to just blindly install the dependencies without writing about checking for deps. The script fails as it's currently written; there's multiple solutions, and I can only implement one. You've repeatedly insisted that there is no issue. If that's your point, then you are either mistaken or intentionally being combative.

if you are trying to implement dep checking, then why arent you doing this for every script? also as ive said multiple times, if you are installing a set of packages why would they fail? Have you ever been in the process of installing a package and it fails on you? I dont think so... Going by that, there is no issue here, if you're installing fontconfig then fc-cache should work perfectly fine. no need to check for deps all that does is create unnecessary overhead and more time spent on the users end to finish the script

2024-10-05 01:40 UTC, nnyyxxxx commented
also to address the statement above about the command_exists bash, the script is literally installing BASH and is implementing bash configurations, also bash isnt the only shell, and its certainly not one that the user has to keep on their system after installation; alternatives exist: such as Zsh, nushell, fish, and multiple others.

2024-10-05 01:40 UTC, cartercanedy commented
Then make the pr yourself. @ChrisTitusTech can decide whether or not to merge. I'm not going to continue this conversation

2024-10-05 01:44 UTC, cartercanedy commented
As a final note, it's very disheartening to see how you've reacted to this bug report. I've made these changes in good faith, but your deliberately rude are not collaborative I'm the slightest. Your first words in response to my bug report were "you're wrong", and I believe make my point very clear.

2024-10-05 01:47 UTC, nnyyxxxx commented
> As a final note, it's very disheartening to see how you've reacted to this bug report. I've made these changes in good faith, but your deliberately rude are not collaborative I'm the slightest. Your first words in response to my bug report were "you're wrong", and I believe make my point very clear.

i've explained to you many times that i cannot reproduce the issue you're having, i have even gone to the lengths of firing up a VM, and could not reproduce in there either. 

and as said above

> if you are trying to implement dep checking, then why arent you doing this for every script? also as ive said multiple times, if you are installing a set of packages why would they fail? Have you ever been in the process of installing a package and it fails on you? I dont think so... Going by that, there is no issue here, if you're installing fontconfig then fc-cache should work perfectly fine. no need to check for deps all that does is create unnecessary overhead and more time spent on the users end to finish the script

Please answer this i would like to hear your thoughts, it explains what i'm trying to convey very well

2024-10-05 04:21 UTC, cartercanedy commented
I'm not going to walk through every line of code with you. Just evaluating the code statically, it was clear to me what the issue was. I implemented the fix, the issue was resolved in my edge-case environment, and trying the script still in my dev environment still worked, indicating that the program was not correct before, and is correct now. The dependencies were not being installed if not present prior to these changes, and now they are. It is an issue, it is not a "non-existent" issue, as you stated. Read my reproduction steps, it's dead simple to reproduce.

2024-10-05 05:58 UTC, nnyyxxxx commented
> I'm not going to walk through every line of code with you. Just evaluating the code statically, it was clear to me what the issue was. I implemented the fix, the issue was resolved in my edge-case environment, and trying the script still in my dev environment still worked, indicating that the program was not correct before, and is correct now. The dependencies were not being installed if not present prior to these changes, and now they are. It is an issue, it is not a "non-existent" issue, as you stated. Read my reproduction steps, it's dead simple to reproduce.

theres no issue here

2024-10-05 05:58 UTC, nnyyxxxx commented
the script works perfectly fine for me in and out of VM. Can't reproduce this issue at all

2024-10-05 06:11 UTC, lj3954 approved these changes
![image](https://github.com/user-attachments/assets/dc271da0-1e3a-4060-be64-99e8321b6653)

Yes, there is an issue with the previous syntax. And yes, that would cause a problem if the first command (bash) exists (which it nearly certainly will) while any of the others don't.

2024-10-05 06:11 UTC, nnyyxxxx commented
both of these versions are basically doing the same thing

1. previous version installs the deps (and does it correctly as this is in every other script
2. new version installs the deps then checks if those deps are installed

This new version bloats the script up, not sure what your issue is here @cartercanedy and i dont know what you're trying to accomplish by adding this complexity onto the script; as i've said many times the issue you're facing is unreproducable meaning i can NOT reproduce this, in and out of a VM, tested on host (Arch Linux) and in a VM (openSUSE).

This reference
![image](https://github.com/user-attachments/assets/cea6681c-8953-48e6-bf32-baaa08dc5020)
is wrong because of the !, infact it should never fail because the ! makes it so if any of them are missing it will proceed and install and since bash-completion and fontconfig aren't executables it will always run through. Along with this i suggested removing all of the deps from the command_exists function and replacing them with just BASH but of course you declined and that is the: quote me on this "solution to your nonexistent problem" as stated in the images above.

These changes do the following:
1. cause unnecessary overhead
2. accomplish the same thing as the previous version except for dep checking (which is not necessary)
3. potential for more unnecessary maintenance burden

please just close this non-sense, i have gave you a solution and you have declined it (for reasons unknown) this is just disgusting.

2024-10-05 06:14 UTC, nnyyxxxx commented
> ![image](https://private-user-images.githubusercontent.com/33645555/373849991-dc271da0-1e3a-4060-be64-99e8321b6653.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMDkwMDcsIm5iZiI6MTcyODEwODcwNywicGF0aCI6Ii8zMzY0NTU1NS8zNzM4NDk5OTEtZGMyNzFkYTAtMWUzYS00MDYwLWJlNjQtOTllODMyMWI2NjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDA2MTE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ODA1OTA3MmU5MThlMjY1NTM0ZjcxZmYzMzI2MmZiMGFlOGE0MWY1MjdhODFhNzc3YjZhNWMxZjZhZTE5YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.itvOowsBkowc9f7O4iMCgK6-3g8NDhBKjs52wFJQNeg)
> 
> Yes, there is an issue with the previous syntax. And yes, that would cause a problem if the first command (bash) exists (which it nearly certainly will) while any of the others don't.

if that is true then why do all of the other scripts work? many people have ran through them including myself and have encountered 0 issues. Please explain

2024-10-05 06:15 UTC, lj3954 commented
@nnyyxxxx There is a syntax error in the current code. We're passing multiple arguments to a function which only can accept one. If you'd like to propose instead allowing the command_exists function to check through a list of arguments rather than just one (using a loop, much like this), you may. But this is code with a syntax error, and this PR just fixes said error. We don't need this pointless tirade about "performance" and how we "don't need these changes" again, it's ridiculous.

2024-10-05 06:18 UTC, nnyyxxxx commented
> @nnyyxxxx There is a syntax error in the current code. We're passing multiple arguments to a function which only can accept one. If you'd like to propose instead allowing the command_exists function to check through a list of arguments rather than just one (using a loop, much like this), you may. But this is code with a syntax error, and this PR just fixes said error. We don't need this pointless tirade about "performance" and how we "don't need these changes" again, it's ridiculous.
> 
> The script works for you because all of these commands exist on your system. If one didn't exist on someone else's system, we'd have an issue. command_exists does not take in more than one parameter, the function is not being called correctly and all of the commands past the first are being completely disregarded.

as i have said in my previous posts in this thread i **know** that only 1 argument can be passed to command_exists and i have **suggested** the change to simplify it down to just **bash** many times, what hes doing here is completely unnecessary

2024-10-05 06:20 UTC, nnyyxxxx commented
https://github.com/ChrisTitusTech/linutil/pull/751#discussion_r1787417459
https://github.com/ChrisTitusTech/linutil/pull/751#discussion_r1788455751

2024-10-05 06:21 UTC, lj3954 commented
The other programs are also dependencies, correct? "Simplifying" the dependency check to not check for dependencies isn't a solution to anything. We can't expect 'unzip' or 'fontconfig' to be installed just because bash is, those aren't dependencies of bash.

2024-10-05 06:21 UTC, nnyyxxxx commented
![image](https://github.com/user-attachments/assets/7b3e7438-e398-4844-a249-4b192d45ae4e)

2024-10-05 06:22 UTC, nnyyxxxx commented
> The other programs are also dependencies, correct? "Simplifying" the dependency check to not check for dependencies isn't a solution to anything. We can't expect 'unzip' or 'fontconfig' to be installed just because bash is, those aren't dependencies of bash.

except it is a solution when literally **every** other script does it, if we want a solution to the 1 dep checking issue, then we can alter the command_exists function in common-script instead of modifying every script to include this dep checking nonsense

2024-10-05 06:25 UTC, lj3954 commented
If every script is calling a function with the wrong amount of parameters, then they're just all wrong. Indeed, you can suggest instead modifying the command_exists function to allow passing in multiple parameters. But suggesting that you only check for one of the numerous dependencies, or claiming that there's "no issue" because you can't reproduce it yourself, isn't helpful.

2024-10-05 06:31 UTC, nnyyxxxx commented
![image](https://github.com/user-attachments/assets/b78530dc-26c4-4c72-a183-76198f8a5867)

2024-10-05 06:40 UTC, nnyyxxxx commented
https://github.com/ChrisTitusTech/linutil/pull/762

is an easier way to solve this "issue" without having to add dep checks to every script

2024-10-05 18:34 UTC, cartercanedy commented
> both of these versions are basically doing the same thing
> 
> 1. previous version installs the deps (and does it correctly as this is in every other script
> 2. new version installs the deps then checks if those deps are installed
> 
> This new version bloats the script up, not sure what your issue is here @cartercanedy and i dont know what you're trying to accomplish by adding this complexity onto the script; as i've said many times the issue you're facing is unreproducable meaning i can NOT reproduce this, in and out of a VM, tested on host (Arch Linux) and in a VM (openSUSE).
> 
> This reference
> ![image](https://github.com/user-attachments/assets/cea6681c-8953-48e6-bf32-baaa08dc5020)
> is wrong because of the !, infact it should never fail because the ! makes it so if any of them are missing it will proceed and install and since bash-completion and fontconfig aren't executables it will always run through. Along with this i suggested removing all of the deps from the command_exists function and replacing them with just BASH but of course you declined and that is the: quote me on this "solution to your nonexistent problem" as stated in the images above.
> 
> These changes do the following:
> 1. cause unnecessary overhead
> 2. accomplish the same thing as the previous version except for dep checking (which is not necessary)
> 3. potential for more unnecessary maintenance burden
> 
> please just close this non-sense, i have gave you a solution and you have declined it (for reasons unknown) this is just disgusting.

This is probably the best example of a code of conduct violation on your part. If it's not, I don't know what would qualify. You've been hostile to two contributors, myself and @lj3954, which is the only *actually* disgusting behavior on display. @ChrisTitusTech I'd like to hear your opinion on this,

2024-10-05 18:50 UTC, cartercanedy commented
This is also completely omitting any other context. Looking strictly at the course of this conversation, your behavior is completely out of line and totally antithetical to the open source process. Looking at other conversations, though, it's clear that this is a chronic issue

2024-10-06 02:21 UTC, nnyyxxxx commented
just close this, i have provided a better solution to this problem in #762

2024-10-06 02:33 UTC, cartercanedy commented
Closing in favor of #742

2024-10-06 02:33 UTC, closed without merging