refact: remove snaps
ChrisTitusTech/linutil pull request #756
Opened 2024-10-04 10:44 UTC by jeevithakannan2

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Documentation update
- [x] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
- Check if snap is installed before trying to remove snap.
- Merge dnf and zypper packagers as they both have the same commands.

![error](https://github.com/user-attachments/assets/6f475faf-94c5-4032-9d7e-9b9a9a740ece)

![no-error](https://github.com/user-attachments/assets/414a9e46-8a4a-4f9d-9169-289505669134)

## Testing
- Works as expected

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-10-04 10:51 UTC, nnyyxxxx requested changes

2024-10-04 10:51 UTC, nnyyxxxx commented on core/tabs/system-setup/remove-snaps.sh
> +                ;;
```suggestion
    if command_exists snap; then
        case "$PACKAGER" in
            apt-get|nala)
                "$ESCALATION_TOOL" "$PACKAGER" autoremove --purge snapd
                if [ "$ID" = ubuntu ]; then
                    "$ESCALATION_TOOL" apt-mark hold snapd
                fi
                ;;
```

Snapd is not a valid package on arch linux
![image](https://github.com/user-attachments/assets/1487116b-8091-451c-9daf-eed90af45d17)

2024-10-04 10:57 UTC, nnyyxxxx commented on core/tabs/system-setup/remove-snaps.sh
> +        printf "%b\n" "${GREEN}Snap is not installed...${RC}"
```suggestion
        printf "%b\n" "${GREEN}Snapd is not installed...${RC}"
```

2024-10-04 10:58 UTC, jeevithakannan2 commented on core/tabs/system-setup/remove-snaps.sh
> +                ;;
It's a AUR package. AUR packages can be uninstalled using pacman

2024-10-04 11:04 UTC, nnyyxxxx commented on core/tabs/system-setup/remove-snaps.sh
> +                ;;
ah i just noticed that it was in the aur

2024-10-04 17:12 UTC, adamperkowski reviewed
NIT (again)

2024-10-04 17:12 UTC, adamperkowski commented on core/tabs/system-setup/remove-snaps.sh
> +        printf "%b\n" "${GREEN}Snapd is not installed...${RC}"
```suggestion
        printf "%b\n" "${GREEN}Snapd is not installed.${RC}"
```

2024-10-04 17:12 UTC, adamperkowski commented on core/tabs/system-setup/remove-snaps.sh
> +        printf "%b\n" "${GREEN}Successfully removed snaps...${RC}"
```suggestion
        printf "%b\n" "${GREEN}Successfully removed snaps.${RC}"
```

2024-10-05 00:51 UTC, jeevithakannan2 commented
> NIT (again)

Unless the end user thinks there is an error occurred when uninstalling snap when the snap is not even installed

2024-10-08 20:56 UTC, ChrisTitusTech approved these changes

2024-10-08 20:56 UTC, merged