do not exit linutil in confirmation prompt when q is pressed
ChrisTitusTech/linutil pull request #758
Opened 2024-10-04 14:34 UTC by nnyyxxxx

## Type of Change
- [x] Bug fix

https://github.com/user-attachments/assets/e7ee90e5-fa73-4823-a284-597c361d2f25

2024-10-04 17:05 UTC, adamperkowski commented on tui/src/confirmation.rs
> +            Char('n') | Char('N') | Esc | Char('q') | Char('Q') => ConfirmStatus::Abort,
We have to be consistent with this. Here you're doing `Char('q') | Char('Q')` but other modules like `float.rs` or `state.rs` use `Char('q')` only.

2024-10-07 22:47 UTC, adamperkowski requested changes

2024-10-07 22:47 UTC, adamperkowski commented on tui/src/state.rs
>          }
you forgot about `Ctrl-C`

```suggestion
        }
        
        if matches!(self.focus, Focus::ConfirmationPrompt(_))
            && (key.modifiers.contains(KeyModifiers::CONTROL) && key.code == KeyCode::Char('c'))
        {
            return false;
        }
```

2024-10-07 22:55 UTC, adamperkowski commented
cargo fmt seeing ghosts lol. wants to change `{` to `{`

2024-10-07 23:02 UTC, adamperkowski commented
9641e6474c6e73581f9ce9f846e36f9174b56808 Excuse me what do you mean untested? It literally does what it says.
![image](https://github.com/user-attachments/assets/57feb05b-2a72-4a1e-a031-bc73a92810e7)
It's not supposed to close the popup on ctrl-c, it's supposed to exit.

2024-10-07 23:05 UTC, nnyyxxxx commented
> [9641e64](https://github.com/ChrisTitusTech/linutil/commit/9641e6474c6e73581f9ce9f846e36f9174b56808) Excuse me what do you mean untested? It literally does what it says. ![image](https://private-user-images.githubusercontent.com/75480869/374354499-57feb05b-2a72-4a1e-a031-bc73a92810e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNDI1OTAsIm5iZiI6MTcyODM0MjI5MCwicGF0aCI6Ii83NTQ4MDg2OS8zNzQzNTQ0OTktNTdmZWIwNWItMmE3Mi00YTFlLWEwMzEtYmM3M2E5MjgxMGU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDIzMDQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMmQwYzcwNjkyMjYzOGYyZDc1NTZlODYzYjAxOGE5YjExMWZjNGQ2N2JjN2NlYzNiZmY2NmUyZTFmMDdhMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PvMlZ7fyObYfgusUWnLbTqxni-PIQvdme8qVI7MJM1w) It's not supposed to close the popup on ctrl-c, it's supposed to exit.

ah

2024-10-07 23:05 UTC, adamperkowski requested changes

2024-10-07 23:05 UTC, adamperkowski commented on tui/src/state.rs
> +            return true;
![image](https://github.com/user-attachments/assets/d797b59a-bfdb-4e4f-ae70-c1152054103a)

No need for `Ctrl-C` to do the same thing. 

```suggestion
            return false;
```

2024-10-07 23:09 UTC, adamperkowski approved these changes
🍟

2024-10-31 18:49 UTC, ChrisTitusTech approved these changes

2024-10-31 18:49 UTC, merged