fix: bash deps
ChrisTitusTech/linutil pull request #763
Opened 2024-10-05 07:25 UTC by jeevithakannan2

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
- bash-completion and fontconfig are not executables
- This PR depends on #762 

## Testing
- Works as expected

## Issues / other PRs related

- Resolves #750 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-10-05 07:27 UTC, nnyyxxxx requested changes
~~close this~~

2024-10-05 07:28 UTC, nnyyxxxx commented
wait

2024-10-05 07:28 UTC, nnyyxxxx commented on core/tabs/applications-setup/mybash-setup.sh
> +        esac
```suggestion
    if ! command_exists bash tar bat tree unzip git; then
    printf "%b\n" "${YELLOW}Installing Bash...${RC}"
    case "$PACKAGER" in
        pacman)
            "$ESCALATION_TOOL" "$PACKAGER" -S --needed --noconfirm bash bash-completion tar bat tree unzip fontconfig git
            ;;
        *)
            "$ESCALATION_TOOL" "$PACKAGER" install -y bash bash-completion tar bat tree unzip fontconfig git
            ;;
    esac
```

just remove them from command_exists

2024-10-05 07:29 UTC, nnyyxxxx commented on core/tabs/applications-setup/mybash-setup.sh
> +        esac
we shouldnt add unnecessary overhead, this is a much simpler way

2024-10-05 07:32 UTC, jeevithakannan2 commented on core/tabs/applications-setup/mybash-setup.sh
> +        esac
Removing them is incorrect. What if the user already has every other deps installed but not bash-completion ?

2024-10-05 07:33 UTC, jeevithakannan2 commented on core/tabs/applications-setup/mybash-setup.sh
> +        esac
Checking if a file exists does not create extra overhead 🤷🏻‍♂️

2024-10-05 07:34 UTC, nnyyxxxx commented on core/tabs/applications-setup/mybash-setup.sh
> +        esac
mark this as resolved

2024-10-05 07:34 UTC, nnyyxxxx approved these changes

2024-10-05 07:36 UTC, nnyyxxxx commented
tested and works :+1:

2024-10-06 02:37 UTC, cartercanedy approved these changes

2024-10-30 23:03 UTC, adamperkowski approved these changes

2024-10-31 18:06 UTC, ChrisTitusTech approved these changes

2024-10-31 18:06 UTC, merged