📃 fix(zsh-setup): check if `/etc/zsh/zshenv` exists
ChrisTitusTech/linutil pull request #771
Opened 2024-10-05 23:59 UTC by adamperkowski

## Type of Change
- [x] Bug fix

## Description
`tee` fails if the file doesn't exist.

## Issues / other PRs related

- Resolves #770

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-10-06 06:17 UTC, nnyyxxxx requested changes

2024-10-06 06:17 UTC, nnyyxxxx commented on core/tabs/applications-setup/zsh-setup.sh
> +  [ ! -f /etc/zsh/zshenv ] && "$ESCALATION_TOOL" touch /etc/zsh/zshenv
```suggestion
  [ ! -f /etc/zsh/zshenv ] && "$ESCALATION_TOOL" mkdir -p /etc/zsh && touch /etc/zsh/zshenv
```

2024-10-06 06:17 UTC, nnyyxxxx commented on core/tabs/applications-setup/zsh-setup.sh
> +  [ ! -f /etc/zsh/zshenv ] && "$ESCALATION_TOOL" touch /etc/zsh/zshenv
-p flag only creates the dir if it doesn't already exist

2024-10-08 21:40 UTC, ChrisTitusTech approved these changes

2024-10-08 21:40 UTC, merged