Added support for installing podman
ChrisTitusTech/linutil pull request #787
Opened 2024-10-09 11:33 UTC by Albert-LGTM

## Type of Change
- [x] New feature

## Description
I added a new feature to install Podman and Podman Compose in the installation script. 

## Testing
I tested the script on Fedora using `dnf` and Ubuntu with apt and pip3. Podman and Podman Compose were installed and worked as expected.

## Impact
This change allows users to install Podman and Podman Compose for those who wish to use it instead of docker

## Additional Information
podman-compose is only available to the dnf package manger, for other distroes it uses the pip3 package. 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-10-09 11:35 UTC, adamperkowski commented on core/tabs/applications-setup/podman-setup.sh
> +# Function to prompt the user for installation choice
```suggestion
```

2024-10-09 11:36 UTC, adamperkowski commented on core/tabs/applications-setup/podman-setup.sh
> +            "$ESCALATION_TOOL" pip3 install podman-compose
You need to check for pip and python first. And install of course. And I'm pretty sure `pip3 install` would return an error. Installing system-wide packages with pip is not safe. See https://veronneau.org/python-311-pip-and-breaking-system-packages.html

2024-10-09 11:37 UTC, nnyyxxxx requested changes

2024-10-09 11:37 UTC, nnyyxxxx commented on core/tabs/applications-setup/podman-setup.sh
> +# Function to prompt the user for installation choice
please remove this LLM generated comment
```suggestion
```
use of LLMs is prohibited unless the code works and is tested:
https://github.com/ChrisTitusTech/linutil/blob/main/.github/CONTRIBUTING.md

please read the contributing guidelines before opening a pull request

2024-10-09 11:39 UTC, adamperkowski commented
Please **test your changes** before submitting a PR. Read the [Guidelines](https://github.com/ChrisTitusTech/linutil/blob/main/.github/CONTRIBUTING.md).

2024-10-09 11:41 UTC, adamperkowski commented
Also, you need to run `cargo xtask docgen` in the root directory.

2024-10-09 12:05 UTC, Albert-LGTM commented on core/tabs/applications-setup/podman-setup.sh
> +# Function to prompt the user for installation choice
Sorry about that, fixed

2024-10-09 12:10 UTC, Albert-LGTM commented on core/tabs/applications-setup/podman-setup.sh
> +            "$ESCALATION_TOOL" pip3 install podman-compose
I changed it to a user-level installation for Podman Compose with pip3 and updated the PATH variable to include the user's local bin directory in order to use podman-compose installed with pip3. Tested on Ubuntu and Fedora

2024-10-09 12:10 UTC, adamperkowski commented on core/tabs/applications-setup/podman-setup.sh
> +            ;;
Still doesn't solve this:
![image](https://github.com/user-attachments/assets/952aeb8e-c1bf-4d7a-8a53-9eb3a030cddd)
`podman-compose` is available in Arch's `extra` repo. No need to use `pip`.
![image](https://github.com/user-attachments/assets/507bdbf4-bf13-4747-869f-4a0c3c11396a)

2024-10-09 12:13 UTC, adamperkowski commented
`podman-compose` is available as a package in arch/extra ([here](https://archlinux.org/packages/extra/x86_64/podman), [here](https://archlinux.org/packages/extra/any/podman-compose)), debian >= 12 (so also ubuntu) with `apt` and openSUSE >= Leap 15 with `zypper`. Took me one quick web search. Don't use `pip`.

2024-10-10 12:50 UTC, Albert-LGTM commented
I have updated the installation method to use the package manager instead of `pip`. I am sorry for  overlooking the package manager option.

I also wanted to clarify that the LLM comment was derived from the `docker-setup.sh` which my script is based upon.

2024-10-10 12:51 UTC, nnyyxxxx requested changes

2024-10-10 12:51 UTC, nnyyxxxx commented on core/tabs/applications-setup/podman-setup.sh
> +            "$ESCALATION_TOOL" "$PACKAGER" -S --noconfirm podman
```suggestion
            "$ESCALATION_TOOL" "$PACKAGER" -S --noconfirm --needed podman
```

2024-10-10 12:51 UTC, nnyyxxxx commented on core/tabs/applications-setup/podman-setup.sh
> +            "$ESCALATION_TOOL" "$PACKAGER" -S --noconfirm podman-compose
```suggestion
            "$ESCALATION_TOOL" "$PACKAGER" -S --noconfirm --needed podman-compose
```

2024-10-10 12:53 UTC, nnyyxxxx requested changes

2024-10-10 12:53 UTC, nnyyxxxx commented on core/tabs/applications-setup/podman-setup.sh
> +    read -r CHOICE
separate podman and podman-compose into separate scripts, Chris does not like interactive scripts

2024-10-10 12:57 UTC, adamperkowski commented
> I have updated the installation method to use the package manager instead of `pip`. I am sorry for overlooking the package manager option.

No problem.

> I also wanted to clarify that the LLM comment was derived from the `docker-setup.sh` which my script is based upon.

Well, that's unfortunate. I wonder who "wrote" docker setup...... @nnyyxxxx ??

2024-10-10 13:21 UTC, Albert-LGTM commented on core/tabs/applications-setup/podman-setup.sh
> +    read -r CHOICE
Are my latest commits acceptable in resolving this issue?

2024-10-10 13:26 UTC, nnyyxxxx requested changes

2024-10-10 13:26 UTC, nnyyxxxx commented on core/tabs/applications-setup/podman-compose-setup.sh
> +}
```suggestion
installPodmanCompose() {
    if ! command_exists podman-compose; then
        printf "%b\n" "${YELLOW}Installing Podman Compose...${RC}"
        case "$PACKAGER" in
            apt-get|nala)
                "$ESCALATION_TOOL" "$PACKAGER" install -y podman-compose
                ;;
            zypper)
                "$ESCALATION_TOOL" "$PACKAGER" --non-interactive install podman-compose
                ;;
            pacman)
                "$ESCALATION_TOOL" "$PACKAGER" -S --noconfirm --needed podman-compose
                ;;
            dnf)
                "$ESCALATION_TOOL" "$PACKAGER" install -y podman-compose
                ;;
            *)
                printf "%b\n" "${RED}Unsupported package manager: ""$PACKAGER""${RC}"
                exit 1
                ;;
        esac
    else
        printf "%b\n" "${GREEN}Podman Compose is already installed.${RC}"
    fi
}
```

2024-10-10 13:26 UTC, nnyyxxxx commented on core/tabs/applications-setup/podman-compose-setup.sh
> +install_components
```suggestion
install_podman_compose
```

2024-10-10 13:26 UTC, nnyyxxxx commented on core/tabs/applications-setup/podman-setup.sh
> +}
```suggestion
installPodman() {
    if ! command_exists podman; then
        printf "%b\n" "${YELLOW}Installing Podman...${RC}"
        case "$PACKAGER" in
            apt-get|nala)
                "$ESCALATION_TOOL" "$PACKAGER" install -y podman
                ;;
            zypper)
                "$ESCALATION_TOOL" "$PACKAGER" --non-interactive install podman
                ;;
            pacman)
                "$ESCALATION_TOOL" "$PACKAGER" -S --noconfirm --needed podman
                ;;
            dnf)
                "$ESCALATION_TOOL" "$PACKAGER" install -y podman
                ;;
            *)
                printf "%b\n" "${RED}Unsupported package manager: ""$PACKAGER""${RC}"
                exit 1
                ;;
        esac
    else
        printf "%b\n" "${GREEN}Podman is already installed.${RC}"
    fi
}
```

2024-10-10 13:26 UTC, nnyyxxxx commented on core/tabs/applications-setup/podman-setup.sh
> +install_components
```suggestion
install_podman
```

2024-10-10 13:26 UTC, nnyyxxxx commented
click commit on these new suggestions and this Pr should be ready to go! @Albert-LGTM

2024-10-10 13:58 UTC, nnyyxxxx approved these changes

2024-10-20 12:41 UTC, jeevithakannan2 requested changes

2024-10-20 12:41 UTC, jeevithakannan2 commented on core/tabs/applications-setup/podman-compose-setup.sh
> +                printf "%b\n" "${RED}Unsupported package manager: ""$PACKAGER""${RC}"
```suggestion
                printf "%b\n" "${RED}Unsupported package manager: ${PACKAGER}${RC}"
```

2024-10-20 12:41 UTC, jeevithakannan2 commented on core/tabs/applications-setup/podman-setup.sh
> +                printf "%b\n" "${RED}Unsupported package manager: ""$PACKAGER""${RC}"
```suggestion
                printf "%b\n" "${RED}Unsupported package manager: ${PACKAGER}${RC}"
```

2024-10-24 07:26 UTC, adamperkowski approved these changes

2024-11-06 22:03 UTC, merged