feat: Add Arch virtualization setup script
ChrisTitusTech/linutil pull request #813
Opened 2024-10-13 04:24 UTC by jeevithakannan2

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
- Add basic virtualization setup script in ARCH.

## Testing
- Works as expected

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-10-13 04:59 UTC, adamperkowski requested changes
Might be worth adding a quick note about CPU / BIOS virtualization settings

2024-10-13 04:59 UTC, adamperkowski commented on core/tabs/system-setup/arch/virtualization.sh
> +        printf "%b\n" "${RED}KVM is not avaiable please refer https://wiki.archlinux.org/title/KVM for more information.${RC}"
```suggestion
        printf "%b\n" "${RED}KVM is not available. Please refer https://wiki.archlinux.org/title/KVM for more information.${RC}"
```

2024-10-13 05:27 UTC, jeevithakannan2 commented
> Might be worth adding a quick note about CPU / BIOS virtualization settings

That's why I added arch wiki link when kvm is not enabled. Arch Wiki has the details about CPU / BIOS virtualization.

2024-10-13 14:00 UTC, adamperkowski commented
> > Might be worth adding a quick note about CPU / BIOS virtualization settings
> 
> That's why I added arch wiki link when kvm is not enabled. Arch Wiki has the details about CPU / BIOS virtualization.

Yea i know but I'm thinking maybe sometjing more direct like "make sure you have CPU virtualization support enabled in your BIOS/UEFI settings"

2024-10-14 16:02 UTC, lj3954 commented on core/tabs/system-setup/arch/virtualization.sh
> +    if [ -z "$hardware_avail" ] || [ -z "$modules_avail" ] || { [ "$kernel_avail" != "m" ] && [ "$kernel_avail" != "y" ]; }; then
```suggestion
    if [ ! -e "/dev/kvm" }; then
```

We don't need to check all this nonsense. /dev/kvm will not exist if virtualization is disabled or KVM is otherwise unsupported.

2024-10-14 17:50 UTC, lj3954 approved these changes

2024-11-07 19:01 UTC, ChrisTitusTech approved these changes

2024-11-07 19:01 UTC, merged