Add OpenSUSE to list of linutil added to package managers
ChrisTitusTech/linutil pull request #820
Opened 2024-10-13 13:00 UTC by solomoncyj

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [*] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description

built linutil for OpenSUSE in my [Home proj](https://build.opensuse.org/package/show/home:solomoncyj/linutil)
Now waiting for pr to Devel and Factory to be accepted

## Testing

## Impact

## Issues / other PRs related

- Resolves #

## Additional Information

## Checklist
- [ ] My code adheres to the coding and style guidelines of the project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no errors/warnings/merge conflicts.

2024-10-14 12:07 UTC, adamperkowski approved these changes
Thanks

2024-10-14 12:07 UTC, adamperkowski commented on README.md
> +[![build result](https://build.opensuse.org/projects/home:solomoncyj/packages/linutil/badge.svg?type=percent)](https://build.opensuse.org/package/show/home:solomoncyj/linutil)
This doesn't need to be here because repology will eventually update. But ok.

2024-10-14 14:10 UTC, solomoncyj commented
> Did you include the desktop file and the manpage in your package? Oh and could you please update the `linutil-installer` script too?

the latest manpage commits will not appear until a new release is cut. will add the install script. any good way to know if the system is on slowroll or tumblweed?

2024-10-14 14:15 UTC, adamperkowski commented
> the latest manpage commits will not appear until a new release is cut.

in situations like this, i usually do a new pkgrel with the manpage being downloaded separately and then update it on the next release. check out [this commit](https://aur.archlinux.org/cgit/aur.git/commit/?h=linutil&id=cd162c2fe33743b0bd4885d9bcb29936b45ab1cf)

2024-10-15 16:10 UTC, nnyyxxxx commented on core/tabs/applications-setup/linutil-installer.sh
> +            ;;
What is this nonsense? first off you're using bashisms [[]] second off you're also using hardcoded packages, and on top of all of that why are you adding your own repo !! please close this, i'm not sure what you're trying to accomplish here, too many issues with this section

![image](https://github.com/user-attachments/assets/83c49543-ea6e-43c4-8d40-fb1def723b94)

2024-10-15 23:54 UTC, solomoncyj commented on core/tabs/applications-setup/linutil-installer.sh
> +            ;;
i did say that i was waiting to get this shipped to the factory right

2024-10-15 23:56 UTC, nnyyxxxx commented on core/tabs/applications-setup/linutil-installer.sh
> +            ;;
> i did say that i was waiting to get this shipped to the factory right

regardless this isn't going to get accepted

2024-10-16 00:39 UTC, ormaaj commented on core/tabs/applications-setup/linutil-installer.sh
> +            flavor = zypper lr | grep -i "Tumbleweed" && echo "Tumbleweed" || echo "Slowroll"
This will try to run a command named `flavor`. Not likely what's intended. `flavor=zypper lr` asssuming `lr` is a command or function and the goal is to export to it.

`grep` should use `-q` unless you want it to write to stdout.

`x && y || z` is not generally a valid substitute for `if...then...else`, even if it happens to work in this instance.

2024-10-16 00:41 UTC, ormaaj commented on core/tabs/applications-setup/linutil-installer.sh
> +            if [$flavor == "Tumbleweed"]
```
[[ $flavor == Tumbleweed ]]
```
or
```
[ "$flavor" = Tumbleweed ]
```

2024-10-16 00:43 UTC, ormaaj commented on core/tabs/applications-setup/linutil-installer.sh
> +                  "$ESCALATION_TOOL" "$PACKAGER" addrepo https://download.opensuse.org/repositories/home:solomoncyj/openSUSE_Tumbleweed/home:solomoncyj.repo
```
"$ESCALLATION_TOOL" -- "$PACKAGER" addrepo 'https://download.opensuse.org/repositories/home:solomoncyj/openSUSE_Tumbleweed/home:solomoncyj.repo'
```

2024-10-16 00:47 UTC, ormaaj commented on core/tabs/applications-setup/linutil-installer.sh
> +            printf "%b\n" " flavor detected is ${GREEN} ${flavor} ${RC}"
```
printf '%b%s%b\n' "flavor detected is ${GREEN}" "$flavor" "$RC"
```

2024-10-16 00:48 UTC, ormaaj commented on core/tabs/applications-setup/linutil-installer.sh
> +            printf "%b\n" "refreshing and installing"
```
printf '%s\n' 'refreshing and installing'
```
`%b` is for interpreting escape sequences. Use `%s` for string literals and avoid `%b` with dynamic data.

2024-10-16 01:06 UTC, ormaaj commented on core/tabs/applications-setup/linutil-installer.sh
> +            if [ $flavor == "Tumbleweed" ]
`[` must use single `=` according to posix. Bash allows `==` as an extension but it should be avoided

The quoting is backwards. It should be _exactly_ `[ "$flavor" = Tumbleweed ]`. Quotes are only not required on the LHS of a comparison if `[[` is used.

2024-10-16 01:12 UTC, ormaaj commented on core/tabs/applications-setup/linutil-installer.sh
> +            [ zypper lr | grep -q "Tumbleweed" ] && flavor="Tumbleweed" || flavor="Slowroll"
```
if zypper lr | grep -Fq Tumbleweed
then flavor=Tumbleweed
else flavor=Slowroll
fi
```

2024-10-16 02:36 UTC, cartercanedy requested changes

2024-10-16 02:36 UTC, cartercanedy commented on core/tabs/applications-setup/linutil-installer.sh
> +            fi
```sh
case "$flavor" in
    Tumbleweed)
        # ...
        ;;
    Slowroll)
        # ...
        ;;
esac
```

2024-10-16 19:24 UTC, ormaaj commented on core/tabs/applications-setup/linutil-installer.sh
Better! \o/

2024-10-17 21:38 UTC, cartercanedy commented on core/tabs/applications-setup/linutil-installer.sh
> +            fi
Does that have a bearing on this?

2024-10-17 21:53 UTC, solomoncyj commented on core/tabs/applications-setup/linutil-installer.sh
> +            fi
If it gets accepted, i do not need all the stuff to add a new repo anymore.

2024-10-20 13:53 UTC, adamperkowski commented on README.md
> +  ###just run:
```suggestion
Linutil can be installed on OpenSUSE with:
```

2024-10-20 13:56 UTC, adamperkowski requested changes

2024-10-20 13:56 UTC, adamperkowski commented on README.md
> +  ###just run:
```suggestion
Linutil can be installed on OpenSUSE with:
```

2024-10-20 13:56 UTC, adamperkowski commented on README.md
> +</details>
````suggestion
```bash
sudo zypper install linutil
```

</details>
````

2024-10-20 16:15 UTC, adamperkowski approved these changes

2024-10-20 16:20 UTC, jeevithakannan2 reviewed
Also remove the zypper case from installing the crates.io package

2024-10-20 16:20 UTC, jeevithakannan2 commented on core/tabs/applications-setup/linutil-installer.sh
> +            printf "%b\n" "${GREEN}Installed successfully.${RC}"
```suggestion
                "$ESCALATION_TOOL" "$PACKAGER" install linutil
                printf "%b\n" "${GREEN}Installed successfully.${RC}"
```

2024-10-20 16:22 UTC, jeevithakannan2 commented on core/tabs/applications-setup/linutil-installer.sh
> +            zypper)
```suggestion
        zypper)
```

2024-10-21 00:56 UTC, jeevithakannan2 approved these changes

2024-10-23 13:51 UTC, adamperkowski commented on README.md
> +[![build result](https://build.opensuse.org/projects/openSUSE:Factory/packages/linutil/badge.svg?type=percent)](https://build.opensuse.org/package/show/openSUSE:Factory/linutil)
Maybe we shouldn't add this. Repology already updated.
![image](https://github.com/user-attachments/assets/761ca138-de35-4948-83a3-90d80df8c491)

2024-11-07 19:07 UTC, merged