Add root check
ChrisTitusTech/linutil pull request #821
Opened 2024-10-13 13:24 UTC by jeevithakannan2

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [x] Hotfix
- [x] Security patch
- [ ] UI/UX improvement

## Description
- Add root check and exit when running as root
- Uses `sudo` crate

![image](https://github.com/user-attachments/assets/6947474e-7f0f-48ba-bce1-ec506d038656)

## Testing
- No issues

## Impact
- Cannot be run as root. Might cause issues when running in a docker container.

## Issues / other PRs related
- Resolves #816 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-10-13 13:32 UTC, solomoncyj commented
what if i am in container system such as docker/podman? they do not drop me as a normal user with dmin rights. they just drop the user in as the root acc.

2024-10-13 13:33 UTC, solomoncyj commented
just look for `.dockerenv` in /

2024-10-13 13:44 UTC, jeevithakannan2 commented
> just look for `.dockerenv` in /

Not only docker env runs as root. Normal user may invoke linutil as root

2024-10-13 13:53 UTC, solomoncyj commented
> > just look for `.dockerenv` in /
> 
> Not only docker env runs as root. Normal user may invoke linutil as root

this allows the user run the script to run it in docker/podman/ andy other container system. this is because users do not usally create users in containers, and insted default to the root user pre-created. we just need to tewak the scripts to allow the scripts to skip elevation checks if the user is root

2024-10-13 14:21 UTC, jeevithakannan2 commented
> > > just look for `.dockerenv` in /
> > 
> > 
> > Not only docker env runs as root. Normal user may invoke linutil as root
> 
> this allows the user run the script to run it in docker/podman/ andy other container system. this is because users do not usally create users in containers, and insted default to the root user pre-created. we just need to tweak the scripts to allow the scripts to skip elevation checks if the user is root

Running scripts as root may break many things. For example configuration files should not be in root permission. An application or non-root user may not be able to rw the configuration file due to insufficient permissions. And why would someone try to run linutil in a docker container ??

2024-10-13 15:21 UTC, solomoncyj commented
I need to set up the bash scripts as I can't stand the default one

2024-10-13 20:44 UTC, cartercanedy commented
@jeevithakannan2 instead of precluding the use, it might be worth implementing a root warning and doing a refactor to just leave `ESCALATION_TOOL` unset when run as root. Configuration files *should* written relative to $HOME, which would be inaccessible to other users anyways, and software is almost exclusively, if not completely, handled by package managers, so there shouldn't be any permission issues there. If there *are* any game-breaking conflicts, I'll eat my words, but I don't think that we need to put that tight of a restriction.

2024-10-13 20:50 UTC, cartercanedy commented
> just look for `.dockerenv` in /

I don't like this. Running a ubuntu docker container should generally the same as running as root in a bare-metal ubuntu install, unless you're running a crazy stripped-down image. There are better solutions to make this workable for this kind of use-case

2024-10-14 00:43 UTC, jeevithakannan2 commented
> @jeevithakannan2 instead of precluding the use, it might be worth implementing a root warning and doing a refactor to just leave `ESCALATION_TOOL` unset when run as root. Configuration files *should* written relative to $HOME, which would be inaccessible to other users anyways, and software is almost exclusively, if not completely, handled by package managers, so there shouldn't be any permission issues there. If there *are* any game-breaking conflicts, I'll eat my words, but I don't think that we need to put that tight of a restriction.

Ok will go through this one more time. If root is disabled arch server setup cannot be run. I think I should do it in the scripts then

2024-10-14 03:41 UTC, cartercanedy commented
Also, I made a PR on your dev branch that implements a warning prompt notifying users that they are running as root. Since we're not really testing these scripts with standard user perms, it's probably best to notify users that they are outside the bounds of the current user story

2024-10-14 03:52 UTC, cartercanedy commented
I also would remove the cli flag since most users are probably going to be using the network runner

2024-10-14 04:01 UTC, jeevithakannan2 commented
> Also, I made a PR ([jeevithakannan2#1](https://github.com/jeevithakannan2/linutil/pull/1)) on your dev branch that implements a warning prompt notifying users that they are running as root. Since we're not really testing these scripts with standard user perms, it's probably best to notify users that they are outside the bounds of the current user story

Can't we just add a flag

> I also would remove the cli flag since most users are probably going to be using the network runner

Yeah removed it thanks for the PR

2024-10-14 11:59 UTC, adamperkowski requested changes
I think this implementation is wrong and overengineered. We can just check the UID or even file permissions. This will only slow linutil down.

2024-10-14 12:01 UTC, cartercanedy commented
> This will only slow linutil down

?

2024-10-14 12:05 UTC, adamperkowski commented
> > This will only slow linutil down
> 
> ?

This PR is adding another rust dependency, more checks and code that has to be maintained. I just think this can be easily avoided with a more efficient approach.

2024-10-14 12:32 UTC, cartercanedy commented
To get the inlined superuser check functional would need even more code to maintain, and it would be hard to beat 8 lines of bash except by just unquoting all references to`ESCALATION_TOOL` and not bothering with an additional function

2024-10-14 12:34 UTC, cartercanedy commented
Tbh, I think unquoting would be the simplest @jeevithakannan2

2024-10-14 12:40 UTC, jeevithakannan2 commented
Mmm 🤔

2024-10-14 12:41 UTC, adamperkowski commented
@cartercanedy To be 100% honest, I love this idea
BUT
depending on a crate that hasn't been updated in 3-4 years for **privilage-escalation** related stuff is just not a good idea.
![image](https://github.com/user-attachments/assets/691818c9-9529-420f-95cf-688660ac990c)

2024-10-14 12:43 UTC, adamperkowski commented
> Getting the inlined superuser check functional would need even more code to maintain, and it would be hard to beat 8 lines of bash except by just unquoting all references to`ESCALATION_TOOL` and not bothering with an additional function

I'm talking about Rust code.

2024-10-14 12:45 UTC, adamperkowski requested changes

2024-10-14 12:45 UTC, adamperkowski commented on core/tabs/common-script.sh
> +        printf "%b\n" "${CYAN}Running as root, no need for escalation tool.${RC}"
```suggestion
    if [ "$(id -u)" -eq 0 ]; then
        printf "%b\n" "${CYAN}Running as root. Skipping escalation tool check.${RC}"
```

2024-10-14 12:45 UTC, adamperkowski commented on tui/src/root.rs
> +You have been warned!
i think we have enough exclamation points

```suggestion
You have been warned.
```

2024-10-14 12:45 UTC, adamperkowski commented on core/tabs/applications-setup/Developer-tools/ngrok-setup.sh
> +        fi
No need for this check. The script will stop when any command (including `curl`) fails because of `sh -e`.

2024-10-14 12:49 UTC, cartercanedy commented on tui/src/root.rs
> +You have been warned!
Lmao

2024-10-14 12:52 UTC, jeevithakannan2 commented
So I undo the changes and not use a crate. If yes I have solution for that too !!

2024-10-14 12:52 UTC, cartercanedy commented
> depending on a crate that hasn't been updated in 3-4 years for **privilege-escalation** related stuff is just not a good idea.

Fair point

2024-10-14 12:52 UTC, jeevithakannan2 commented
We can check the USER env right for running as root ?

2024-10-14 12:55 UTC, jeevithakannan2 commented on core/tabs/applications-setup/Developer-tools/ngrok-setup.sh
> +        fi
The if condition is not necessary but piping was causing issues so I split the command

2024-10-14 13:01 UTC, adamperkowski commented
@jeevithakannan2 You can use Rust's `libc` to check current UID.

2024-10-14 13:02 UTC, jeevithakannan2 commented
> `libc`

Yeah thought of that. It needs unsafe that's why I leaned toward crate

2024-10-14 13:03 UTC, adamperkowski commented
Yeah we currently 0% of Linutil's codebase is unsafe. Would be sad to loose that.

2024-10-14 13:06 UTC, adamperkowski commented
What about `nix::unistd`?

2024-10-14 13:12 UTC, cartercanedy commented
> How about `nix::unistd`?

That seems like the best safe option

2024-10-14 13:24 UTC, jeevithakannan2 commented
Yeah agreed

2024-10-14 13:25 UTC, jeevithakannan2 commented
What about the scripts ??

2024-10-14 13:29 UTC, adamperkowski commented
> What about the scripts ??

scripts are fine

2024-10-14 13:30 UTC, adamperkowski commented on core/tabs/applications-setup/Developer-tools/ngrok-setup.sh
> +        fi
okay

2024-10-14 13:30 UTC, jeevithakannan2 commented
> > What about the scripts ??
> 
> scripts are fine

We can just unquote the ESCALATION_TOOL instead of creating a new function

2024-10-14 14:33 UTC, jeevithakannan2 commented on tui/src/root.rs
> +You have been warned!
Exclamation looks good

2024-10-14 15:53 UTC, lj3954 commented
I'm not sure what all this discussion is, it's already been decided that we're going to adapt the scripts to work on root (as as been done in the recent commits here) rather than prohibiting linutil from launching as root. Please drop https://github.com/ChrisTitusTech/linutil/pull/821/commits/c997a3d89e6908a6fb76d15da03ee43a6ed4fdda. 

By the way, @adamperkowski, both crates mentioned here, nix and this unmaintained sudo crate use libc::getuid() anyways. I think it's a poor idea to religiously avoid writing a line of unsafe code, just to pick up another dependency which calls quite literally the exact same function. That does the opposite of improving security.

2024-10-14 15:59 UTC, adamperkowski commented
> By the way, @adamperkowski, both crates mentioned here, nix and this unmaintained sudo crate use libc::getuid() anyways. I think it's a poor idea to religiously avoid writing a line of unsafe code, just to pick up another dependency which calls quite literally the exact same function. That does the opposite of improving security.

I am aware that they do use `libc::getuid` but by not including unsafe code blocks in our code directly we at least know that future PRs / other stuff like that will be relatively safe and have an overall lower chance of causing something like memory leaks, overflows, etc. It is 100% possible that (for example) `libc` gets updated in the future and using `getuid` directly could cause issues. Using `nix::unistd` solves this issue. (assuming that `nix` would be regularly updated)

2024-10-14 17:33 UTC, cartercanedy commented
We should use a `#![forbid(unsafe_code)]` top-level directive to enforce safety then

2024-10-15 14:58 UTC, adamperkowski approved these changes

2024-10-15 17:37 UTC, cartercanedy approved these changes

2024-10-26 02:43 UTC, lj3954 approved these changes

2024-11-01 17:41 UTC, jeevithakannan2 commented
@ChrisTitusTech All the scripts have shellcheck warning and formatting issues that need to be resolve in a separate PR. This PR has no issues.

2024-11-06 00:59 UTC, closed without merging

2024-11-06 06:20 UTC, adamperkowski commented
?

2024-11-06 06:30 UTC, cartercanedy commented
> ?

I was just about to say...