feat: Drastically increase the operating system support for USB creation script
ChrisTitusTech/linutil pull request #828
Opened 2024-10-15 00:56 UTC by lj3954

## Type of Change
- [x] New feature

## Description
Remove inbuilt logic for finding debian & arch ISO URLs from the USB creation script. Instead, if the user selects the online ISO option, download JSON data containing the necessary information from a project I started and brought into the quickemu project, [quickget_configs](https://github.com/quickemu-project/quickget_configs). This project was created to eventually be used to fully replace functionality in the quickget bash script, similar to that present in this script. Thus, it provides the data necessary to download images of various operating systems. The data is produced daily in CI, where invalid or unresolvable URLs (and their accompanying entries) are thrown out, and other useful information, like SHA256 checksums to verify validity, are included. 

jq is used to filter through this JSON data, and ensure that we're only taking entries with 1 ISO file and nothing else.  The user is prompted for the Architecture, OS, Release, and Edition (if necessary), and the ISO is downloaded, verified, and unarchived as applicable.  This change will additionally reduce the maintenance burden on this script, since the logic to find URLs is contained within a different project.

https://github.com/user-attachments/assets/132f27af-28a9-4c1b-9cba-71cba7cdd5ca

## Impact
jq is added as a dependency, along with a few archiving tools (xz, bzip2, gzip).

## Issues / other PRs related

- Functionality supersedes that in #699. 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-10-15 01:25 UTC, lj3954 commented
Older jq versions appear to break in many cases here. Working to resolve it

2024-10-15 02:19 UTC, nnyyxxxx approved these changes
nice changes

2024-10-15 02:20 UTC, nnyyxxxx requested changes

2024-10-15 02:20 UTC, nnyyxxxx commented on core/tabs/utils/create-bootable-usb.sh
> +# Function to fetch ISO URLs
```suggestion
```
this comment is unnecessary

2024-10-15 02:21 UTC, nnyyxxxx commented on core/tabs/utils/create-bootable-usb.sh
> +# Function to fetch ISO URLs
```bash
get_online_iso() {
    get_architecture
    printf "%b\n" "${YELLOW}Fetching available operating systems...${RC}"
```
the purpose is described perfectly here

2024-10-15 02:26 UTC, lj3954 commented on core/tabs/utils/create-bootable-usb.sh
> +# Function to fetch ISO URLs
Indeed. That comment was there prior to my changes, git just tagged it as a line removed & added.

2024-10-15 02:28 UTC, nnyyxxxx requested changes

2024-10-15 02:28 UTC, nnyyxxxx commented on core/tabs/utils/create-bootable-usb.sh
> +CONFIGURATION_URL="https://github.com/quickemu-project/quickget_configs/releases/download/daily/quickget_data.json"
can we not externally link projects that could **potentially** be **dangerous**, this is a risk i'm not sure Chris would like to take, maybe we should host this in this repository so it can be monitored.

2024-10-15 04:45 UTC, lj3954 commented on core/tabs/utils/create-bootable-usb.sh
> +CONFIGURATION_URL="https://github.com/quickemu-project/quickget_configs/releases/download/daily/quickget_data.json"
Please read the body of my PR. That is quite literally the entire proposal of the PR. The project that is being relied upon here is extremely trustworthy. The Quickemu project was created by Martin Wimpress, who is an extremely trusted member of the community. He's a former Canonical employee and long term lead of Ubuntu MATE. In fact, Chris has used and showcased quickemu's bash scripts & flutter GUI in the past (https://www.youtube.com/watch?v=87MCT3Ekjlo). 

The quickget_configs tool, in specific, was created by me. I had several discussions with other contributors to the quickemu project along with the lead, and the idea of creating a tool which generates all the data necessary to create a QEMU virtual machine, including URLs to download image files, in CI was brought up. I worked on it for a bit alongside my re-implementations of the project's 2 main tools, and then relinquished my ownership of the project to Martin's quickemu project. Once again, it's in very safe hands. The project will not be hosted in this repository, for reasons that should already be spelled out well enough.

It's also worth looking at what a potential attack on the project could even affect. Someone would have to insert a mirror providing malicious images into the logic for creating configurations to download one operating system. There should and will be high scrutiny on unrecognized URLs in future contributions to the project, and the reward for the attacker for carrying out such a complicated attack would be miniscule (it would only affect people who chose to download that one specific operating system, nearly exclusively for virtual machines). If we are to be worried about a security risk, a MITM attack (which this change would protect against, due to the checksums being fetched in CI) or a legitimate mirror being compromised are **far** more likely threats.

2024-10-15 05:10 UTC, nnyyxxxx approved these changes

2024-10-17 15:09 UTC, adamperkowski commented on core/tabs/utils/create-bootable-usb.sh
> +    echo "${OS_JSON}" | jq -r '.releases[].release' | sort -Vur | tr '\n' ' '
```suggestion
    echo "${OS_JSON}" | jq -r '.releases[].release' | sort -Vur | tr '\n' ';'
```

2024-10-17 15:09 UTC, adamperkowski commented on core/tabs/utils/create-bootable-usb.sh
> +    echo "${OS_JSON}" | jq -r '.[].name' | tr '\n' ' '
```suggestion
    echo "${OS_JSON}" | jq -r '.[].name' | tr '\n' ';'
```

2024-10-25 14:29 UTC, adamperkowski approved these changes

2024-10-31 17:57 UTC, ChrisTitusTech approved these changes

2024-10-31 17:58 UTC, merged