Add greeter install for lightdm during dwm-titus setup
ChrisTitusTech/linutil pull request #831
Opened 2024-10-15 09:14 UTC by fortifyde

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
After fresh Arch-Server install, using Linutil to install and configure dwm-titus, a display manager must be chosen. When choosing lightdm, a greeter is required without autologin configured. This adds the most common greeter `lightdm-gtk-greeter` to the install in case lightdm is chosen as a DM.

## Testing
Tested for fresh Arch-Server install using Linutil. Boots cleanly into login screen after dwm-titus setup.

## Impact
Fixes dwmtitus-setup.sh for lightdm choice

## Issues / other PRs related
- Resolves #829 

## Additional Information
none

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no errors/warnings/merge conflicts.

2024-10-20 12:29 UTC, jeevithakannan2 requested changes
Can you add gtk-greeter for other distros as well

`apt-get|nala` -> `lightdm-gtk-greeter`
`dnf` -> `lightdm-gtk`
`zypper` -> `lightdm-gtk-greeter`

2024-10-22 16:00 UTC, fortifyde commented
Checked other distros and they all require a greeter as a dependency. No changes necessary.

## Debian:
![greeter_deb](https://github.com/user-attachments/assets/d16f8545-b739-4e2a-9df7-537f4f5f9565)

## Fedora 40:
![greeter_fed40](https://github.com/user-attachments/assets/a1ebd324-d8e0-4e66-ba15-068df3559d5c)

## OpenSuse Tumbleweed:
![greeter_suse](https://github.com/user-attachments/assets/d7fa4aeb-7163-480d-a59f-f06ed45f9639)

2024-10-22 16:11 UTC, jeevithakannan2 commented
Okay thanks for the reply !

2024-10-22 16:11 UTC, jeevithakannan2 approved these changes

2024-10-25 14:31 UTC, adamperkowski requested changes

2024-10-25 14:31 UTC, adamperkowski commented on core/tabs/applications-setup/dwmtitus-setup.sh
> +                    "$ESCALATION_TOOL" "$PACKAGER" -S --needed --noconfirm lightdm-gtk-greeter # greeter is required for lightdm to start without autologin enabled
```suggestion
                    "$ESCALATION_TOOL" "$PACKAGER" -S --needed --noconfirm lightdm-gtk-greeter
```

2024-10-25 14:43 UTC, adamperkowski approved these changes
Thanks

2024-11-05 19:58 UTC, ChrisTitusTech approved these changes

2024-11-05 19:58 UTC, merged