Linutil arguments when using `curl`
ChrisTitusTech/linutil pull request #835
Opened 2024-10-15 18:11 UTC by jeevithakannan2

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [x] Documentation update
- [ ] Refactoring
- [x] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
- Use `linutil` arguments when using `curl`

## Testing
- Works

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-10-30 23:10 UTC, adamperkowski requested changes

2024-10-30 23:10 UTC, adamperkowski commented on README.md
> +  <summary>Usage of Arguments</summary>
```suggestion
  <summary>CLI arguments</summary>
```

2024-10-30 23:56 UTC, adamperkowski reviewed
thanks

2024-10-30 23:57 UTC, adamperkowski approved these changes
thanks

2024-11-07 19:17 UTC, ChrisTitusTech approved these changes

2024-11-07 19:18 UTC, merged