Add Epson inkjet printer driver installation and printer category under Utilities
ChrisTitusTech/linutil pull request #837
Opened 2024-10-15 22:14 UTC by Vorthas

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
Came to mind to add this when I was struggling to get my Epson printer working earlier today on my new computer.  Turns out I forgot to install the Epson printer drivers in the AUR.  I did a search and the same package is in the Debian and Fedora repos so I added support for those, but I'm not really able to test them myself as I only use EndeavourOS.  I can comment those out in the shell script if needed.

## Testing
Ran the script and verified it installed (or reinstalled in my case) the correct drivers and saw them show up in CUPS when I brought up the CUPS web interface.

## Impact
Printer driver installation on Linux (and on Windows for that matter) is a real pain to get right sometimes, I'm hoping this will help people out who use Epson printers.

## Issues / other PRs related
N/A

## Additional Information
As I mentioned in description, I only really tested this on an Arch-based distro.  May need some help testing this on a Debian- or Fedora-based distro.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-10-16 01:55 UTC, cartercanedy approved these changes

2024-10-20 12:19 UTC, jeevithakannan2 requested changes

2024-10-20 12:19 UTC, jeevithakannan2 commented on core/tabs/utils/printers/install-epson-printer-drivers.sh
> +    *) ;;
```suggestion
        pacman)
            "$AUR_HELPER" -S --noconfirm epson-inkjet-printer-escpr
            ;;
        apt-get|nala)
            "$ESCALATION_TOOL" "$PACKAGER" install -y printer-driver-escpr
            ;;
        dnf)
            "$ESCALATION_TOOL" "$PACKAGER" install -y epson-inkjet-printer-escpr
            ;;
        *)
            printf "%b\n" "${RED}Unsupported package manager ${PACKAGER}${RC}"
            exit 1
            ;;
```

2024-10-20 12:19 UTC, jeevithakannan2 commented on core/tabs/utils/printers/install-epson-printer-drivers.sh
> +    *) ;;
- No need for `{}` let's keep the consistency among scripts. 
- Add unsupported packager manager with `exit 1`
- And formatting

2024-10-21 19:31 UTC, Vorthas commented on core/tabs/utils/printers/install-epson-printer-drivers.sh
> +    *) ;;
Thanks, gonna make these changes in a couple minutes.  Formatting might've gotten off with my editor, will have to look into that.

2024-10-25 18:24 UTC, adamperkowski commented
> Think CUPS installation should be done in a separate script that this script calls?

Yeah would be a good idea to have `cups.sh`

2024-10-30 23:12 UTC, adamperkowski requested changes

2024-10-30 23:12 UTC, adamperkowski commented on core/tabs/utils/printers/install-cups.sh
> +# Function to install CUPS for printers
Seriously?
![image](https://github.com/user-attachments/assets/8ede1223-0cdd-4c0d-8ec1-cc0631b4ce76)

```suggestion
```

2024-10-30 23:12 UTC, adamperkowski commented on core/tabs/utils/printers/install-epson-printer-drivers.sh
> +# Function to install drivers for Epson printers
```suggestion
```

2024-10-30 23:12 UTC, adamperkowski commented on core/tabs/utils/tab_data.toml
> +name = "Install CUPS"
```suggestion
name = "CUPS"
```

2024-10-30 23:12 UTC, adamperkowski commented on core/tabs/utils/tab_data.toml
> +name = "Install Epson printer drivers"
```suggestion
name = "Epson printer drivers"
```

2024-10-31 12:52 UTC, adamperkowski approved these changes

2024-11-07 19:23 UTC, ChrisTitusTech approved these changes

2024-11-07 19:23 UTC, merged