feat(whatsapp): add whatsapp desktop client for linux
ChrisTitusTech/linutil pull request #838
Opened 2024-10-16 04:56 UTC by harshv5094

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
[ZapZap](https://github.com/rtosta/zapzap) is an open source `WhatsApp` desktop client. This script allows to install ZapZap in your system

## Testing
For arch, I've tested on my own system. In case of other distro's, I've set Flatpak as default option.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-10-16 05:25 UTC, lj3954 commented
Perhaps it would be better to call the entry 'ZapZap', with the description specifying that it's a client for WhatsApp.

2024-10-20 12:13 UTC, jeevithakannan2 requested changes

2024-10-20 12:13 UTC, jeevithakannan2 commented on core/tabs/applications-setup/communication-apps/whatsapp-setup.sh
> +}
```suggestion
  if ! command_exists com.rtosta.zapzap && ! command_exists zapzap; then
    printf "%b\n" "${YELLOW}Installing Whatsapp(Zap-Zap by rtosta)${RC}"
    case "$PACKAGER" in
      pacman)
        "$AUR_HELPER" -S --needed --noconfirm zapzap
        ;;
      *)
        . ../setup-flatpak.sh
        flatpak install flathub com.rtosta.zapzap
        ;;
    esac
  else
    printf "%b\n" "${GREEN}WhatsApp(Zap-Zap by rtosta) is already installed.${RC}"
  fi
}
```

2024-10-20 12:30 UTC, jeevithakannan2 approved these changes

2024-10-20 15:22 UTC, jeevithakannan2 commented
Try to keep consistency with other scripts. This is not a big deal but linutil uses 4 space or tabs instead of 2 spaces.

2024-10-20 15:23 UTC, jeevithakannan2 approved these changes

2024-10-21 02:18 UTC, harshv5094 commented
> Try to keep consistency with other scripts. This is not a big deal but linutil uses 4 space or tab instead of 2 spaces.
Okay, I think it has to do with my lazyvim. I'll make sure this won't happen again

2024-10-25 14:39 UTC, adamperkowski commented
> Perhaps it would be better to call the entry 'ZapZap', with the description specifying that it's a client for WhatsApp.

I agree.

2024-10-25 16:27 UTC, harshv5094 commented
okay I'll change it

> > Perhaps it would be better to call the entry 'ZapZap', with the description specifying that it's a client for WhatsApp.
> 
> I agree.

2024-11-02 12:54 UTC, adamperkowski requested changes

2024-11-02 12:54 UTC, adamperkowski commented on core/tabs/applications-setup/tab_data.toml
> +description = "ZapZap is a whatsapp desktop client for linux users, It is an open source project developed by rafatosta."
```suggestion
description = "ZapZap is an open source whatsapp desktop client for Linux users developed by rafatosta."
```

2024-11-02 12:54 UTC, adamperkowski commented on core/tabs/applications-setup/communication-apps/zapzap-setup.sh
> +  printf "%b\n" "${YELLOW}The app we are installing is Zap-Zap, an Open Source Desktop Client for Linux${RC}"
```suggestion
installZapZap() {
```

2024-11-02 12:54 UTC, adamperkowski commented on core/tabs/applications-setup/communication-apps/zapzap-setup.sh
> +    printf "%b\n" "${YELLOW}Installing Whatsapp(Zap-Zap by rtosta)${RC}"
```suggestion
    printf "%b\n" "${YELLOW}Installing Zap-Zap...${RC}"
```

2024-11-02 12:54 UTC, adamperkowski commented on core/tabs/applications-setup/communication-apps/zapzap-setup.sh
> +    printf "%b\n" "${GREEN}WhatsApp(Zap-Zap by rtosta) is already installed.${RC}"
```suggestion
    printf "%b\n" "${GREEN}Zap-Zap is already installed.${RC}"
```

2024-11-02 12:54 UTC, adamperkowski commented on core/tabs/applications-setup/communication-apps/zapzap-setup.sh
> +installWhatsapp
```suggestion
installZapZap
```

2024-11-06 04:52 UTC, harshv5094 commented
Hey @adamperkowski, can you help me clearing this shell formatting check? It's returning error code 1

2024-11-06 05:44 UTC, jeevithakannan2 commented
Run `shfmt -i 4 -ci path/to/file.sh`

2024-11-06 05:45 UTC, jeevithakannan2 requested changes

2024-11-06 05:45 UTC, jeevithakannan2 commented on core/tabs/applications-setup/communication-apps/zapzap-setup.sh
> +        . ../setup-flatpak.sh
```suggestion
        checkFlatpak
```

2024-11-06 05:56 UTC, jeevithakannan2 commented on core/tabs/applications-setup/tab_data.toml
> +(Whatsapp Client)"
```suggestion
name = "ZapZap"
```

2024-11-06 05:56 UTC, jeevithakannan2 commented on core/tabs/applications-setup/tab_data.toml
> +
```suggestion
```

2024-11-07 19:26 UTC, ChrisTitusTech approved these changes

2024-11-07 19:26 UTC, merged