feat: tor browser installation
ChrisTitusTech/linutil pull request #842
Opened 2024-10-16 13:11 UTC by phoenixhaleofficial

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description

- Added Tor Browser as an option in the Web Browsers tab.

## Testing

- Tested on Arch Linux and Debian.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-10-16 15:31 UTC, adamperkowski requested changes
Please run `cargo xtask docgen` and push the changes.

2024-10-16 15:45 UTC, adamperkowski approved these changes
`torbrowser-launcher` packages are not official. Some users might want to get tor browser directly. See https://support.torproject.org/apt/tor-deb-repo and https://support.torproject.org/rpm.

2024-10-17 00:35 UTC, jeevithakannan2 requested changes

2024-10-17 00:35 UTC, jeevithakannan2 commented on core/tabs/applications-setup/browsers/tor-browser.sh
> +                printf "%b\n" "${RED}Unsupported package manager: ""$PACKAGER""${RC}"
```suggestion
                printf "%b\n" "${RED}Unsupported package manager: ${PACKAGER}${RC}"
```

2024-10-17 14:31 UTC, phoenixhaleofficial commented on core/tabs/applications-setup/browsers/tor-browser.sh
> +                printf "%b\n" "${RED}Unsupported package manager: ""$PACKAGER""${RC}"
@jeevithakannan2 My script is based on the firefox.sh script, where there's also 2 double-quotes.
Same in all other scripts.

2024-10-17 14:56 UTC, jeevithakannan2 commented on core/tabs/applications-setup/browsers/tor-browser.sh
> +                printf "%b\n" "${RED}Unsupported package manager: ""$PACKAGER""${RC}"
Yeah working on removing unnecessary quotes. The double quotes is not necessary.

2024-10-17 16:31 UTC, phoenixhaleofficial commented
@adamperkowski both instructions relate to only the tor package, not `torbrowser-launcher`

The `torbrowser-launcher` package seems to be maintained by the Tor project, see [https://github.com/torproject/torbrowser-launcher](https://github.com/torproject/torbrowser-launcher)

They also state that the packages in the distro's repos may be out-of-date and recommend installing `torbrowser-launcher` via Flatpak, see [https://github.com/torproject/torbrowser-launcher?tab=readme-ov-file#installing-in-any-linux-distro-using-flatpak](https://github.com/torproject/torbrowser-launcher?tab=readme-ov-file#installing-in-any-linux-distro-using-flatpak)

Maybe it would be best to change the install script to use Flatpak instead of native package managers, what do you think?

2024-11-07 19:28 UTC, ChrisTitusTech approved these changes

2024-11-07 19:49 UTC, merged