fix: Debian && popos gaming deps
ChrisTitusTech/linutil pull request #859
Opened 2024-10-20 16:15 UTC by jeevithakannan2

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
- Add `git` as a dependency because getting version info for lutris requires `git`
- Correct package name for `libsdl2` => `libsdl2-2.0-0`
- Removed redundant update command
- No confirm installation for lutris
- Replace unnecessary package install code with unsupported package manager message
- Remove some comments

## Testing
- Tested on fresh install of debian12 and pop-os 22

## Issues / other PRs related
- Resolves #851 
- Resolves #852 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-10-21 06:04 UTC, lj3954 requested changes

2024-10-21 06:04 UTC, lj3954 commented on core/tabs/system-setup/gaming-setup.sh
> +            fi
What's the benefit of skipping this command? Will it fail on Pop!_OS systems, or is it just unnecessary? I think it's rather unnecessary to check for the case of one distro if it's the latter.

The `software-properties-common` package also includes add-apt-repository (and this symlink, apt-add-repository); we cannot move its installation to after running this command.

2024-10-21 08:24 UTC, jeevithakannan2 commented on core/tabs/system-setup/gaming-setup.sh
> +            fi
Pop os doesn't require contrib

2024-10-21 14:24 UTC, lj3954 commented on core/tabs/system-setup/gaming-setup.sh
> +            fi
Okay. Please move the software-properties-common installation into the body of the if statement.

2024-10-21 18:25 UTC, lj3954 approved these changes

2024-11-02 12:50 UTC, adamperkowski approved these changes

2024-11-08 15:04 UTC, ChrisTitusTech approved these changes

2024-11-08 15:04 UTC, merged