Delisting Firewall setup on fedora as it conflicts with Firewalld.
ChrisTitusTech/linutil pull request #862
Opened 2024-10-21 16:33 UTC by Angxddeep

## Type of Change
- [x] Refactoring

## Description
As Fedora comes with Firewalld preinstalled & preconfigured with rules set for fedora desktop out of the box. Installing ufw on it might conflict with it & is really not needed.

## Testing
I have tested it

## Impact
Hides firewall setup on fedora systems

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-10-21 19:01 UTC, lj3954 requested changes

2024-10-21 19:01 UTC, lj3954 commented on core/tabs/security/tab_data.toml
> +values = [ "dnf" ]
```suggestion
values = [ "firewalld" ]
```

Why check the distro, rather than for the conflicting package itself?

2024-10-22 05:39 UTC, lj3954 approved these changes

2024-10-27 00:47 UTC, lj3954 commented
This is not a refactor, it's a bugfix. The title also should be modified since my proposed changes make this PR delist firewall setup on any system with firewalld installed, with no relevance to the distro.

2024-11-02 12:50 UTC, adamperkowski approved these changes

2024-11-08 15:05 UTC, ChrisTitusTech approved these changes

2024-11-08 15:05 UTC, merged