fix: Autocpu-freq script not detecting battery on laptops
ChrisTitusTech/linutil pull request #877
Opened 2024-10-26 22:28 UTC by infstate

## Type of Change
- [ ] New feature
- [X] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description

* Added better checking when searching /sys/class/power_supply/ directory
* Uses ls with * wildcard to find all battery entries not limited to BAT0. (e.g. BAT1, BAT2)

## Testing
I have tested this on my Arch Linux install on DESKTOP. (no battery) 
However it should work.

## Impact
All this does is if there is any battery it will run the function for laptops and not desktops. 
It fixes the issue of not detecting a laptop and instead runs the power profile meant for desktops.

## Issues / other PRs related

- Resolves #871

## Checklist
- [X] My code adheres to the coding and style guidelines of the project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no errors/warnings/merge conflicts.

2024-10-26 22:52 UTC, nnyyxxxx requested changes

2024-10-26 22:52 UTC, nnyyxxxx commented on core/tabs/utils/power-profile.sh
> +        if ls /sys/class/power_supply/BAT* >/dev/null 2>&1; then     # Check if the system has a battery (laptop) by looking for any battery directory
```suggestion
        if ls /sys/class/power_supply/BAT* >/dev/null 2>&1; then
 ```
this is self explanatory, no need for the comment

2024-10-26 23:24 UTC, adamperkowski approved these changes
Thanks

2024-10-26 23:26 UTC, infstate commented
Alright, thanks for the suggestions, I have removed the comment.

2024-10-27 01:21 UTC, jeevithakannan2 approved these changes

2024-10-27 01:32 UTC, jeevithakannan2 commented
This doesn't solve the error that occurs after installation.

Add these lines after installation steps

`sudo auto-cpufreq --install`

2024-10-27 03:45 UTC, jeevithakannan2 requested changes
While this solves the laptop issue. This doesn't solve the error that occurs after installation.

Add these lines after installation steps

`sudo auto-cpufreq --install`

2024-10-27 03:49 UTC, nnyyxxxx commented
> While this solves the laptop issue. This doesn't solve the error that occurs after installation.
> 
> Add these lines after installation steps
> 
> `sudo auto-cpufreq --install`

that is not related to this pull request, and it should be used with $ESCALATION_TOOL not sudo

2024-10-27 04:20 UTC, jeevithakannan2 commented
> > While this solves the laptop issue. This doesn't solve the error that occurs after installation.
> > Add these lines after installation steps
> > `sudo auto-cpufreq --install`
> 
> that is not related to this pull request, and it should be used with $ESCALATION_TOOL not sudo

The issue mentions two issues and this PR only resolves only one issue.

And I just copy pasted the sudo auto-cpufreq --install from the err log

2024-10-27 04:22 UTC, nnyyxxxx commented
> > > While this solves the laptop issue. This doesn't solve the error that occurs after installation.
> > > Add these lines after installation steps
> > > `sudo auto-cpufreq --install`
> > 
> > 
> > that is not related to this pull request, and it should be used with $ESCALATION_TOOL not sudo
> 
> The issue mentions two issues and this PR only resolves only one issue.
> 
> And I just copy pasted the sudo auto-cpufreq --install from the err log

again, ``sudo auto-cpufreq --install`` is not related to this pull request, please re read the PR title and description

2024-10-27 04:23 UTC, jeevithakannan2 commented
> > > > While this solves the laptop issue. This doesn't solve the error that occurs after installation.
> > > > Add these lines after installation steps
> > > > `sudo auto-cpufreq --install`
> > > 
> > > 
> > > that is not related to this pull request, and it should be used with $ESCALATION_TOOL not sudo
> > 
> > 
> > The issue mentions two issues and this PR only resolves only one issue.
> > And I just copy pasted the sudo auto-cpufreq --install from the err log
> 
> again, `sudo auto-cpufreq --install` is not related to this pull request, please re read the PR title and description

Then it does not resolve that issue completely. Please re-read the issue !!

2024-10-27 04:24 UTC, nnyyxxxx commented
> > > > > While this solves the laptop issue. This doesn't solve the error that occurs after installation.
> > > > > Add these lines after installation steps
> > > > > `sudo auto-cpufreq --install`
> > > > 
> > > > 
> > > > that is not related to this pull request, and it should be used with $ESCALATION_TOOL not sudo
> > > 
> > > 
> > > The issue mentions two issues and this PR only resolves only one issue.
> > > And I just copy pasted the sudo auto-cpufreq --install from the err log
> > 
> > 
> > again, `sudo auto-cpufreq --install` is not related to this pull request, please re read the PR title and description
> 
> Then it does not resolve that issue completely. Please re-read the issue !!

ok? and is that my problem? why should i read the issue, once again ``sudo auto-cpufreq --install`` is not related to this pull request, please re read the pr title and description one more time !!

2024-10-27 04:25 UTC, nnyyxxxx commented
issues and pull requests should be focused on 1 bug, or 1 implementation, they should not include multiple bugs or implementations, if you want you can split your issue into 2 since that would be better

2024-10-27 04:29 UTC, jeevithakannan2 commented
> issues and pull requests should be focused on 1 bug, or 1 implementation, they should not include multiple bugs or multiple implementations, if you want you can split your issue into 2 since that would be better

I am getting what you're trying to say but this is not a big change. Not going to waste time on two separate PRs and issues while it can be easily fixed by adding a line in single PR.

2024-10-27 04:30 UTC, nnyyxxxx commented
> > issues and pull requests should be focused on 1 bug, or 1 implementation, they should not include multiple bugs or multiple implementations, if you want you can split your issue into 2 since that would be better
> 
> I am getting what you're trying to say but this is not a big change. Not going to waste time on two separate PRs and issues while it can be easily fixed by adding a line in single PR.

please re read the message you're responding to !!, that second issue is not related to this PR at all and should not be included

2024-10-27 04:32 UTC, jeevithakannan2 commented
> > > issues and pull requests should be focused on 1 bug, or 1 implementation, they should not include multiple bugs or multiple implementations, if you want you can split your issue into 2 since that would be better
> > 
> > 
> > I am getting what you're trying to say but this is not a big change. Not going to waste time on two separate PRs and issues while it can be easily fixed by adding a line in single PR.
> 
> please re read the message you're responding to !!, that second issue is not related to this PR at all and should not be included

Waste of time and resources for a simple fix.

2024-10-27 04:32 UTC, nnyyxxxx commented
> > > > issues and pull requests should be focused on 1 bug, or 1 implementation, they should not include multiple bugs or multiple implementations, if you want you can split your issue into 2 since that would be better
> > > 
> > > 
> > > I am getting what you're trying to say but this is not a big change. Not going to waste time on two separate PRs and issues while it can be easily fixed by adding a line in single PR.
> > 
> > 
> > please re read the message you're responding to !!, that second issue is not related to this PR at all and should not be included
> 
> Waste of time and resources for a simple fix.

re read the reply chain one more time !! maybe you'll understand the issue we're arguing about

2024-10-27 04:37 UTC, nnyyxxxx approved these changes
awesome

2024-10-27 04:59 UTC, infstate commented
What in tarnation is going on here, doesn't it run the autocpu-freq --install on line 37 of the install function?

2024-10-27 05:07 UTC, jeevithakannan2 commented
> What in tarnation is going on here, doesn't it run the autocpu-freq --install on line 37 of the install function?

Looks like I was hallucinating. When I took the SS that line was not called. See the SS in the issue.

2024-10-27 05:07 UTC, nnyyxxxx commented
looks like theres an extra space separating escalation tool on that line

2024-10-27 05:09 UTC, jeevithakannan2 commented
> looks like theres an extra space separating escalation tool on that line

Yeah but that shouldn't cause issues. I cannot reproduce the issue again.

2024-10-27 05:10 UTC, infstate commented
If you want I can remove the extra space...

2024-10-27 06:43 UTC, jeevithakannan2 approved these changes

2024-10-27 18:00 UTC, adamperkowski commented
damn what happened here
thats a lot of words

2024-11-08 15:06 UTC, ChrisTitusTech approved these changes

2024-11-08 15:06 UTC, merged