WIP: Replace BUILD_DATE with VERSION
ChrisTitusTech/linutil pull request #878
Opened 2024-10-27 04:49 UTC by bmwiedemann

WIP: Replace `BUILD_DATE` with `VERSION`
to make builds reproducible.
See https://reproducible-builds.org/ for why this is good.

This is an alternative solution to #869 

Needs some solution for the `FIXME`.

## Type of Change
- [ ] New feature
- [X] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description

## Testing

## Impact

## Issues / other PRs related

- Resolves #

## Additional Information

## Checklist
- [X] My code adheres to the coding and style guidelines of the project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no errors/warnings/merge conflicts.

2024-10-27 10:37 UTC, adamperkowski requested changes

2024-10-27 10:37 UTC, adamperkowski commented on tui/build.rs
> +        "FIXME"
remove this completely

2024-10-27 10:37 UTC, adamperkowski commented on tui/src/state.rs
> +const TITLE: &str = concat!("Linux Toolbox - ", env!("VERSION"));
https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates

```suggestion
const TITLE: &str = concat!("Linux Toolbox - ", env!("CARGO_PKG_VERSION"));
```

2024-10-27 11:40 UTC, adamperkowski commented
Thanks for the PR. We can remove the whole `build.rs` file here and use [CARGO_PKG_VERSION](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates).

2024-10-27 14:54 UTC, bmwiedemann commented on tui/build.rs
> +        "FIXME"
Done

2024-10-27 16:42 UTC, adamperkowski approved these changes
Thanks. I'll close the other PR.

2024-10-27 18:31 UTC, lj3954 commented
The build dependency should also be removed.

2024-10-27 18:32 UTC, adamperkowski commented
Oh yes. Liam is right.

2024-10-30 13:54 UTC, bmwiedemann commented
Is anything missing to get this merged?

2024-10-30 14:01 UTC, adamperkowski approved these changes
> Is anything missing to get this merged?

In this PR - no
In the repo - yes

Chris needs to set some things up

2024-10-31 18:22 UTC, ChrisTitusTech approved these changes

2024-10-31 18:22 UTC, merged