Made the neovim config setup as an option
ChrisTitusTech/linutil pull request #879
Opened 2024-10-27 16:34 UTC by pik4li

## Type of Change
- [x] New feature

## Description
Made the setup of Chris's dotfiles as an option, so that you can only install neovim and its dependencies

## Testing
Changed the code -> save -> cargo run -> works

## Impact
small

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-10-27 18:06 UTC, adamperkowski requested changes

2024-10-27 18:06 UTC, adamperkowski commented on core/tabs/applications-setup/Developer-tools/neovim-setup.sh
> +}
```suggestion
dotsPrompt() {
    printf "%b\n" "${GREEN}Do you want to install Titus' Neovim? (Y/n): ${RC}"
    read -r _titusDots
    case "$_titusDots" in
    N | n)
        printf "%b\n" "${YELLOW}Installation complete.."
        ;;
    *)
        cloneNeovim
        backupNeovimConfig
        linkNeovimConfig
        ;;
    esac
}
```

2024-10-27 18:06 UTC, adamperkowski commented on core/tabs/applications-setup/Developer-tools/neovim-setup.sh
> +askToClone
```suggestion
dotsPrompt
```

2024-10-27 18:06 UTC, adamperkowski commented
I see where you're coming from but I'm not sure if we want that change. It may be better to just rename this from Neovim setup to something like Titus' Neovim setup

2024-10-27 22:36 UTC, pik4li commented
> I see where you're coming from but I'm not sure if we want this change. It may be better to just rename the entry from Neovim setup to something like Titus' Neovim setup

Thanks very much. Im pretty new to contributing, so any help is appreciated

2024-10-31 18:18 UTC, ChrisTitusTech commented
Extra keypresses and prompts just annoy me. Going to deny this PR, if you are rolling your own neovim... why would you use mine?

2024-10-31 18:18 UTC, closed without merging