Added Script to update to the next stable fedora release
ChrisTitusTech/linutil pull request #886
Opened 2024-10-29 22:51 UTC by Angxddeep

## Type of Change
- [x] New feature

## Description
An easy way to upgrade to the next version of fedora, not recommended (by me) for gnome and KDE spin because they support upgrades through their software store.

## Testing
I have tested everything except the upgrade itself, I am currently on fedora 41 and in no mood of reinstalling my install

## Additional Information
I couldn't understand what task_list =  means in tab data, so If someone could explain what it is, I would really appreciate it
## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-10-29 23:16 UTC, jeevithakannan2 commented
This was not implemented as it could break systems. Make sure you've tested it.

2024-10-29 23:17 UTC, jeevithakannan2 commented
Try testing it in a VM.

2024-10-30 02:38 UTC, adamperkowski commented
Yeah I agree with @jeevithakannan2

2024-10-30 02:39 UTC, adamperkowski commented
Yeah I agree with @jeevithakannan2

2024-10-30 02:57 UTC, adamperkowski requested changes

2024-10-30 02:57 UTC, adamperkowski commented on core/tabs/system-setup/fedora/fedora-upgrade.sh
> +# Global version variables
```suggestion
```

2024-10-30 02:57 UTC, adamperkowski commented on core/tabs/system-setup/fedora/fedora-upgrade.sh
> +# Function to update Fedora
```suggestion
```

2024-10-30 02:57 UTC, adamperkowski commented on core/tabs/system-setup/fedora/fedora-upgrade.sh
> +# Function to run post-upgrade tasks
```suggestion
```

2024-10-30 02:57 UTC, adamperkowski commented on core/tabs/system-setup/fedora/fedora-upgrade.sh
> +# Main menu
```suggestion
```

2024-10-30 02:57 UTC, adamperkowski commented on core/tabs/system-setup/tab_data.toml
> +description = "Upgrades the System to the next fedora release"
```suggestion
description = "Upgrades system to the next Fedora release"
```

2024-10-30 02:57 UTC, adamperkowski commented on core/tabs/system-setup/fedora/fedora-upgrade.sh
> +    printf "%b\n" "${RED}Make sure your system is fully updated; if not, update first and reboot once.${RC}"
```suggestion
    printf "%b\n" "${RED}Make sure your system is fully updated; if not, update it first and reboot once.${RC}"
```

2024-10-30 02:57 UTC, adamperkowski commented on core/tabs/system-setup/fedora/fedora-upgrade.sh
> +    printf "%b\n" "${YELLOW}Do you want to update to Fedora version $next_version? (y/n): ${RC}"
```suggestion
    printf "%b\n" "${YELLOW}Do you want to update to $next_version? (y/n): ${RC}"  
```

2024-10-30 02:57 UTC, adamperkowski commented on core/tabs/system-setup/fedora/fedora-upgrade.sh
> +previous_version=$((current_version - 1))
it's unused

```suggestion
```

2024-10-30 02:57 UTC, adamperkowski commented on core/tabs/system-setup/fedora/fedora-upgrade.sh
> +    fi
bashisms

```suggestion
    case "$response" in
        y|Y)
            printf "%b\n" "${CYAN}Preparing to update to $next_version...${RC}"
        
            if ! "$ESCALATION_TOOL" "$PACKAGER" install dnf-plugin-system-upgrade -y; then
                printf "%b\n" "${RED}Failed to install dnf-plugin-system-upgrade.${RC}"
                exit 1
            fi
        
            if ! "$ESCALATION_TOOL" "$PACKAGER" system-upgrade download --releasever="$next_version"; then
                printf "%b\n" "${RED}Failed to download the upgrade packages.${RC}"
                exit 1
            fi

            printf "%b\n" "${YELLOW}Do you want to reboot now to apply the upgrade? (y/n): ${RC}"
            read -r reboot_response

            case "$reboot_response" in
                y|Y)
                    printf "%b\n" "${GREEN}Rebooting to apply the upgrade...${RC}"
                    "$ESCALATION_TOOL" "$PACKAGER" system-upgrade reboot
                    ;;
                *)
                    printf "%b\n" "${YELLOW}You can reboot later to apply the upgrade.${RC}"
                    ;;
            esac
            ;;
        *)
            printf "%b\n" "${RED}No upgrade performed.${RC}"
            ;;
    esac
}
```

2024-10-30 13:08 UTC, jeevithakannan2 requested changes

2024-10-30 13:08 UTC, jeevithakannan2 commented on core/tabs/system-setup/fedora/fedora-upgrade.sh
> +    printf "%b\n" "${RED}Make sure your system is fully updated; if not, update it first and reboot once.${RC}"
```suggestion
    printf "%b\n" "${YELLOW}Make sure your system is fully updated; if not, update it first and reboot once.${RC}"
```

2024-10-30 13:08 UTC, jeevithakannan2 commented on core/tabs/system-setup/fedora/fedora-upgrade.sh
> +                    printf "%b\n" "${GREEN}Rebooting to apply the upgrade...${RC}"
```suggestion
                    printf "%b\n" "${YELLOW}Rebooting to apply the upgrade...${RC}"
```

2024-10-30 13:58 UTC, adamperkowski approved these changes
> Just tested it on real hardware and its working

Well if you say so.

2024-10-31 19:00 UTC, ChrisTitusTech approved these changes

2024-10-31 19:01 UTC, merged