fix(create-bootable-usb.sh) confirmation prompt
ChrisTitusTech/linutil pull request #902
Opened 2024-11-01 18:10 UTC by lennartpj

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
Fixing the confirmation prompt by converting everything to lower case and allowing yes and y as answers.

## Testing
tested this and works as expected

## Impact
minor

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-11-01 18:18 UTC, adamperkowski approved these changes

2024-11-01 18:22 UTC, lj3954 requested changes

2024-11-01 18:22 UTC, lj3954 commented on core/tabs/utils/create-bootable-usb.sh
> +    if [ "$(echo "$CONFIRMATION" | tr '[:upper:]' '[:lower:]')" != "yes" ] && [ "$(echo "$CONFIRMATION" | tr '[:upper:]' '[:lower:]')" != "y" ]; then
```suggestion
    CONFIRMATION="$(echo "$CONFIRMATION" | tr '[:upper:]' '[:lower:]')"
    if [  "${CONFIRMATION}" != "yes" ] && [ "${CONFIRMATION}" != "y" ]; then
```

2024-11-01 18:29 UTC, lennartpj commented on core/tabs/utils/create-bootable-usb.sh
> +    if [ "$(echo "$CONFIRMATION" | tr '[:upper:]' '[:lower:]')" != "yes" ] && [ "$(echo "$CONFIRMATION" | tr '[:upper:]' '[:lower:]')" != "y" ]; then
wow, that was fast!
I gave it a quick test and it seems to work. 
thank you!

2024-11-01 19:05 UTC, adamperkowski commented
The CI failing here is unrelated to the changes.

2024-11-01 21:03 UTC, cartercanedy commented
> The CI failing here is unrelated to the changes.

Hmm...

Looks like he needs to put in some shellcheck directives to ignore the warnings

https://github.com/ChrisTitusTech/linutil/blob/e96b75a890a149fe9af83bbd1040f15590708fa9/core/tabs/utils/create-bootable-usb.sh#L17

https://github.com/ChrisTitusTech/linutil/blob/e96b75a890a149fe9af83bbd1040f15590708fa9/core/tabs/utils/create-bootable-usb.sh#L23

https://github.com/ChrisTitusTech/linutil/blob/e96b75a890a149fe9af83bbd1040f15590708fa9/core/tabs/utils/create-bootable-usb.sh#L25

2024-11-01 21:17 UTC, cartercanedy requested changes
```sh
    # shellcheck disable=SC2086
```

Apply shellcheck directives like this to the rest of the unquoted `${DEPENDENCIES}` instances

2024-11-01 22:51 UTC, lj3954 approved these changes

2024-11-04 05:07 UTC, jeevithakannan2 approved these changes

2024-11-11 16:09 UTC, merged