fix (ci): preview workflow
ChrisTitusTech/linutil pull request #905
Opened 2024-11-02 14:29 UTC by jeevithakannan2

## Type of Change
- [x] Bug fix

## Description
- Fix binary download bug
- Remove invalid action inputs
- Add preview in PR body

>[!NOTE]
> - @ChrisTitusTech using `latest` as tag name will not work
> - I don't know why you're using a PAT token. I think that is not needed.

## Issues / other PRs related
- Closes #904 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-11-08 22:31 UTC, Real-MullaC requested changes

2024-11-08 22:31 UTC, Real-MullaC commented on .github/workflows/preview.yml
> +            ![preview](https://raw.githubusercontent.com/${{ github.repository }}/feature/preview-${{ env.tag_name }}/docs/assets/preview.gif)
Make it go to the .github folder.

2024-11-08 22:32 UTC, Real-MullaC commented
This change is to make sure my PR 888 has no more conflicts due to docs update,

2024-11-11 16:10 UTC, ChrisTitusTech approved these changes

2024-11-11 16:10 UTC, merged