fix(fedora): Recent syntax changes with DNF5
ChrisTitusTech/linutil pull request #907
Opened 2024-11-03 00:46 UTC by Angxddeep

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
There have been a recent syntax change in dnf5 therefore I have updated all the setup scripts which requires **--add-repo** and replaced it with **--addrepo**.

## Testing
Works

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-11-03 04:36 UTC, jeevithakannan2 commented
This syntax change is only for fedora 41 right?

2024-11-03 04:42 UTC, jeevithakannan2 commented
I think adding a version check is more robust way

2024-11-03 13:36 UTC, Angxddeep commented
> I think adding a version check is more robust way

Do we really need to do that, most fedora downstream will switch to dnf5 if they haven't already done it.

2024-11-03 14:09 UTC, jeevithakannan2 commented
Are they switching to dnf5 in fedora 39 and 40 also?

2024-11-04 01:40 UTC, adamperkowski commented
> Are they switching to dnf5 in fedora 39 and 40 also?

No idea. @Angxddeep please research this, add a version check (if applicable) and then mark this PR as ready for review. Thanks.

2024-11-04 04:56 UTC, lj3954 commented
> Are they switching to dnf5 in fedora 39 and 40 also?

No. This PR absolutely cannot be merged as is.

2024-11-04 06:24 UTC, Angxddeep commented
I am a busy with life for a week. Ill will try to do it after that

2024-11-06 05:50 UTC, jeevithakannan2 commented
fedora 39, 40, 41 all have `dnf5`

2024-11-06 07:42 UTC, Angxddeep commented
> fedora 39, 40 have `dnf5` package. So [64cb3c8](https://github.com/ChrisTitusTech/linutil/commit/64cb3c860be21c20d6071e7666b5f703bf745786) this might not work

They only have dnf5 is as experimental in the repos, it's not installed by default

2024-11-06 08:02 UTC, lj3954 commented
Yes, but it still could be installed; the dnf symlink will continue to point to dnf4 in that case. You would need to explicitly call dnf5 to ensure the correct program is used.

2024-11-06 08:24 UTC, jeevithakannan2 commented
dnf --version and some cuts this reduces complexity

2024-11-06 11:13 UTC, Angxddeep commented
> Yes, but it still could be installed; the dnf symlink will continue to point to dnf4 in that case. You would need to explicitly call dnf5 to ensure the correct program is used.

I am going to be honest, fedora 39 will be EOL in a month and linutil isn't popular enough and most people will upgrade to 41 in no time. As is said I am a bit busy I think we should merge this so at least it works for people who have upgraded to F41. If you guys can submit changes that will be good too

2024-11-06 14:40 UTC, jeevithakannan2 requested changes

2024-11-06 14:40 UTC, jeevithakannan2 commented on core/tabs/applications-setup/Developer-tools/sublime-setup.sh
> +                    "$ESCALATION_TOOL" "$PACKAGER" config-manager --add-repo https://download.sublimetext.com/rpm/dev/x86_64/sublime-text.repo
```suggestion
                dnf_version=$(dnf --version | head -n 1 | cut -d '.' -f 1)
                if [ "$dnf_version" -eq 4 ]; then
                    "$ESCALATION_TOOL" "$PACKAGER" config-manager --add-repo https://download.sublimetext.com/rpm/dev/x86_64/sublime-text.repo
                else
                    "$ESCALATION_TOOL" "$PACKAGER" config-manager addrepo --from-repofile=https://download.sublimetext.com/rpm/dev/x86_64/sublime-text.repo
```

2024-11-06 14:40 UTC, jeevithakannan2 commented on core/tabs/applications-setup/browsers/brave.sh
> +                    "$ESCALATION_TOOL" "$PACKAGER" config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
```suggestion
                dnf_version=$(dnf --version | head -n 1 | cut -d '.' -f 1)
                if [ "$dnf_version" -eq 4 ]; then
                    "$ESCALATION_TOOL" "$PACKAGER" config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
                else
                    "$ESCALATION_TOOL" "$PACKAGER" config-manager addrepo --from-repofile=https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
```

2024-11-06 14:40 UTC, jeevithakannan2 commented on core/tabs/applications-setup/browsers/vivaldi.sh
> +                    "$ESCALATION_TOOL" "$PACKAGER" config-manager --add-repo https://repo.vivaldi.com/stable/vivaldi-fedora.repo
```suggestion
                dnf_version=$(dnf --version | head -n 1 | cut -d '.' -f 1)
                if [ "$dnf_version" -eq 4 ]; then
                    "$ESCALATION_TOOL" "$PACKAGER" config-manager --add-repo https://repo.vivaldi.com/stable/vivaldi-fedora.repo
                else
                    "$ESCALATION_TOOL" "$PACKAGER" config-manager addrepo --from-repofile=https://repo.vivaldi.com/stable/vivaldi-fedora.repo
```

2024-11-06 14:40 UTC, jeevithakannan2 commented on core/tabs/applications-setup/docker-setup.sh
> +                "$ESCALATION_TOOL" "$PACKAGER" config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
```suggestion
            dnf_version=$(dnf --version | head -n 1 | cut -d '.' -f 1)
            if [ "$dnf_version" -eq 4 ]; then
                "$ESCALATION_TOOL" "$PACKAGER" config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
            else
                "$ESCALATION_TOOL" "$PACKAGER" config-manager addrepo --from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo
```

2024-11-06 14:40 UTC, jeevithakannan2 commented on core/tabs/applications-setup/docker-setup.sh
> +                "$ESCALATION_TOOL" "$PACKAGER" config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
```suggestion
            dnf_version=$(dnf --version | head -n 1 | cut -d '.' -f 1)
            if [ "$dnf_version" -eq 4 ]; then
                "$ESCALATION_TOOL" "$PACKAGER" config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
            else
                "$ESCALATION_TOOL" "$PACKAGER" config-manager addrepo --from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo
```

2024-11-06 15:09 UTC, jeevithakannan2 approved these changes

2024-11-11 16:12 UTC, merged