refact: auto-cpufreq
ChrisTitusTech/linutil pull request #908
Opened 2024-11-03 13:08 UTC by jeevithakannan2

## Type of Change
- [x] Refactoring

## Description
- Added description.
- Renamed functions.
- Added AUR package installation for arch systems.
- Moved `auto-cpufreq` from `utils` to `application-setup`.
- Refact git clone path to `$HOME/.local/share` to maintain consistency among scripts.

## Testing
- Tested on arch linux without issues.

## Issues / other PRs related
- Resolves #872 

## Additional Information
- Merge conflicts with #877 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-11-04 04:59 UTC, lj3954 approved these changes

2024-11-08 22:35 UTC, Real-MullaC requested changes
This is to make no conflicts with PR #888

2024-11-08 22:35 UTC, Real-MullaC commented on docs/userguide.md
> +https://github.com/AdnanHodzic/auto-cpufreq
Remove these and add them to the [https://github.com/Chris-Titus-Docs/linutil-docs](https://github.com/Chris-Titus-Docs/linutil-docs) repo

2024-11-11 16:13 UTC, ChrisTitusTech approved these changes

2024-11-11 16:13 UTC, merged