feat: Mouse scroll
ChrisTitusTech/linutil pull request #913
Opened 2024-11-04 07:10 UTC by jeevithakannan2

## Type of Change
- [x] New feature
- [x] UI/UX improvement

## Description
- Add mouse scroll in all directions.

## Testing
- Tested on arch linux with no issues.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-11-05 08:28 UTC, lj3954 requested changes

2024-11-05 08:28 UTC, lj3954 commented on tui/src/main.rs
> +                continue;
```suggestion
```
No need for this.

2024-11-05 08:28 UTC, lj3954 commented on tui/src/confirmation.rs
> +        };
```suggestion
        match event.kind {
            MouseEventKind::ScrollDown => {
                self.scroll_down();
            }
            MouseEventKind::ScrollUp => {
                self.scroll_up();
            }
            _ => {}
        }
```
Why is this match statement returning an unused ConfirmStatus?

2024-11-05 08:28 UTC, lj3954 commented on tui/src/state.rs
> +    }
We should consider taking the position of the mouse into account. For example, mouse events outside a floating window should be ignored, and the tablist/list focus should switch if a mouse event occurs in the other.

2024-11-05 08:44 UTC, jeevithakannan2 commented on tui/src/confirmation.rs
> +        };
I was wondering the same with handle_key_event

2024-11-05 08:46 UTC, jeevithakannan2 commented on tui/src/state.rs
> +    }
Yeah I get it. That was my idea but it requires little bit more time. I have my semesters from next week will need to do that after my semesters. For now this is okayish

2024-11-05 13:30 UTC, jeevithakannan2 commented on tui/src/state.rs
> +    }
Implemented !!

2024-11-05 23:22 UTC, nnyyxxxx requested changes
this should be togglable and off by default

2024-11-05 23:24 UTC, jeevithakannan2 commented
> this should be togglable and off by default

Why would someone want that?

2024-11-05 23:25 UTC, nnyyxxxx commented
> > this should be togglable and off by default
> 
> Why would someone want that?

this is a tui application ran in the terminal having mouse interaction without a toggle is poor ux by default

2024-11-11 16:21 UTC, ChrisTitusTech approved these changes

2024-11-11 16:22 UTC, merged