Move ZapZap entry to communication apps, remove redundant zoom entry
ChrisTitusTech/linutil pull request #925
Opened 2024-11-08 01:05 UTC by jeevithakannan2

## Type of Change
- [x] Documentation update
- [x] Refactoring

## Description
- Remove redundant zoom entry and move zapzap from developer tools to communication.

## Testing

**Before**

![image](https://github.com/user-attachments/assets/bcde129b-b25c-4d73-b4d6-58a32211db08)
![image](https://github.com/user-attachments/assets/d925f2f4-2edc-468c-91a8-a48d8a5b346f)

**After**

![image](https://github.com/user-attachments/assets/6eb71547-ce8a-4cdc-9945-9c9f8d9d7885)
![image](https://github.com/user-attachments/assets/2412b69a-f488-4f9b-896d-7af4b419a854)

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-11-08 22:38 UTC, Real-MullaC requested changes
This is to make no conflicts with PR https://github.com/ChrisTitusTech/linutil/pull/888

2024-11-08 22:38 UTC, Real-MullaC commented on docs/userguide.md
> +- **ZapZap**: ZapZap is an open source whatsapp desktop client for Linux users developed by rafatosta.
Remove this and add it to the https://github.com/Chris-Titus-Docs/linutil-docs repo

2024-11-11 16:25 UTC, ChrisTitusTech requested changes
Why remove Zoom that is used all over the US for meetings.

2024-11-11 16:38 UTC, jeevithakannan2 commented
> Why remove Zoom that is used all over the US for meetings.

That is a redundant entry. It is not completely removed.

2024-11-13 13:22 UTC, harshv5094 commented
> ## Type of Change
> 
>     * [x]  Documentation update
> 
>     * [x]  Refactoring
> 
> 
> ## Description
> 
>     * Remove redundant zoom entry and move zapzap from developer tools to communication.
> 
> 
> ## Testing
> 
> **Before**
> 
> ![image](https://private-user-images.githubusercontent.com/97960473/384188379-bcde129b-b25c-4d73-b4d6-58a32211db08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDQzODAsIm5iZiI6MTczMTUwNDA4MCwicGF0aCI6Ii85Nzk2MDQ3My8zODQxODgzNzktYmNkZTEyOWItYjI1Yy00ZDczLWI0ZDYtNThhMzIyMTFkYjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEzMjEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3OGZiYzRkMGY3ZWU1ZTIwZWUyMzUwNWEzYzlhMjk3Nzg2MDI1OTg0NWE4NGY5YmJiNzU5YWEwNTBmODU4OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.idjR6jb4tq6_rse19NSA_fO6AEPBo2pOxcjMNPvJIlM) ![image](https://private-user-images.githubusercontent.com/97960473/384188464-d925f2f4-2edc-468c-91a8-a48d8a5b346f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDQzODAsIm5iZiI6MTczMTUwNDA4MCwicGF0aCI6Ii85Nzk2MDQ3My8zODQxODg0NjQtZDkyNWYyZjQtMmVkYy00NjhjLTkxYTgtYTQ4ZDhhNWIzNDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEzMjEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZDVhNTJmOTc3M2I1YTQ4Mjk4YzFmMGQ4YTg2NmZkZTE2MzZkMmY2MjkyMTMxNGI1ZWNhZWY5Yjg3NTkxNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.be6OSPXx839yg_1-csr3xOgBNtFeC-jq0bakOZliGa4)
> 
> **After**
> 
> ![image](https://private-user-images.githubusercontent.com/97960473/384188189-6eb71547-ce8a-4cdc-9945-9c9f8d9d7885.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDQzODAsIm5iZiI6MTczMTUwNDA4MCwicGF0aCI6Ii85Nzk2MDQ3My8zODQxODgxODktNmViNzE1NDctY2U4YS00Y2RjLTk5NDUtOWM5ZjhkOWQ3ODg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEzMjEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZDZjNTY3Njc2ZDQyOTJiZTU5NjI4Mjk0ZjNlMTQxM2FiYjUyMzAyNGY1OTY4MGM0YTI2NzQ2NGY2ZDAxZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.plx1c5E-8htshdoam2rNTA2QuaO5RdzZFbt8VnxBfgI) ![image](https://private-user-images.githubusercontent.com/97960473/384188520-2412b69a-f488-4f9b-896d-7af4b419a854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDQzODAsIm5iZiI6MTczMTUwNDA4MCwicGF0aCI6Ii85Nzk2MDQ3My8zODQxODg1MjAtMjQxMmI2OWEtZjQ4OC00ZjliLTg5NmQtN2FmNGI0MTlhODU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEzMjEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlYTEwOWM5NzU5NGFkOGZmM2U3MGUxNzM1ZjA1ZTBjZmIzOTZjNTJkOTFjMWUxOTVhMGE4ZTZjOTY5ZWZkZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OM4VQiZjWXXSiOaMWszFo7G738Oe2T-oc8j7oqdSYQ4)
> ## Checklist
> 
>     * [x]  My code adheres to the coding and style guidelines of the project.
> 
>     * [x]  I have performed a self-review of my own code.
> 
>     * [x]  I have made corresponding changes to the documentation.
> 
>     * [x]  My changes generate no errors/warnings/merge conflicts.

Sorry, My bad 😝

2024-11-13 14:05 UTC, jeevithakannan2 commented
> Sorry, My bad 😝

No problem

2024-11-22 15:55 UTC, adamperkowski approved these changes

2024-12-05 03:36 UTC, ChrisTitusTech approved these changes

2024-12-05 03:36 UTC, merged