Add Zed editor installation script
ChrisTitusTech/linutil pull request #929
Opened 2024-11-08 18:07 UTC by jeevithakannan2

## Type of Change
- [x] New feature
- [x] Refactoring

## Description
- Added [zed](https://zed.dev/) editor installation script.

> [!NOTE]
> Chores:
> - The chores are not related to this PR. Instead of creating a separate PR it was done here itself.
> - Refactor `Developer-tools` directory to `developer-tools` (Kind of annoying for developers to hold shift every time when typing D)
> - Refactor file names inside `developer-tools` from `application-setup.sh` to `application.sh` as all the scripts inside the directory is supposed to setup that particular application. No need of mentioning it in the name.
> - The chores are of separate commits @ChrisTitusTech If you wish not to do this we can easily revert the commits.

## Testing
- Tested on arch linux and debian12 without issues.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-11-08 22:39 UTC, Real-MullaC requested changes
This is to make no conflicts with PR https://github.com/ChrisTitusTech/linutil/pull/888

2024-11-08 22:39 UTC, Real-MullaC commented on docs/userguide.md
> +- **Zed**: Zed is a next-generation code editor written in rust, designed for high-performance collaboration with humans and AI.
Remove this and add it to the https://github.com/Chris-Titus-Docs/linutil-docs repo

2024-11-09 02:25 UTC, nnyyxxxx requested changes

2024-11-09 02:25 UTC, nnyyxxxx commented on core/tabs/applications-setup/developer-tools/zed.sh
> +    if ! command_exists dev.zed.Zed && ! command_exists zed && ! command_exists zeditor; then
```suggestion
    if ! command_exists dev.zed.Zed && ! command_exists zed zeditor; then
```

2024-11-09 02:26 UTC, nnyyxxxx commented on core/tabs/applications-setup/developer-tools/zed.sh
> +    if ! command_exists dev.zed.Zed && ! command_exists zed && ! command_exists zeditor; then
command_exists takes multiple values #762

2024-11-09 02:27 UTC, nnyyxxxx requested changes

2024-11-09 02:27 UTC, nnyyxxxx commented on core/tabs/applications-setup/developer-tools/zed.sh
> +    if ! command_exists dev.zed.Zed && ! command_exists zed && ! command_exists zeditor; then
```suggestion
    if ! command_exists dev.zed.Zed zed zeditor; then
```

this can actually just be put on one line instead of using &&

2024-11-09 02:27 UTC, nnyyxxxx commented on core/tabs/applications-setup/developer-tools/zed.sh
> +    if ! command_exists dev.zed.Zed && ! command_exists zed && ! command_exists zeditor; then
ignore this, and apply the one below

2024-11-09 02:28 UTC, nnyyxxxx commented
@jeevithakannan2 if there are any other scripts that use && please remove all of the &&'s and make a pr

2024-11-09 02:29 UTC, jeevithakannan2 commented
That suggestion is wrong.

2024-11-09 02:29 UTC, nnyyxxxx commented
how so?

2024-11-09 02:30 UTC, jeevithakannan2 commented
You suggestion is interpreted as command_exists foo1 || command_exists foo2

2024-11-09 02:32 UTC, nnyyxxxx commented
nope

2024-11-09 02:32 UTC, nnyyxxxx commented
```bash
command_exists() {
for cmd in "$@"; do
    export PATH="$HOME/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:$PATH"
    command -v "$cmd" >/dev/null 2>&1 || return 1
done
return 0
}
```
take a look

2024-11-09 02:33 UTC, jeevithakannan2 commented
This will not check both foo1 and foo2 .It will immediately return 1 is foo1 is not found

2024-11-09 02:33 UTC, nnyyxxxx commented
removing the && would simplify it since && is redundant due to #762 having both && and not having && is the same but, && is redundant due to #762

2024-11-09 02:34 UTC, nnyyxxxx commented
if one is found why would it need to check the others?

> This will not check both foo1 and foo2 .It will immediately return 1 if foo1 is not found

2024-11-09 02:38 UTC, jeevithakannan2 commented
> removing the && would simplify it since && is redundant due to #762 having both && and not having && is the same but, && is redundant due to #762

That's what I have explained above. #762 will work as || not as &&

2024-11-09 02:48 UTC, nnyyxxxx commented
i have made a pr to fix this, might as well change it now and reference it in the description of this one #931

2024-11-09 02:53 UTC, nnyyxxxx commented
ig there really is no way to fix that other than manually using &&

2024-11-09 03:07 UTC, nnyyxxxx requested changes

2024-11-09 03:07 UTC, nnyyxxxx commented on core/tabs/applications-setup/developer-tools/zed.sh
> +installZed
```suggestion
checkEnv
checkEscalationTool
clear
installZed
```

2024-11-09 03:07 UTC, nnyyxxxx commented on core/tabs/applications-setup/developer-tools/zed.sh
> +installZed
keep the synergy with the other scripts

2024-11-11 16:41 UTC, jeevithakannan2 commented
Oops accidentally rebased instead of merging main. Will clear this in a minute

2024-11-11 16:42 UTC, nnyyxxxx commented
wtf

2024-11-11 16:45 UTC, jeevithakannan2 commented
Fixed !!

2024-11-16 03:15 UTC, cartercanedy commented
> Oops accidentally rebased instead of merging main. Will clear this in a minute

Rebasing is often preferred, just fyi

Too many merges make `git log` way to complicated to understand/bisect if needed.

2025-02-02 04:07 UTC, ChrisTitusTech approved these changes

2025-02-02 04:07 UTC, merged