WIP: Rust fixes and optimizations
ChrisTitusTech/linutil pull request #933
Opened 2024-11-10 11:01 UTC by jeevithakannan2

## Type of Change
- [x] Bug fix
- [x] Refactoring
- [x] UI/UX improvement

## Changes so for
- 1aa1dfe3823c1534aab93164d17f9619c66dd445 Use theme color instead of using ratatui::Color for running_command success and fail + search preview text color + min tui warning color, add colors for confirmation prompt, fix inverted success and fail colors 

## Testing
- WIP

## Impact

## Issues / other PRs related

- Resolves #

## Additional Information

## Checklist
- [ ] My code adheres to the coding and style guidelines of the project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no errors/warnings/merge conflicts.

2024-11-10 22:31 UTC, lj3954 commented
> * [0b4f33c](https://github.com/ChrisTitusTech/linutil/commit/0b4f33c761f27a2efb12628b60cb6b6afc89cd28) Use regex for case insensitive search, implement `String` instead of `char<Vec>` for `seach_input`, fix word disappearing by recalculating the render x for preview text.

Other than the last point, why would we want to do any of these things? Compiling a regex on each change to the search input makes the code less readable & negatively impacts performance compared to just taking the lowercase of the input, which we already do. Vec<char> is used to fix crashes upon inputting a multi-byte unicode character, unicode_width is used to fix incorrect cursor positioning with wider unicode characters. Both are niche issues, but I don't see the purpose of removing these fixes for absolutely no improvement.

> https://github.com/ChrisTitusTech/linutil/commit/3b7e859af80bfa1f453928a74c47efd897e26934 Replace redundant match statements with helper function in theme.rs.

Adding a new theme which has different colours for these theme elements could require these match statements be added back. This is the same thing you did when you suggested removing "unnecessary cases" in scripts. This change also does not improve readability.

I oppose these 2 commits. I'll review certain elements of the other changes in a few minutes.

2024-11-10 22:47 UTC, lj3954 commented on tui/src/confirmation.rs
> +        use ConfirmStatus::*;
I personally think this decreases readability, especially when `None` is one of the enum variants, easily confusable with Option::None. 

I agree with the change to KeyCode imports on the next line; it's generally not good practice to wildcard import enums with unit variants, as the removal of any unit variant you're referencing in a match statement will cause that pattern to match any variant.

2024-11-10 22:47 UTC, lj3954 commented on tui/src/confirmation.rs
> +    pub fn new(names: Vec<&str>) -> Self {
This change should be reverted, it's **always** good practice to only take a reference if you don't need an owned value, whether or not your code currently passes in only owned values.

2024-11-10 22:47 UTC, lj3954 commented on tui/src/confirmation.rs
> -            })
This code appears to be used to make all entries start at the same position on screen in the case that you have over 10 entries.
i.e.
```
  1. value1...
 10. value10...
100. value100
```
I don't personally care one way or the other whether this remains, but I figured I'd just specify its purpose in case you didn't understand when you made the change.

2024-11-11 00:45 UTC, nnyyxxxx commented
i personally think its better to keep it lowercase as it feels more snappier that way imo

2024-11-11 01:59 UTC, jeevithakannan2 commented on tui/src/confirmation.rs
> -            })
I think 
```
1. value1
10. value2
100. value3
```

![image](https://github.com/user-attachments/assets/1ad59299-27d4-4e31-9e40-289068f55373)

Is not a big difference from if we see in the image. Maybe this is upto everyones personal preference

```
    1. value1
  10. value 2
110. value 3
```

![image](https://github.com/user-attachments/assets/66313524-1cf4-4737-968a-f0e8fb9b4d76)

2024-11-11 02:30 UTC, jeevithakannan2 commented on tui/src/confirmation.rs
> +    pub fn new(names: Vec<&str>) -> Self {
I agree.

2024-11-11 02:36 UTC, jeevithakannan2 commented on tui/src/confirmation.rs
> +        use ConfirmStatus::*;
Since self.status expects ConfirmPrompt Enum think will not be an issue. I too think this decreases readability but in this context we are not using Options anywhere so user would know it is a ConfirmPrompt enum variant.

2024-11-11 08:10 UTC, jeevithakannan2 commented
> > * [0b4f33c](https://github.com/ChrisTitusTech/linutil/commit/0b4f33c761f27a2efb12628b60cb6b6afc89cd28) Use regex for case insensitive search, implement `String` instead of `char<Vec>` for `seach_input`, fix word disappearing by recalculating the render x for preview text.
> 
> Other than the last point, why would we want to do any of these things? Compiling a regex on each change to the search input makes the code less readable & negatively impacts performance compared to just taking the lowercase of the input, which we already do. `Vec<char>`, over String, is used to fix panics upon inputting a multi-byte unicode character, unicode_width is used to fix incorrect cursor positioning with wider unicode characters. Both are niche issues, but I don't see the purpose of removing these fixes for absolutely no improvement.
> 
> > [3b7e859](https://github.com/ChrisTitusTech/linutil/commit/3b7e859af80bfa1f453928a74c47efd897e26934) Replace redundant match statements with helper function in theme.rs.
> 
> ~Adding a new theme which has different colours for these theme elements could require these match statements be added back. This is the same thing you did when you suggested removing "unnecessary cases" in scripts. This change also does not improve readability.~
> 
> Sorry, I misunderstood the changes made in that commit. It's even worse an idea than what I thought you were doing. If more themes are added, you'd have to keep adding function parameters, making the code even more difficult to read. A match statement is by far the best choice there.
> 
> I oppose these 2 commits. I'll review certain elements of the other changes in a few minutes.

Thanks for the quick review. I forgot about the multi-byte characters reverted back to Vec<char> with some comments.

2024-11-11 10:05 UTC, jeevithakannan2 commented
@cartercanedy @lj3954 Why are using ansi colors for tree-sitter-highlighting instead of ratatui colors?

2024-11-11 13:32 UTC, cartercanedy commented
treesitter-highlight provides the machinery for interacting with the individual parsers for syntax highlighting, in our case it's the bash parser. This is necessary

Anstlye makes it easier to render the ansi color codes directly to a stream. There's some complication with using the ratatui text constructs since there might be some styling that needs to be applied over a line break, which would make parsing more complicated than necessary

2024-11-11 13:33 UTC, cartercanedy commented on tui/src/confirmation.rs
> -            })
This was a sticking point. I would leave it in

2024-11-11 14:22 UTC, jeevithakannan2 commented
Since we using custom colors for syntax_highlighting_styles maybe using the ratatui colors reduces the complexity?

2024-11-11 14:28 UTC, cartercanedy commented
Trust me, it's just going to get more complicated...

2024-11-11 14:30 UTC, jeevithakannan2 commented
Ok I will try my best and create a commit let me know what you think about it

2024-11-11 16:26 UTC, cartercanedy requested changes

2024-11-11 16:26 UTC, cartercanedy commented on tui/src/hint.rs
> +                .map(|s| Span::styled(*s, Style::default().bold()))
```suggestion
                .map(|s| Span::styled(Cow::<'_, str>::Borrowed(s) Style::default().bold()))
```

This isn't an optimization. There's no reason to deref the str slice, just use a `Cow` to prevent unnecessary copies. It's going to use a `Cow` under the hood, anyways. `Cow` is a part of `std`, so there's no benefit to removing the import either.

2024-11-11 16:26 UTC, cartercanedy commented on tui/src/hint.rs
> -use std::borrow::Cow;
Moo

2024-11-11 16:36 UTC, jeevithakannan2 commented on tui/src/hint.rs
> +                .map(|s| Span::styled(*s, Style::default().bold()))
Ahh I see.

2024-11-11 16:48 UTC, jeevithakannan2 commented on tui/src/hint.rs
> -use std::borrow::Cow;
Dropped the commit Mooooo

2024-11-11 17:00 UTC, jeevithakannan2 commented
Is it normal for the checkout process to take in 10min in typos workflow 🙄 https://github.com/ChrisTitusTech/linutil/actions/runs/11782804516/job/32818643344?pr=933

2024-11-11 17:05 UTC, cartercanedy commented
The initial checkout can get throttled, I've seen that happen in my own projects

2024-11-11 17:16 UTC, jeevithakannan2 commented
> The initial checkout can get throttled, I've seen that happen in my own projects

Are the changes to the anstyle good ? Did you review the changes?

2024-11-11 17:18 UTC, cartercanedy commented
Lgtm

2024-11-11 18:24 UTC, cartercanedy commented on tui/src/state.rs
>          self.spawn_float(command, 80, 80);
I like what I see here, nice work

2024-11-11 18:27 UTC, cartercanedy commented
I've noticed that Chris can get overwhelmed and slightly annoyed with larger PRs, and I think this is starting to become too sprawling. I would break it down so that each PR is more atomic and understandable in its own context.

2024-11-11 18:38 UTC, jeevithakannan2 commented
> I don't want to put words in his mouth, but I've noticed that Chris can get overwhelmed and slightly annoyed with larger PRs. With that said, I think this is starting to become too sprawling; I would break it down so that each PR is more atomic and understandable in its own context.

I agree but I have seen huge PRs in winutil with clear description. If multiple people like you guys go through the code base and approve it won't be a problem for Chris. Let me finish this for now and then decide whether we can split it to smaller ones. The thing is there are minor changes in every file which don't need a separate PR so I thought instead of creating separate PRs for each and every file or change why not create a single PR with all the rust changes included. Still it's not too late, this is WIP and can be split into separate PRs if wanted.

2024-11-11 18:47 UTC, lj3954 commented
Please drop 6e5fe07, it duplicates #935.

2024-11-12 08:02 UTC, lj3954 requested changes
I think this is more concise.

2024-11-12 08:09 UTC, lj3954 commented on tui/src/filter.rs
>          }
```suggestion
        });
```

Alongside my other suggested change. A semicolon should be suffixed for good practice since this is a statement, rather than just an expression which happens to return a unit type.

2024-11-12 13:32 UTC, jeevithakannan2 commented on tui/src/filter.rs
> +            })
@lj3954 Can you open a PR to my branch I think your suggestion here have errors ( might be because you used your browser )

2024-11-12 13:46 UTC, jeevithakannan2 commented on tui/src/filter.rs
> +            })
```rust
let render_completion = !(self.items.is_empty() || self.search_input.is_empty());
        self.completion_preview = render_completion.then(|| {
            let input = self.search_input.iter().collect::<String>().to_lowercase();
            self.items
                .iter()
                .find_map(|item| {
                    let item_name_lower = item.node.name.to_lowercase();
                    (item_name_lower.starts_with(&input))
                        .then_some(item_name_lower[input.len()..].to_string())
                })
                .unwrap_or("".to_string())
        });
```

Is this the suggestion?

2024-11-12 15:25 UTC, lj3954 commented on tui/src/filter.rs
> +            })
Whoops, the suggestion with then() wouldn't work given that we're returning an optional value.

2024-11-12 15:28 UTC, lj3954 requested changes

2024-11-12 15:28 UTC, lj3954 commented on tui/src/filter.rs
> +                }
```suggestion
                let item_name_lower = item.node.name.to_lowercase();
                (item_name_lower.starts_with(&input))
                    .then_some(item_name_lower[input.len()..].to_string())
```

2024-11-12 15:37 UTC, jeevithakannan2 commented on tui/src/filter.rs
> +                }
Yupp !!!

2024-11-15 19:54 UTC, jeevithakannan2 commented
@ChrisTitusTech A new crates.io publish should be made for the CI/CD pipeline and for the program to work due to the merge of https://github.com/ChrisTitusTech/linutil/pull/949

2024-11-16 01:19 UTC, lj3954 commented
Making the theme functions const doesn't accomplish anything useful; they'll still be evaluated at runtime since the theme is not known at compile time.

2024-11-16 01:20 UTC, lj3954 commented
We also should not be merging PRs like this. I find it unlikely Chris will accept anything with a 1500 line diff.

2024-11-16 02:18 UTC, jeevithakannan2 commented
> Making the theme functions const doesn't accomplish anything useful; they'll still be evaluated at runtime since the theme is not known at compile time.

It may not be now. But if we decide to change how themes work instead of passing the default theme at run time making it as default during compile time will make this more efficient.

2024-11-16 02:19 UTC, jeevithakannan2 commented
> We also should not be merging PRs like this. I find it unlikely Chris will accept anything with a 1500 line diff.

I'm aware of that. What can we do? Do I create 9 separate PRs for each commit?

2024-11-16 02:25 UTC, cartercanedy commented
> > Making the theme functions const doesn't accomplish anything useful; they'll still be evaluated at runtime since the theme is not known at compile time.
> 
> It may not be now. But if we decide to change how themes work instead of passing the default theme at run time making it as default during compile time will make this more efficient.

I don't mind the idea of marking methods const when compatible, but I don't see any way that the theme will ever become a compile-time constant as long as it remains configurable at runtime.

2024-11-16 02:30 UTC, cartercanedy commented
> > We also should not be merging PRs like this. I find it unlikely Chris will accept anything with a 1500 line diff.
> 
> I'm aware of that. What can we do? Do I create 9 separate PRs for each commit?

Yes

2024-11-17 01:44 UTC, adamperkowski commented
man that diff is HUGE
@jeevithakannan2, the conflict-creator

2024-11-17 01:46 UTC, jeevithakannan2 commented
> man that diff is HUGE
> @jeevithakannan2, the conflict-creator

I know we have put a lot of time into this. Separating the PRs will do the same. But this makes the program more efficient in many areas. Can't complain.

2024-11-17 18:24 UTC, merged

2024-11-17 18:26 UTC, adamperkowski commented
Didn't expect you to actually merge this huge diff but ok.