Zen Browser installation
ChrisTitusTech/linutil pull request #940
Opened 2024-11-12 11:15 UTC by d7omdev

## Type of Change
- [x] New feature

## Description
- Added [Zen](https://zen-browser.app/) browser installation script.

## Testing
- Tested on arch and fedora without issues.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-11-12 11:20 UTC, nnyyxxxx approved these changes

2024-11-12 15:16 UTC, jeevithakannan2 requested changes
Drop the changes to docs. The doc is moved to https://github.com/Chris-Titus-Docs/linutil-docs

2024-11-12 15:16 UTC, jeevithakannan2 commented on core/tabs/applications-setup/browsers/zen-browser.sh
> +    if ! command_exists zen-browser; then
```suggestion
    if ! command_exists io.github.zen_browser.zen && ! command_exists zen-browser; then
```

2024-11-12 15:36 UTC, jeevithakannan2 approved these changes

2024-11-17 01:42 UTC, adamperkowski approved these changes

2024-11-27 00:06 UTC, afonsofrancof approved these changes

2025-02-02 04:13 UTC, ChrisTitusTech approved these changes

2025-02-02 04:13 UTC, merged