Linutil installer and updated refact
ChrisTitusTech/linutil pull request #956
Opened 2024-11-19 02:11 UTC by jeevithakannan2

## Type of Change
- [x] Bug fix
- [x] Refactoring

## Description
Installer -> Remove unreachable pacman case. dnf requires rustup-init before using rustup-init. Source .cargo/env after the installation of rustup.

Updater -> Formatting, Install rustup from dnf, change the wild case to use rustup.rs general installer from rust. Source the .cargo/env after the installation of rustup.

## Testing
- Tested on fedora 41 without issues.

## Issues / other PRs related
- Resolves #955 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-11-19 07:32 UTC, adamperkowski commented on core/tabs/applications-setup/linutil-installer.sh
> +                                rustup-init -y
```suggestion
```

2024-11-19 07:34 UTC, adamperkowski requested changes

2024-11-19 07:34 UTC, adamperkowski commented on core/tabs/applications-setup/linutil-updater.sh
> +                rustup-init -y
```suggestion
```

2024-11-19 07:34 UTC, adamperkowski commented on core/tabs/applications-setup/linutil-updater.sh
> +                rustup-init -y
```suggestion
```

2024-11-19 08:28 UTC, jeevithakannan2 commented
No until you do rustup-init rustup command will not be available in fedora and alpine

2024-11-19 12:11 UTC, adamperkowski approved these changes
Oh okay then. Couldn't find any official documentation on it, that's why I commented.

2025-06-20 18:15 UTC, ChrisTitusTech approved these changes

2025-06-20 18:15 UTC, merged