System information in Bug Report Template
ChrisTitusTech/linutil pull request #958
Opened 2024-11-19 16:14 UTC by jeevithakannan2

## Type of Change
- [x] Documentation update

## Description
Add system information in Bug Report Template

2024-11-20 02:50 UTC, lj3954 requested changes

2024-11-20 02:50 UTC, lj3954 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Version and branch of linutil: Version can be found inside linutil. Branch (Stable/Dev).
```suggestion
Distribution: 
DE/WM (GNOME, Hyprland, etc): 
Windowing System (X11/Wayland): 
Linutil version (found on the top of the list within linutil):
Branch (stable/prerelease/master): 
```

2024-11-22 15:53 UTC, adamperkowski approved these changes

2024-11-23 01:11 UTC, lj3954 approved these changes

2024-12-06 14:30 UTC, AkkhilCodingHub reviewed
We should include support in major distributions like Ubuntu, Kali linux, Debian, Arch


The list of releases is available in releases tab

2025-01-21 00:21 UTC, jeevithakannan2 commented
Closing as this is merged in https://github.com/ChrisTitusTech/linutil/pull/1004

2025-01-21 00:21 UTC, closed without merging