Fix bluetooth manager
ChrisTitusTech/linutil pull request #959
Opened 2024-11-20 06:19 UTC by jeevithakannan2

## Type of Change
- [x] Bug fix

## Description
- Added missing bluez package.
- Removed unused variable `action`.
- Fix usage of locally modified variable`(i)` value.
- Strip of some unwanted comments
- For some odd reason the read at the end of the loop is not working. So it was added to each if block.

## Testing
- Tested on arch linux without issues

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-11-20 07:52 UTC, adamperkowski approved these changes

2024-11-20 07:52 UTC, adamperkowski commented on core/tabs/common-service-script.sh
> +checkInitManager 'systemctl rc-service'
Could you reset this file?

2024-11-30 06:57 UTC, AkkhilCodingHub requested changes
We may want to keep user input for going back to the main menue Or  maybe implement to go to a specific section

2025-06-20 18:17 UTC, ChrisTitusTech approved these changes

2025-06-20 18:17 UTC, merged