docs(README): wrong crate name in `cargo install` instructions
ChrisTitusTech/linutil pull request #964
Opened 2024-11-22 15:47 UTC by adamperkowski

Resolves #963

2024-11-22 16:05 UTC, jeevithakannan2 approved these changes

2024-11-22 19:53 UTC, OvermindDL1 requested changes

2024-11-22 19:53 UTC, OvermindDL1 commented on README.md
> +cargo install linutil_tui
Should probably add `--locked` to it as well since the version currently on crates cannot compile because one of the dependencies broke semver. Using `--locked` will have the install only use the dependent versions that are in the Cargo.lock file rather than the latest semver matching ones.

(The broken dependency really needs to fix that, `cargo-semver-checks` exists for a reason after all, lol)

2024-11-22 20:14 UTC, adamperkowski commented on README.md
> +cargo install linutil_tui
Thanks for pointing that out. I really have no idea what's going on with versioning here. I'll try to fix all this today but @ChrisTitusTech IMO you really should check if crates 100% work before releasing.

I'm not sure if this will work though, as `Cargo.lock` is not included in the packages.
https://github.com/ChrisTitusTech/linutil/blob/ab7a67087d8387d38cbc839c4725aaf89a70675a/tui/Cargo.toml#L10
https://github.com/ChrisTitusTech/linutil/blob/ab7a67087d8387d38cbc839c4725aaf89a70675a/core/Cargo.toml#L8

2024-11-22 20:20 UTC, adamperkowski commented
@ChrisTitusTech Why is the version in `Cargo.toml` = `24.9.28` on the `24.10.31` branch?
https://github.com/ChrisTitusTech/linutil/blob/00914ab05dd64b893e05d1e9b43d8b9e84a7918c/Cargo.toml#L3

2024-11-22 22:14 UTC, lj3954 commented
> @ChrisTitusTech Why is the version in `Cargo.toml` == `24.9.28` on the `24.10.31` tag?
> 
> https://github.com/ChrisTitusTech/linutil/blob/00914ab05dd64b893e05d1e9b43d8b9e84a7918c/Cargo.toml#L3

#965 will resolve this issue.

2024-11-25 00:16 UTC, ChrisTitusTech approved these changes

2024-11-25 00:16 UTC, merged