Move the installation procedure before usage in README
ChrisTitusTech/linutil pull request #970
Opened 2024-11-30 12:24 UTC by jeevithakannan2

## Type of Change
- [x] Documentation update

## Description
- Adjust the README structure to place the the usage section after the installation procedure.

2024-11-30 21:52 UTC, lj3954 commented on README.md
> +```
This section should be merged into installation.

2024-12-17 18:14 UTC, adamperkowski requested changes

2025-01-20 13:07 UTC, jeevithakannan2 commented on README.md
> +```
It's not in installation the USAGE is a separate section both are H2

2025-01-20 13:08 UTC, jeevithakannan2 commented on README.md
> +```
It would look like this https://github.com/jeevithakannan2/linutil/tree/patch-3

2025-02-12 12:42 UTC, nnyyxxxx commented
merge upstream please, cli flags were removed from the documentation

2025-06-20 18:21 UTC, closed without merging