Refact:- Simplifying Brave install script
ChrisTitusTech/linutil pull request #980
Opened 2024-12-11 05:59 UTC by Angxddeep

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Documentation update
- [x] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
So the folks at Brave made an all-in-one curl script for Linux, so just using that is better than the mess we have today.

## Testing
Tested and works

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-12-15 17:46 UTC, afonsofrancof approved these changes
LGTM

2025-01-10 04:00 UTC, adamperkowski approved these changes

2025-01-10 04:01 UTC, adamperkowski commented
i think we should remove brave installation entirely if there's a one-line universal solution. @ChrisTitusTech ?

2025-01-10 04:02 UTC, adamperkowski requested changes
i think we should remove brave installation entirely if there's a one-line universal solution. @ChrisTitusTech ?

2025-01-10 07:14 UTC, lj3954 commented
> i think we should remove brave installation entirely if there's a one-line universal solution. @ChrisTitusTech ?

Linutil has options to install firefox, chromium, etc, even though they're essentially the same line. I think it's better to keep it around.

2025-02-28 20:47 UTC, ChrisTitusTech approved these changes

2025-02-28 20:47 UTC, merged